### PR TITLE
Fix bug not remove offline node

### PR DESCRIPTION
**Pull request by yah01**
#17411 #17426 #17367 
The LoadBalance task won't remove the offline node if the node never load/watch any segment/dmchannel

Signed-off-by: yah01 <yang.cen@zilliz.com>

### CODE REVIEW

**Review by congqixia — APPROVED** [review]
/lgtm

**Comment by xiaofan-luan** [comment]
OK to me, but the replicaID thing in DmChannelWatchInfo is weird to me. 
We should deprecated. it

**Comment by jiaoew1991** [comment]
related to https://github.com/milvus-io/milvus/issues/17556

**Pull request merged**
