### PR TITLE
enhance: move segcore codes of segment into one package

### PR DESCRIPTION
**Pull request by chyezh**
issue: #33285

- move most cgo opeartions related to search/query into segcore package for reusing for streamingnode.
- add go unittest for segcore operations.

### CODE REVIEW

**Comment by chyezh** [comment]
rerun go-sdk

**Comment by chyezh** [comment]
rerun cpp-unit-test

**Comment by chyezh** [comment]
rerun cpp-unit-test

**Comment by chyezh** [comment]
rerun cpp-unit-test

**Comment by chyezh** [comment]
rerun cpp-unit-test

**Comment by chyezh** [comment]
rerun cpp-unit-test

**Review by congqixia — APPROVED** [review]
/lgtm

**Pull request merged**
