### PR TITLE
Fix bitSet panic: runtime error: makeslice: len out of range (#27939)

### PR DESCRIPTION
**Pull request by ulovecode**
/kind bug
issue: #27939

### CODE REVIEW

**Comment by yhmo** [comment]
#27939

**Comment by ulovecode** [comment]
related issue: https://github.com/milvus-io/milvus/discussions/27939

**Comment by ulovecode** [comment]
/kind bug
fix https://github.com/milvus-io/milvus/discussions/27939

**Comment by ulovecode** [comment]
能把 do-not-merge missing-related-issue 这个label 删掉吗。然后合并进去

**Comment by ulovecode** [comment]
@xiaofan-luan

**Comment by ulovecode** [comment]
issue: https://github.com/milvus-io/milvus/discussions/27939

**Comment by yhmo** [comment]
@ulovecode 
Try to modify the comment "fix https://github.com/milvus-io/milvus/discussions/27939" to "issue: https://github.com/milvus-io/milvus/discussions/27939"

**Pull request merged**
