### PR TITLE
enhance: [2.5] Release compacted growing segment if in dropped list (#37245)

### PR DESCRIPTION
**Pull request by congqixia**
Cherry pick from master
pr: #37245
See also #37205

Previously releasing growing segments could be triggered by two conditions:

- Sealed Segment with same id is loaded
- Segment start position is before target checkpoint ts

Which has a worst case that the corresponding sealed segment is compacted and the checkpoint is pinned by a growing l0 segment.

This PR introduces a new rule that: a growing segment could be released if the segment id appeared in current target dropped segment id list.

### CODE REVIEW

**Comment by congqixia** [comment]
cpp-unit-test

**Comment by congqixia** [comment]
rerun go-sdk
rerun cpp-unit-test

**Comment by congqixia** [comment]
rerun go-sdk

**Comment by congqixia** [comment]
rerun cpp-unit-test

**Review by XuanYang-cn — APPROVED** [review]
/lgtm

**Pull request merged**
