### PR TITLE
doc: Changes in README.md file

### PR DESCRIPTION
**Pull request by iamvbenz49**
issue: #38797
Before:
Screenshot from 2024-12-27 18-41-24

 There was no inclusion of the embedding function used which will be quite harder for a beginner to understand
After:
Screenshot from 2024-12-27 18-43-37
 A sample embedding function

### CODE REVIEW

**Comment by yanliang567** [comment]
@iamvbenz49  you need to pass the dco check, which requires -s in the commit.

**Comment by yanliang567** [comment]
/assign @liliu-z 
please help to review the pr

**Comment by xiaofan-luan** [comment]
@iamvbenz49 
please use git commit -sm "commit message" and make sure you set the right commit message

**Comment by iamvbenz49** [comment]
I will do it

**Pull request closed without merging**
