### PR TITLE
Disable retryKeepAlive when LivenessCheck's Context close

### LINKED ISSUE #25174: [Enhancement]: Disable retryKeepAlive when LivenessCheck's Context close
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

Disable retryKeepAlive when LivenessCheck's Context close

### Why is this needed?

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by wayblink**
#25174

### CODE REVIEW

**Comment by xiaofan-luan** [comment]
@wayblink 
are there any race for enableRetryKeepAlive?

**Comment by wayblink** [comment]
rerun ut

**Comment by wayblink** [comment]
> @wayblink are there any race for enableRetryKeepAlive?

no race, something wrong with code coverage

**Pull request merged**
