### PR TITLE
Cherry pick some feature and bug fix in querycoordv2.

### PR DESCRIPTION
**Pull request by sunby**
Signed-off-by: Wei Liu <wei.liu@zilliz.com>

Signed-off-by: Wei Liu <wei.liu@zilliz.com>

### CODE REVIEW

**Review by congqixia — APPROVED** [review]
/lgtm

**Comment by jiaoew1991** [comment]
issue: #20371

**Comment by sunby** [comment]
issue : https://github.com/milvus-io/milvus/issues/20371

**Comment by sunby** [comment]
related issue: https://github.com/milvus-io/milvus/issues/20371

**Pull request merged**
