### PR TITLE
support configurable sasl mechanisms for kafka

### PR DESCRIPTION
**Pull request by jaime0815**
issue. #17541 
Signed-off-by: yun.zhang <yun.zhang@zilliz.com>

### CODE REVIEW

**Comment by jaime0815** [comment]
backport to 2.1 https://github.com/milvus-io/milvus/pull/17542

**Comment by erezweissgloat** [comment]
Will it be merged soon?

**Comment by erezweissgloat** [comment]
@jaime0815 @yanliang567 
Thanks!
Can it be merged also to v2.1.1?
It presents in v2.1.0 and in master lol

**Comment by yanliang567** [comment]
there is no 2.1.1 branch, v2.1.1 release would be tagged on branch 2.1.0

**Comment by erezweissgloat** [comment]
@yanliang567 Thank you! 
Please help me understand the issue:
v2.1.1 version tag already tagged - this version tag only (and not v1.1.0) supports "S3 with iAM role", but sadly not this secured sasl mechanisms Kafka protocol.
What image version may I use to get both of the abilities? Do I have to wait for v2.1.2? Thx!

**Comment by yanliang567** [comment]
i am afraid yes, you have to wait for v2.1.2, which would be released at the end of this week.

**Comment by erezweissgloat** [comment]
Hey!
We are keep waiting for the v2.1.2 version.
Will it be released soon?
thanks a lot
Erez,
Gloat

‫בתאריך יום ב׳, 22 באוג׳ 2022 ב-14:03 מאת ‪yanliang567‬‏ <‪
***@***.***‬‏>:‬

**Pull request merged**
