### PR TITLE
Implements restful entities api

### PR DESCRIPTION
**Pull request by haorenfsa**
Signed-off-by: shaoyue.chen <shaoyue.chen@zilliz.com>
part of #7700 
/cc @congqixia @Anosh21 @ArkaprabhaChakraborty

### CODE REVIEW

**Comment by ArkaprabhaChakraborty** [comment]
Uhh, the coverage dropped.

**Comment by haorenfsa** [comment]
> Uhh, the coverage dropped.

It's a WIP, unit test not added yet,  any advice about the url `path` layout?

**Comment by ArkaprabhaChakraborty** [comment]
> > Uhh, the coverage dropped.
> 
> It's a WIP, unit test not added yet, any advice about the URL `path` layout?

The path layout looks fine to me.

**Comment by haorenfsa** [comment]
> > > Uhh, the coverage dropped.
> > 
> > 
> > It's a WIP, unit test not added yet, any advice about the URL `path` layout?
> 
> The path layout looks fine to me.

Tests added, I also alter the `path` a bit.

**Review by congqixia — APPROVED** [review]
/lgtm

**Pull request merged**
