### PR TITLE
enhance: use already installed vcpkg

### PR DESCRIPTION
**Pull request by PowderLi**
issue #28686
1. Update Builder gpu image changes, see changes #28505
2. update azure-identity-cpp from beta to release

### CODE REVIEW

**Comment by PowderLi** [comment]
rerun ut

**Comment by PowderLi** [comment]
rerun ut

**Comment by PowderLi** [comment]
rerun ut

**Comment by PowderLi** [comment]
rerun ut

**Review by yellow-shine — COMMENTED** [review]
/lgtm for the  workflow part

**Pull request merged**
