### PR TITLE
enhance: support httpv1/v2 throttle and add it for httpV2(#35350)

### PR DESCRIPTION
**Pull request by MrPresent-Han**
related: #35350

### CODE REVIEW

**Comment by jaime0815** [comment]
A more elegant solution is to define a unified handler function with the Gin API to intercept HTTP requests and check rate limits.

**Comment by MrPresent-Han** [comment]
> A more elegant solution is to define a unified handler function in routers handle interface to intercept HTTP requests and check rate limits.

true, this way is more elegant

**Comment by MrPresent-Han** [comment]
rerun ut

**Pull request merged**
