### PR TITLE
fix: merge index params when creating index

### PR DESCRIPTION
**Pull request by sunby**
issue: https://github.com/milvus-io/milvus/issues/31102

### CODE REVIEW

**Comment by weiliu1031** [comment]
`CreateIndex` and `AlterIndex` both inherit the mmap param through `UpdateParam` func, which is abit confused, we need some ut here to make sure that mmap param has been passed. 

should be fixed in next pr

**Comment by congqixia** [comment]
Code here is messy, any idea to fix this?
/approve

**Comment by sunby** [comment]
> Code here is messy, any idea to fix this? /approve

agree, maybe we should refactor these codes.

**Pull request merged**
