### PR TITLE
[skip ci]Require related issue in PR

### PR DESCRIPTION
**Pull request by wxyucs**
To make sure each PR link to an issue, otherwise blocking automatic merging.

Signed-off-by: Xiangyu Wang <xiangyu.wang@zilliz.com>

### CODE REVIEW

**Comment by scsven** [comment]
@jeffoverflow Should we add a rule that if `do-not-merge/missing-related-issue` existed in a PR, blocking merge?

**Comment by xiaofan-luan** [comment]
/approve 

we may also want to check the milestone of current pull request

**Comment by scsven** [comment]
> /approve
> 
> we may also want to check the milestone of current pull request

OK, I will update this pr, add a condition that if a PR missing milestone then blocking merge.

**Comment by scsven** [comment]
@xiaofan-luan The milestone just can be set by who has `write` permission in this repo. So outside collaborators cannot set this item.

**Pull request merged**
