### PR TITLE
fix: Fix checkGeneralCapacity slowly

### PR DESCRIPTION
**Pull request by bigsheeper**
Cache the general count to speed up `checkGeneralCapacity`.

issue: https://github.com/milvus-io/milvus/issues/37630

### CODE REVIEW

**Comment by czs007** [comment]
rerun go-sdk

**Comment by bigsheeper** [comment]
### Enhancements and Fixes

- [ ] Mutex & Metadata
  - [ ] Rootcoord
    - [ ] GeneralCount 
      - master https://github.com/milvus-io/milvus/pull/37976
      - 2.5 https://github.com/milvus-io/milvus/pull/37976
      - 2.4 https://github.com/milvus-io/milvus/pull/38074
    - [ ] Rootcoord meta
      - master https://github.com/milvus-io/milvus/pull/38799
      - 2.5 https://github.com/milvus-io/milvus/pull/38902
      - 2.4 https://github.com/milvus-io/milvus/pull/38903
  - [ ] Datacoord
    - [ ] SegmentManager
      - master https://github.com/milvus-io/milvus/pull/37836 
      - 2.5 https://github.com/milvus-io/milvus/pull/37836 
      - 2.4 https://github.com/milvus-io/milvus/pull/37869
    - [ ] Datacoord meta
      - master https://github.com/milvus-io/milvus/pull/38219
      - 2.5 https://github.com/milvus-io/milvus/pull/38904
      - 2.4 https://github.com/milvus-io/milvus/pull/38230
    - [ ] BufferManager
      - master https://github.com/milvus-io/milvus/pull/37817
      - 2.5 https://github.com/milvus-io/milvus/pull/37817
      - 2.4 https://github.com/milvus-io/milvus/pull/37897
    - [ ] Remove frequently updating metric
      - master https://github.com/milvus-io/milvus/pull/38775
      - 2.5 https://github.com/milvus-io/milvus/pull/38778
      - 2.4 https://github.com/milvus-io/milvus/pull/38776
  - [ ] Querycoord
    - [ ] ReplicaManager
      - master https://github.com/milvus-io/milvus/pull/37906
      - 2.5 https://github.com/milvus-io/milvus/pull/37906
      - 2.4 https://github.com/milvus-io/milvus/pull/37970
    - [ ] TargetObserver
      - master https://github.com/milvus-io/milvus/pull/37454
      - 2.5 https://github.com/milvus-io/milvus/pull/37454
      - 2.4 https://github.com/milvus-io/milvus/pull/37735
    - [ ] Remove dist clone
      - master https://github.com/milvus-io/milvus/pull/37797
      - 2.5 https://github.com/milvus-io/milvus/pull/37797
      - 2.4 https://github.com/milvus-io/milvus/pull/37833
    - [ ] LeaderView
      - master https://github.com/milvus-io/milvus/pull/37777
      - 2.5 https://github.com/milvus-io/milvus/pull/37777
      - 2.4 https://github.com/milvus-io/milvus/pull/37802
    - [ ] 
      - master https://github.com/milvus-io/milvus/pull/38311
      - 2.5
      - 2.4
    - [ ] 
      - master https://github.com/milvus-io/milvus/pull/38566
      - 2.5
      - 2.4
  - [ ] Querynode
    - [ ] 
      - master https://github.com/milvus-io/milvus/pull/38599
      - 2.5
      - 2.4
    - [ ] 
      - master https://github.com/milvus-io/milvus/pull/38813
      - 2.5
      - 2.4

- [ ] RPC & CPU
  - https://github.com/milvus-io/milvus/pull/37815
  - https://github.com/milvus-io/milvus/pull/37863
  - https://github.com/milvus-io/milvus/pull/38059

- [ ] Memory
  - https://github.com/milvus-io/milvus/pull/37696
  - https://github.com/milvus-io/milvus/pull/38816
  - https://github.com/milvus-io/milvus/pull/38129
  - https://github.com/milvus-io/milvus/pull/36628

- [ ] Recovery
  - https://github.com/milvus-io/milvus/pull/38028
  - https://github.com/milvus-io/milvus/pull/38151
  - https://github.com/milvus-io/milvus/pull/38248
  - https://github.com/milvus-io/milvus/pull/38308
  - https://github.com/milvus-io/milvus/pull/38403
  - https://github.com/milvus-io/milvus/pull/38455
 
- [ ] Balance
  - https://github.com/milvus-io/milvus/pull/38143

**Pull request merged**
