### PR TITLE
Remove golint to avoid deprecated warnings

### PR DESCRIPTION
**Pull request by wxyucs**
Signed-off-by: Xiangyu Wang <xiangyu.wang@zilliz.com>

/kind improvement
/cc @congqixia

### CODE REVIEW

**Comment by congqixia** [comment]
It's not a good idea to remove `golint` without enabling `revive` or other replacement.

**Comment by scsven** [comment]
> It's not a good idea to remove `golint` without enabling `revive` or other replacement.

OK, I will update this change and enable the `revive` linter. 

/hold

**Comment by scsven** [comment]
Hi @congqixia, I enabled the revive linter, and I just added one rule into the config file. Many rules I cannot decide whether it's useful for us, so adding rules when needed may be better.

**Review by congqixia — APPROVED** [review]
/lgtm

**Comment by scsven** [comment]
/unhold
@congqixia please help to review this pr.

**Review by congqixia — APPROVED** [review]
/lgtm

**Pull request merged**
