### PR TITLE
enhance: add metrics for stopping querynode balance progress (#29201)

### PR DESCRIPTION
**Pull request by weiliu1031**
pr: #29201
This PR add three metrics to track the stopping balance progress.

### CODE REVIEW

**Comment by yanliang567** [comment]
e2e passed, rerun by mistake.
manual pass

**Comment by weiliu1031** [comment]
rerun ut

**Comment by weiliu1031** [comment]
rerun ut

**Review by congqixia — APPROVED** [review]
/lgtm

**Pull request merged**
