### PR TITLE
fix: grant ManualCompact api doesn't work (#38096)

### PR DESCRIPTION
**Pull request by weiliu1031**
issue: #38086
pr: #38096
cause ManualCompact api pass collection id in request, but RBAC requires to check collection name, so grant ManualCompact api doesn't work.

This PR refine the ManualCompact api to accpet collection name in request.

### CODE REVIEW

**Review by XuanYang-cn — APPROVED** [review]
/lgtm

**Review by congqixia — APPROVED** [review]
/approve

**Pull request merged**
