### PR TITLE
feat: add enable_tokenizer params to VarChar field

### PR DESCRIPTION
**Pull request by zhengbuqian**
issue: #35922

add an enable_tokenizer param to varchar field: must be set to true so that a varchar field can enable_match or used as input of BM25 function

### CODE REVIEW

**Comment by czs007** [comment]
e2e is not triggered. @zhengbuqian

**Comment by zhengbuqian** [comment]
rerun go-sdk

**Comment by zhengbuqian** [comment]
e2e is failing due to PyMilvus SDK not yet recognizing the `enable_tokenizer` params. should be fixed after https://github.com/milvus-io/pymilvus/pull/2273 merged.

**Comment by zhengbuqian** [comment]
rerun go-sdk

**Pull request merged**
