### PR TITLE
fix: Fix insert not limited when set collection.insertRate.max.mb=0

### PR DESCRIPTION
**Pull request by xige-16**
issue: #33722 
pr: #31070 
/kind bug

### CODE REVIEW

**Comment by xige-16** [comment]
rerun ut

**Comment by xige-16** [comment]
Can any kind person tell me why I failed the cpu-e2e test?

**Comment by xiaofan-luan** [comment]
e2e is not working

other wise looks good to me
/lgtm
/approve

**Comment by xige-16** [comment]
e2e does not work, please merge this pr manually. 
@xiaofan-luan @czs007

**Comment by xiaofan-luan** [comment]
@samhuang-z 
could you help on checking milvus 2.3 e2e? seems compilation is not working as expect

**Comment by xige-16** [comment]
need lgtm @xiaofan-luan @yanliang567

**Pull request merged**
