### PR TITLE
tracing enhancement

### PR DESCRIPTION
**Pull request by Zach41**
cherry-pick from master
1. refine logging interfaces
2. adjust logs for query/search requests

Related Issue: https://github.com/milvus-io/milvus/issues/17603

Signed-off-by: Zach41 <zongmei.zhang@zilliz.com>

### CODE REVIEW

**Comment by Zach41** [comment]
rerun ut

**Comment by Zach41** [comment]
`rerun ut`

**Comment by Zach41** [comment]
rerun ut

**Comment by bigsheeper** [comment]
https://github.com/milvus-io/milvus/pull/19023

**Comment by bigsheeper** [comment]
https://github.com/milvus-io/milvus/pull/19023

**Pull request closed without merging**
