### PR TITLE
[skip ci]Format code style

### PR DESCRIPTION
**Pull request by zhuwenxing**
Signed-off-by: zhuwenxing <wenxing.zhu@zilliz.com>

/kind improvement

### CODE REVIEW

**Review by yanliang567 — COMMENTED** [review]
/lgtm
/approve

**Comment by zhuwenxing** [comment]
/assign @yanliang567 

Please assign the LGTM label again.  The previous one was removed due to resolving conflict.

**Review by yanliang567 — COMMENTED** [review]
/lgtm

**Pull request merged**
