### PR TITLE
Fix about high level restful api

### LINKED ISSUE #25482: [Bug]: [restful] Dynamic field can not be shown when it is include in output field
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.0-20230710-4dd02836
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

insert data
image

get data by id
image

### Expected Behavior

`book_id` and `word_count` should in response

### Steps To Reproduce

_No response_

### Milvus Log

_No response_

### Anything else?

_No response_

### LINKED ISSUE #25497: [Bug]: [restful] Data is None (or null) when result is empty
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

The data will be None when there is no collection for list collections or no result for get and query.

```
{'code': 200, 'data': None}
```

### Expected Behavior

It would be more reasonable to change it be []. (empty list)

And for the serverless restful API, it behaves like the way above (use [] rather than None)

### Steps To Reproduce

_No response_

### Milvus Log

_No response_

### Anything else?

_No response_

### LINKED ISSUE #25502: [Bug]: [restful]Dim info was not in response of describe collection
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.0-20230710-4dd02836
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```
{"code":200,"data":{"collectionName":"test_collection_2023_07_11_19_49_16","description":"","enableDynamic":true,"fields":[{"autoId":true,"description":"","name":"id","primaryKey":true,"type":"Int64"}...false,"description":"","name":"emb","primaryKey":false,"type":"FloatVector"}],"indexes":[{"fieldName":"emb","indexName":"_default_idx_101","metricType":"L2"}],"load":"LoadStateLoading","shardsNum":2}}
```

We can only know it is FloatVector, but can not know the dim of it.

### Expected Behavior

in the serverless restful API implement, it was included in type like `floatVector(768)`

### Steps To Reproduce

_No response_

### Milvus Log

_No response_

### Anything else?

_No response_

### LINKED ISSUE #25509: [Bug]: [restful]Create collection can success with dbName which has not been created, but list collections with same dbName failed
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.0-20230710-4dd02836
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

create collection
```
POST http://10.100.36.162:19530/v1/vector/collections/create
200
40 ms
POST /v1/vector/collections/create HTTP/1.1
Content-Type: application/json
Authorization: Bearer root:Milvus
User-Agent: PostmanRuntime/7.32.3
Accept: */*
Postman-Token: d018aff4-c89b-47f4-be5b-1a6d7bc01558
Host: 10.100.36.162:19530
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
Content-Length: 132
 
{
"collectionName": "book",
"dbName": "demo",
"dimension": 2,
"metricsType": "L2",
"vectorField": "book_intro"
}
 
HTTP/1.1 200 OK
Content-Type: application/json; charset=utf-8
Date: Wed, 12 Jul 2023 02:36:18 GMT
Content-Length: 22
 
{"code":200,"data":{}}
```

list collection
```
GET http://10.100.36.162:19530/v1/vector/collections?dbName=demo
200
18 ms
GET /v1/vector/collections?dbName=demo HTTP/1.1
Authorization: Basic cm9vdDpNaWx2dXM=
User-Agent: PostmanRuntime/7.32.3
Accept: */*
Postman-Token: 0d020f99-4de3-4ddf-b5ae-c1b07549afd2
Host: 10.100.36.162:19530
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
 
HTTP/1.1 200 OK
Content-Type: application/json; charset=utf-8
Www-Authenticate: Basic realm="restricted", charset="UTF-8"
Date: Wed, 12 Jul 2023 02:37:54 GMT
Content-Length: 104
 
{"code":400,"error":"ShowCollections failed: database:demo not found","message":"show collections fail"}
```

### Expected Behavior

the requests all successful or all fail

### Steps To Reproduce

_No response_

### Milvus Log

_No response_

### Anything else?

Since Restful does not have an API to manage the database, we can not use the database if we choose Restful as the only tech stack to develop with Milvus.

We need to use SDK like pymilvus to create a database and then go back to using restful API with this database.

In short, using restful API can not get a complete lifecycle, and need to be used in conjunction with other SDKs.

### LINKED ISSUE #25521: [Bug]: [restful]Drop collection with a invalid collection name, the code is 200, but the message is `can't find collection: invalid_name`
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.0-20230710-4dd02836
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

```
2023-07-12 14:25:37.761 | DEBUG    | api.milvus:logger_request_response:14 - method: post, url: http://10.100.36.162:19530/v1/vector/collections/drop, cost time: 0.06141304969787598, header: {'Content-Type': 'application/json', 'Authorization': 'Bearer root:Milvus', 'RequestId': 'ea7a9320-207c-11ee-92df-acde48001122'}, payload: {"collectionName": "invalid_name", "dbName": "default"}, response: {"code":200,"message":"can't find collection: invalid_name"}
```

### Expected Behavior

When the code is 200, this should mean the params should be correct and the request is a success.

However, in this case, the code and message conflict.

In describe collection API,  the behavior is
```
2023-07-12 14:29:07.513 | ERROR    | api.milvus:logger_request_response:17 - method: get, url: http://10.100.36.162:19530/v1/vector/collections/describe, cost time: 0.03580021858215332, header: {'Content-Type': 'application/json', 'Authorization': 'Bearer root:Milvus', 'RequestId': '67842a02-207d-11ee-954b-acde48001122'}, payload: null, response: {"code":1,"message":"code: CollectionNotExists, reason: can't find collection: invalid_name"}
```

This is more reasonable

### Steps To Reproduce

_No response_

### Milvus Log

_No response_

### Anything else?

_No response_

### LINKED ISSUE #25547: [Bug]: [restful] Limit and offset does not take effect for query
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.2.0-20230712-96ba92d0
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

total number of entities is 5.

When I set the limit to 1, the return results should only have one entity
```
POST /v1/vector/query HTTP/1.1
Content-Type: application/json
Authorization: Bearer root:Milvus
User-Agent: PostmanRuntime/7.32.3
Accept: */*
Postman-Token: 9706aee2-ff29-4280-bfe5-f14326c38772
Host: 10.100.36.164:19530
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
Content-Length: 158
 
{
"collectionName": "book",
"filter": "id > 0",
"limit": 1,
"offset": 0,
"outputFields": [
"book_id",
"word_count"
]
}
 
HTTP/1.1 200 OK
Content-Type: application/json; charset=utf-8
Date: Wed, 12 Jul 2023 11:32:32 GMT
Content-Length: 151
 
{"code":200,"data":[{"id":442801292047025295},{"id":442801292047025297},{"id":442801292047025299},{"id":442801292047025301},{"id":442801292047025305}]}
```

when I set offset to 1, the return results should only have 4 entities

```
POST /v1/vector/query HTTP/1.1
Content-Type: application/json
Authorization: Bearer root:Milvus
User-Agent: PostmanRuntime/7.32.3
Accept: */*
Postman-Token: 1d8a9885-5a5d-48be-ae3d-dc8f5c3df1e3
Host: 10.100.36.164:19530
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
Content-Length: 142
 
{
"collectionName": "book",
"filter": "id > 0",
"offset": 1,
"outputFields": [
"book_id",
"word_count"
]
}
 
HTTP/1.1 200 OK
Content-Type: application/json; charset=utf-8
Date: Wed, 12 Jul 2023 11:37:37 GMT
Content-Length: 151
 
{"code":200,"data":[{"id":442801292047025295},{"id":442801292047025297},{"id":442801292047025299},{"id":442801292047025301},{"id":442801292047025305}]}
```

### Expected Behavior

_No response_

### Steps To Reproduce

_No response_

### Milvus Log

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by PowderLi**
/kind bug
fix #25482
fix #25497
fix #25502
fix #25521
fix #25509
fix #25547
bring by #24761

### CODE REVIEW

**Comment by PowderLi** [comment]
rerun ut

**Comment by PowderLi** [comment]
rerun ut

**Comment by PowderLi** [comment]
rerun ut

**Comment by czs007** [comment]
@PowderLi  remember to pick to master branch.

**Pull request merged**
