### PR TITLE
fix: lack good results for insufficient ef(#29883)

### PR DESCRIPTION
**Pull request by MrPresent-Han**
related: #29883

### CODE REVIEW

**Comment by xiaofan-luan** [comment]
/approve

@MrPresent-Han How do we verify the result to be good?

**Comment by MrPresent-Han** [comment]
> /approve
> 
> @MrPresent-Han How do we verify the result to be good?

intersect the result_sets and calculate hit_rate
this is fix removed by myself previously by accident
my fault

**Pull request merged**
