### PR TITLE
Enable sort for segcore RetrieveResults

### PR DESCRIPTION
**Pull request by XuanYang-cn**
See also: #18893

Signed-off-by: yangxuan <xuan.yang@zilliz.com>

### CODE REVIEW

**Comment by XuanYang-cn** [comment]
rerun ut

**Comment by XuanYang-cn** [comment]
rerun ut

**Comment by XuanYang-cn** [comment]
rerun ut

**Comment by jiaoew1991** [comment]
add a sort step in query path maybe affect query latency. otherwise LGTM

**Pull request merged**
