### PR TITLE
Fix build version typo

### LINKED ISSUE #7640: Compile version is still 0.10.0
When compile milvus 2.0 by "make all", the build output information is still 0.10.0

Building Milvus cpp library ...
~/git-go/milvus/cmake_build ~/git-go/milvus
cmake -DBUILD_UNIT_TEST=OFF -DCMAKE_INSTALL_PREFIX=/home/yhmo/git-go/milvus/scripts/../internal/core/output -DCMAKE_BUILD_TYPE=Release -DOpenBLAS_SOURCE=AUTO -DCMAKE_CUDA_COMPILER=/usr/local/cuda/bin/nvcc -DBUILD_COVERAGE=OFF -DMILVUS_DB_PATH=/tmp/milvus -DENABLE_CPU_PROFILING=OFF -DMILVUS_GPU_VERSION=OFF -DMILVUS_WITH_PROMETHEUS=ON -DMILVUS_CUDA_ARCH=DEFAULT -DCUSTOM_THIRDPARTY_DOWNLOAD_PATH= /home/yhmo/git-go/milvus/scripts/../internal/core
-- Building using CMake version: 3.20.3
-- Build time = 2021-09-09 16:31.59
-- Build type = Release
-- Build version = 0.10.0

#### Expected result:
Should be 2.0

#### Environment:
- Milvus version(e.g. v2.0.0-RC2 or 8b23a93):
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:

### PR DESCRIPTION
**Pull request by yhmo**
Signed-off-by: yhmo <yihua.mo@zilliz.com>

Resolves: #7640

### CODE REVIEW

**Comment by yanliang567** [comment]
@yhmo i think it requires a rebase master for a ut issue fixed

**Review by xiaofan-luan — APPROVED** [review]

**Comment by czs007** [comment]
rebase master and retry @yhmo

**Pull request merged**
