### PR TITLE
enhance: refactor createCollection in RESTful API

### PR DESCRIPTION
**Pull request by smellthemoon**
1.  support isClusteringKey in restful api;
2. throw err if passed invalid 'enableDynamicField' params
3. parameters in indexparams are not processed properly, related with #36365

### CODE REVIEW

**Comment by smellthemoon** [comment]
rerun ut

**Review by congqixia — APPROVED** [review]
/lgtm

**Comment by smellthemoon** [comment]
@zhuwenxing could you help to adjust or add some test about it?

**Comment by zhuwenxing** [comment]
> @zhuwenxing could you help to adjust or add some test about it?

👌

**Pull request merged**
