### PR TITLE
Fix bug of missing JSON type when sorting retrieve results

### PR DESCRIPTION
**Pull request by xiaocai2333**
issue: #25385

### CODE REVIEW

**Review by yah01 — APPROVED** [review]
/lgtm

**Comment by xiaofan-luan** [comment]
i don't really understand the fix

**Comment by xiaocai2333** [comment]
> i don't really understand the fix

The JSON column was not being swapped during sorting of the PK column.

**Comment by xiaocai2333** [comment]
rerun ut

**Comment by xiaocai2333** [comment]
rerun ut

**Pull request merged**
