### PR TITLE
enhance: add switch for local rpc enabled

### PR DESCRIPTION
**Pull request by chyezh**
issue: #33285

- Add switch for local rpc

### CODE REVIEW

**Comment by chyezh** [comment]
rerun go-sdk

**Comment by chyezh** [comment]
rerun go-sdk

**Comment by jaime0815** [comment]
rerun go-sdk

**Comment by jaime0815** [comment]
rerun cpp-unit-test

**Comment by chyezh** [comment]
rerun go-sdk

**Comment by chyezh** [comment]
rerun go-sdk

**Pull request merged**
