### PR TITLE
enhance: refine rootcoord/metatable interfaces to ensure that each method includes a ctx parameter

### PR DESCRIPTION
**Pull request by tinswzy**
issue: #35917
Before enhancing log trace information, it's necessary to pass the context to the method entry point.
This PR first refine the rootcoord/metatable interfaces to ensure that each method includes a ctx parameter.

### CODE REVIEW

**Comment by jaime0815** [comment]
rerun go-sdk

**Comment by tinswzy** [comment]
rerun cpp-unit-test

**Comment by chyezh** [comment]
rerun ut

**Comment by tinswzy** [comment]
rerun cpp-unit-test

**Pull request merged**
