### PR TITLE
fix: Load raw data with mmap when scalar index doesn't have raw data for indexing finish

### PR DESCRIPTION
**Pull request by xiaocai2333**
isuue: #28886

### CODE REVIEW

**Review by yah01 — COMMENTED** [review]
we could simply not drop the field data while loading a index without raw data, see https://github.com/milvus-io/milvus/pull/29912

**Comment by yah01** [comment]
this would do unnecessary works:
- load index would drop the loaded field data
- reload the field data back

**Comment by xiaocai2333** [comment]
> we could simply not drop the field data while loading a index without raw data, see #29912

got it.

/close

**Pull request closed without merging**
