### PR TITLE
add array hashKeys empty check

### LINKED ISSUE #15791: [Bug]: The array hashKeys without empty check
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.0GA
- Deployment mode(standalone):
- SDK version(golang sdk ):
- OS(CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

run the golang-sdk example , examples/index/inedx.go

image

### Expected Behavior

success run the example code

### Steps To Reproduce

```markdown
1.docker-compose up -d  to start milvus 

2. my milvus is restart ,so the milvus is load the data ,but i can not Sure when is ready,so i run the golang-sdk

3.so i trigger this bug
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by zhuyaguang**
fix #15791
Signed-off-by: zhuyaguang <zhuyaguang1368@163.com>

### CODE REVIEW

**Comment by xiaofan-luan** [comment]
fmt check failed, run "make fmt" or " gofmt -s -w internal/proxy/task.go " before you commit

**Comment by xiaofan-luan** [comment]
Actually I would also suggest to think about why ComputeProduceChannelIndexes could return nil.
That seems to be a weird a behaviour and there are many other cases the return value is not handled correctly

**Comment by zhuyaguang** [comment]
> Actually I would also suggest to think about why ComputeProduceChannelIndexes could return nil. That seems to be a weird a behaviour and there are many other cases the return value is not handled correctly

in my opinion，i trigger this bug  when the milvus is restart  loading the collection,  so ComputeProduceChannelIndexes without data.

**Comment by xiaofan-luan** [comment]
> > Actually I would also suggest to think about why ComputeProduceChannelIndexes could return nil. That seems to be a weird a behaviour and there are many other cases the return value is not handled correctly
> 
> in my opinion，i trigger this bug when the milvus is restart loading the collection, so ComputeProduceChannelIndexes without data.

I've seen ComputeProduceChannelIndexes is used at a couple of other places,  if we can also add length check at other places that would make more sense to me

**Comment by xiaofan-luan** [comment]
Thanks for the contribution and welcome to the community~~

**Pull request merged**
