### PR TITLE
Hide ID cache timeout settings from users.

### PR DESCRIPTION
**Pull request by soothing-rain**
Also change default expire time from 60 min to 5 min.

/kind improvement

issue: 15593

Signed-off-by: Yuchen Gao <yuchen.gao@zilliz.com>

### CODE REVIEW

**Comment by soothing-rain** [comment]
rerun ut

**Comment by soothing-rain** [comment]
rerun ut

**Comment by xiaofan-luan** [comment]
should we remove ID cache when operation succeed?

**Comment by soothing-rain** [comment]
> should we remove ID cache when operation succeed?

It seems cache is used as the first guard when processing search result to avoid duplicate request IDs.

On a cache hit, the search result processing step will fast fail.

**Comment by soothing-rain** [comment]
Closing it. No longer needed for: https://github.com/milvus-io/milvus/pull/16655

**Pull request closed without merging**
