### PR TITLE
fix: missing to support compact for Array type

### LINKED ISSUE #29503: [Bug]: Compaction can be never done with Array type
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.3
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

the compactor missing to handle array type, the system could go normally with the original flushed segments, but these segments can be never compacted

### Expected Behavior

_No response_

### Steps To Reproduce

_No response_

### Milvus Log

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by yah01**
the array type can't be compacted, the system could continue with the inserted segments, but these segments can be never compacted

fix #29503

### CODE REVIEW

**Comment by xiaofan-luan** [comment]
need a test on compacting all datatypes

**Comment by yah01** [comment]
rerun ut

**Review by congqixia — COMMENTED** [review]
/lgtm

**Pull request merged**
