### PR TITLE
feat: [cherry-pick][2.4] support partition key isolation (#34336)

### PR DESCRIPTION
**Pull request by PwzXxm**
issue: #34332
pr: #34336

---------

Signed-off-by: Patrick Weizhi Xu <weizhi.xu@zilliz.com>
(cherry picked from commit 104d0966b7df80a251437bed74f28fa47e138397)

### CODE REVIEW

**Comment by PwzXxm** [comment]
/hold
wait for 2.4.6 release

**Review by congqixia — APPROVED** [review]
/lgtm

**Pull request merged**
