### PR TITLE
fix: add move cursor function to physical expr

### PR DESCRIPTION
**Pull request by zhagnlu**
#29570

### CODE REVIEW

**Comment by czs007** [comment]
need to rebase to solve code check  problem @zhagnlu

**Review by longjiquan — APPROVED** [review]
/lgtm

**Comment by zhagnlu** [comment]
rerun ut

**Comment by zhagnlu** [comment]
rerun ut

**Comment by samhuang-z** [comment]
rerun ut

**Comment by zhagnlu** [comment]
rerun ut

**Pull request merged**
