### PR TITLE
natsmq

### PR DESCRIPTION
**Pull request by yiwangdr**
@jaime0815 This PR contains my code for Nats MQ. I will keep updating it until I explicitly sign off. Let's sync on the progress and  planning when I sign off.

My idea is that we can keep all the initial nats mq implementation discussions and comments in one place for future reference.

issue: #23611

### CODE REVIEW

**Comment by xiaofan-luan** [comment]
Hi @yiwangdr 
You will need a issue describe what you try to contribute, and related the pr with issue.
Also you will have to sign the DCO, check the CONTRIBUTING Guide here
https://github.com/milvus-io/milvus/blob/master/CONTRIBUTING.md

**Comment by yiwangdr** [comment]
> Hi @yiwangdr You will need a issue describe what you try to contribute, and related the pr with issue. Also you will have to sign the DCO, check the CONTRIBUTING Guide here https://github.com/milvus-io/milvus/blob/master/CONTRIBUTING.md

Thanks, I'm aware of that.
Please correct me if I'm wrong. I noticed that there is a "[one commit only](https://github.com/milvus-io/milvus/pull/23606#issuecomment-1518415965)" policy. I'm not sure why we have that...

So this is a draft PR where I can keep commit history. @jaime0815  and other team members can commit to it as well.

We will have a separate PR with one commit for review & merge.

**Comment by jiaoew1991** [comment]
> > Hi @yiwangdr You will need a issue describe what you try to contribute, and related the pr with issue. Also you will have to sign the DCO, check the CONTRIBUTING Guide here https://github.com/milvus-io/milvus/blob/master/CONTRIBUTING.md
> 
> Thanks, I'm aware of that. Please correct me if I'm wrong. I noticed that there is a "[one commit only](https://github.com/milvus-io/milvus/pull/23606#issuecomment-1518415965)" policy. I'm not familiar with how that works if we have multiple contributors yet.
> 
> So this is a draft PR where I can keep commit history. @jaime0815 and other team members can commit to it as well.
> 
> We will have a separate PR with one commit for review & merge.

During the development phase, there can be multiple commits, and before merging, someone needs to rebase the commits into one.

**Comment by jiaoew1991** [comment]
It's best to break down a large pull request into several small ones and merge them one by one  😄

**Comment by yiwangdr** [comment]
> It's best to break down a large pull request into several small ones and merge them �one by one 😄

I agree. That's the preferred pattern. 
I noticed there are very big PRs in the codebase history thus thought big PRs are the pattern here. Thanks for pointing it out.

This PR is also experimental-ish.  Will break it for review&merge if needed.

**Comment by yiwangdr** [comment]
rerun ut

**Pull request closed without merging**
