### PR TITLE
feat: add more operation detail info for better allocation

### PR DESCRIPTION
**Pull request by SimFG**
issue: #30436

### CODE REVIEW

**Comment by xiaofan-luan** [comment]
/assign @yanliang567 

could we verify on this?
1. list databases don't require global permission
2. it returns all the db's this user has permission with

**Comment by xiaofan-luan** [comment]
I actaully give comment on the wrong issue, still work on reviewing of this PR

**Comment by SimFG** [comment]
@xiaofan-luan get it. if there are some comments, please give me some issue and i will fix them

**Pull request merged**
