### PR TITLE
fix: Skip to load l0 segment on old version query node

### PR DESCRIPTION
**Pull request by weiliu1031**
issue: #32107
pr: #32124

during rolling upgrade progress, skip to load l0 segment on old version query node

### CODE REVIEW

**Comment by weiliu1031** [comment]
rerun ut

**Comment by weiliu1031** [comment]
rerun ut

**Comment by weiliu1031** [comment]
rerun ut

**Comment by weiliu1031** [comment]
rerun ut

**Review by congqixia — COMMENTED** [review]
/approve

**Pull request merged**
