### PR TITLE
Update pymilvus version

### LINKED ISSUE #17614: [Bug]: Update pymilvus version
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

NA

### Expected Behavior

NA

### Steps To Reproduce

```markdown
NA
```

### Milvus Log

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by NicoYuan1986**
Resolve: #17614
Signed-off-by: “nico” <cheng.yuan@zilliz.com>

### CODE REVIEW

**Comment by binbinlv** [comment]
@NicoYuan1986 

Please see why this CI is failed.

**Comment by NicoYuan1986** [comment]
> @NicoYuan1986
> 
> Please see why this CI is failed, and modify your pr.

OK, the error code of create index need to be updated.

**Pull request merged**
