### PR TITLE
[2.2.0]Fix graceful stop may not wait for the query goroutines done

### PR DESCRIPTION
**Pull request by smellthemoon**
Signed-off-by: lixinguo [xinguo.li@zilliz.com](mailto:xinguo.li@zilliz.com)
/kind improvement

### CODE REVIEW

**Comment by yah01** [comment]
Does search has the same problem?

**Comment by smellthemoon** [comment]
> Does search has the same problem?

Yes, have already modified it.

**Comment by smellthemoon** [comment]
rerun ut

**Review by congqixia — COMMENTED** [review]
WaitGroup adds in `searchWithDmlChannel` and `queryWithDmlChannel` methods

**Pull request closed without merging**
