### PR TITLE
Fix keep milvus and knowhere openBLAS version same

### PR DESCRIPTION
**Pull request by soulteary**
Signed-off-by: soulteary [soulteary@gmail.com](mailto:soulteary@gmail.com)

issue: https://github.com/milvus-io/milvus/issues/18192

### CODE REVIEW

**Comment by xiaofan-luan** [comment]
@soulteary ut is not passed, could you pls check on it

**Comment by xiaofan-luan** [comment]
@soulteary ut is not passed, could you pls check on it

seems that it it due to address already used.

7/09 03:36:20.105 +00:00] [ERROR] [service.go:128] ["grpc server failed to listen error"] [error="listen tcp :13333: bind: address already in use"] [stack="github.com/milvus-io/milvus/internal/distributed/datacoord.(*Server).startGrpcLoop\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/datacoord/service.go:128"]

**Comment by soulteary** [comment]
Thanks for the reminder, I'll try to see how to fix this test issue. @xiaofan-luan

**Comment by soulteary** [comment]
After communicating with the knowhere maintainers, at the current point in time, we should use the openblas in the milvus docker builder as the benchmark, so, I submitted a PR to knowhere, and this PR does not need to be revised and merged anymore.

Thanks to @xiaofan-luan  and @jennyli-z  for their help.


ref issue: https://github.com/milvus-io/knowhere/pull/292

**Pull request closed without merging**
