### PR TITLE
enhance: Skip generate load segment task

### PR DESCRIPTION
**Pull request by weiliu1031**
issue: #29814
if channel is not subscribed yet, the generated load segment task will be remove from task scheduler due to the load segment task need to be transfer to worker node by shard leader.

This PR skip generate load segment task when channel is not subscribed yet.

### CODE REVIEW

**Comment by samhuang-z** [comment]
rerun ut

**Comment by weiliu1031** [comment]
rerun ut

**Comment by weiliu1031** [comment]
rerun ut

**Review by yah01 — COMMENTED** [review]
/lgtm

**Pull request merged**
