### PR TITLE
 enhance: skip segment when using pk in (..) expr

### PR DESCRIPTION
**Pull request by zhagnlu**
#29293

### CODE REVIEW

**Comment by xiaofan-luan** [comment]
@zhagnlu 
seems that you link the wrong issue

**Comment by zhagnlu** [comment]
> @zhagnlu seems that you link the wrong issue

Found the bug when do performance optimization, so Is also contains the fix, should spilt it to two pr ?

**Comment by xiaofan-luan** [comment]
can we explain the bug a little bit?

**Comment by zhagnlu** [comment]
> can we explain the bug a little bit?



> can we explain the bug a little bit?

#29391 #29399  the bug reason is:
image
get batch result cursor is wrong, for different batch, cursor not increase

**Pull request merged**
