### PR TITLE
Add NodeIds field for QuerySegmentInfo

### PR DESCRIPTION
**Pull request by yah01**
We need to add NodeIds field for QuerySegmentInfo, since the Memory-Replica feature
/kind improvement

Signed-off-by: yah01 <yang.cen@zilliz.com>

### CODE REVIEW

**Comment by XuanYang-cn** [comment]
lgtm by me

**Comment by congqixia** [comment]
lgtm as temp solution. we need to combine segment information interfaces.
/cc @xiaofan-luan

**Pull request merged**
