### PR TITLE
Update cgroups version from v1.0.2 to v1.0.4

### PR DESCRIPTION
**Pull request by KubrickLiu**
Signed-off-by: KubrickLiu <m18800105727@163.com>
Fix: Centos Docker Milvus unable to start, issue link: https://github.com/milvus-io/milvus/issues/21386

### CODE REVIEW

**Review by congqixia — APPROVED** [review]
/kind bug
/lgtm

**Comment by xiaofan-luan** [comment]
@KubrickLiu Welcome to the community Kubrick!

**Pull request merged**
