### PR TITLE
Remove needless kv at dataSyncService

### PR DESCRIPTION
**Pull request by aoiasd**
related:https://github.com/milvus-io/milvus/issues/21074
Signed-off-by: aoiasd [zhicheng.yue@zilliz.com](mailto:zhicheng.yue@zilliz.com)

### CODE REVIEW

**Comment by aoiasd** [comment]
rerun ut

**Review by jiaoew1991 — APPROVED** [review]
/lgtm

**Review by congqixia — APPROVED** [review]
/lgtm

**Pull request merged**
