### PR TITLE
optimize the check of global cache

### LINKED ISSUE #16781: [Bug]: [benchmark][standalone] Milvus restart and raise error: Milvus Proxy is not ready yet. please wait
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20220429-1a29337e
- Deployment mode(standalone or cluster): standalone
- SDK version(e.g. pymilvus v2.0.0rc2): 2.1.0.dev39
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

argo task: benchmark-backup-fndkx

test yaml:
client-configmap:client-random-locust-100m-ddl-r8-w2
server-configmap:server-single-32c128m

client pod: benchmark-backup-fndkx-1459905251

client log file: locust_report_2022-04-29_703.log

client logs:
```
[2022-04-29 16:26:39,049] [   ERROR] - RPC error: [query], <MilvusException: (code=1, message=<_MultiThreadedRendezvous of RPC that terminated with:
	debug_error_string = "{"created":"@1651249599.040845892","description":"Error received from peer ipv4:10.96.168.171:19530","file":"src/core/lib/surface/call.cc","file_line":1068,"grpc_message":"internal: Milvus Proxy is not ready yet. please wait","grpc_status":2}"
>)>, <Time:{'RPC start': '2022-04-29 16:26:39.025218', 'RPC error': '2022-04-29 16:26:39.049203'}> (pymilvus.decorators:73)
[2022-04-29 16:26:39,049] [   ERROR] - grpc RpcError: [has_collection], <_MultiThreadedRendezvous: StatusCode.UNKNOWN, internal: Milvus Proxy is not ready yet. please wait>, <Time:{'RPC start': '2022-04-29 16:26:39.025289', 'gRPC error': '2022-04-29 16:26:39.049730'}> (pymilvus.decorators:81)
[2022-04-29 16:26:39,050] [   ERROR] - RPC error: [search], <MilvusException: (code=1, message=<_MultiThreadedRendezvous of RPC that terminated with:
	debug_error_string = "{"created":"@1651249599.040856720","description":"Error received from peer ipv4:10.96.168.171:19530","file":"src/core/lib/surface/call.cc","file_line":1068,"grpc_message":"internal: Milvus Proxy is not ready yet. please wait","grpc_status":2}"
>)>, <Time:{'RPC start': '2022-04-29 16:26:39.025285', 'RPC error': '2022-04-29 16:26:39.050183'}> (pymilvus.decorators:73)
[2022-04-29 16:26:39,050] [   ERROR] - grpc RpcError: [has_collection], <_MultiThreadedRendezvous: StatusCode.UNKNOWN, internal: Milvus Proxy is not ready yet. please wait>, <Time:{'RPC start': '2022-04-29 16:26:39.025350', 'gRPC error': '2022-04-29 16:26:39.050806'}> (pymilvus.decorators:81)
[2022-04-29 16:26:39,051] [   ERROR] - RPC error: [search], <MilvusException: (code=1, message=<_MultiThreadedRendezvous of RPC that terminated with:
	debug_error_string = "{"created":"@1651249599.040868022","description":"Error received from peer ipv4:10.96.168.171:19530","file":"src/core/lib/surface/call.cc","file_line":1068,"grpc_message":"internal: Milvus Proxy is not ready yet. please wait","grpc_status":2}"
>)>, <Time:{'RPC start': '2022-04-29 16:26:39.025344', 'RPC error': '2022-04-29 16:26:39.051365'}> (pymilvus.decorators:73)
[2022-04-29 16:26:39,052] [   ERROR] - grpc RpcError: [has_collection], <_MultiThreadedRendezvous: StatusCode.UNKNOWN, internal: Milvus Proxy is not ready yet. please wait>, <Time:{'RPC start': '2022-04-29 16:26:39.025414', 'gRPC error': '2022-04-29 16:26:39.051974'}> (pymilvus.decorators:81)
[2022-04-29 16:26:39,052] [   ERROR] - RPC error: [search], <MilvusException: (code=1, message=<_MultiThreadedRendezvous of RPC that terminated with:
	debug_error_string = "{"created":"@1651249599.040878540","description":"Error received from peer ipv4:10.96.168.171:19530","file":"src/core/lib/surface/call.cc","file_line":1068,"grpc_message":"internal: Milvus Proxy is not ready yet. please wait","grpc_status":2}"
>)>, <Time:{'RPC start': '2022-04-29 16:26:39.025407', 'RPC error': '2022-04-29 16:26:39.052579'}> (pymilvus.decorators:73)
[2022-04-29 16:26:39,053] [   ERROR] - grpc RpcError: [describe_collection], <_MultiThreadedRendezvous: StatusCode.UNKNOWN, internal: Milvus Proxy is not ready yet. please wait>, <Time:{'RPC start': '2022-04-29 16:26:39.025490', 'gRPC error': '2022-04-29 16:26:39.053046'}> (pymilvus.decorators:81)
[2022-04-29 16:26:39,053] [   ERROR] - RPC error: [query], <MilvusException: (code=1, message=<_MultiThreadedRendezvous of RPC that terminated with:
	debug_error_string = "{"created":"@1651249599.040931024","description":"Error received from peer ipv4:10.96.168.171:19530","file":"src/core/lib/surface/call.cc","file_line":1068,"grpc_message":"internal: Milvus Proxy is not ready yet. please wait","grpc_status":2}"
>)>, <Time:{'RPC start': '2022-04-29 16:26:39.025485', 'RPC error': '2022-04-29 16:26:39.053404'}> (pymilvus.decorators:73)
[2022-04-29 16:26:39,053] [   ERROR] - grpc RpcError: [load_collection], <_MultiThreadedRendezvous: StatusCode.UNKNOWN, internal: Milvus Proxy is not ready yet. please wait>, <Time:{'RPC start': '2022-04-29 16:26:39.027866', 'gRPC error': '2022-04-29 16:26:39.053804'}> (pymilvus.decorators:81)
[2022-04-29 16:26:39,057] [   ERROR] - grpc RpcError: [has_collection], <_MultiThreadedRendezvous: StatusCode.UNKNOWN, internal: Milvus Proxy is not ready yet. please wait>, <Time:{'RPC start': '2022-04-29 16:26:39.036506', 'gRPC error': '2022-04-29 16:26:39.057214'}> (pymilvus.decorators:81)
[2022-04-29 16:26:39,057] [   ERROR] - RPC error: [search], <MilvusException: (code=1, message=<_MultiThreadedRendezvous of RPC that terminated with:
	debug_error_string = "{"created":"@1651249599.054495374","description":"Error received from peer ipv4:10.96.168.171:19530","file":"src/core/lib/surface/call.cc","file_line":1068,"grpc_message":"internal: Milvus Proxy is not ready yet. please wait","grpc_status":2}"
>)>, <Time:{'RPC start': '2022-04-29 16:26:39.036488', 'RPC error': '2022-04-29 16:26:39.057865'}> (pymilvus.decorators:73)
```

server:
```
NAME                                                          READY   STATUS      RESTARTS   AGE     IP             NODE                      NOMINATED NODE   READINESS GATES
benchmark-backup-fndkx-1-etcd-0                               1/1     Running     0          3d13h   10.97.17.203   qa-node014.zilliz.local   <none>           <none>
benchmark-backup-fndkx-1-milvus-standalone-789764bdc8-lwfhj   1/1     Running     1          3d13h   10.97.20.191   qa-node018.zilliz.local   <none>           <none>
benchmark-backup-fndkx-1-minio-7fcd668cbb-4kwj5               1/1     Running     0          3d13h   10.97.16.130   qa-node013.zilliz.local   <none>           <none>
```

### Expected Behavior

_No response_

### Steps To Reproduce

```markdown
1、create collection
2、create index of ivf_sq8
3、insert 100m million vectors
4、flush collection
5、build index with the same params
6、load collection
7、locust concurrent: query<-search, load, get<-query, scene_test 《- raise error
```

### Milvus Log

_No response_

### Anything else?

client-random-locust-100m-ddl-r8-w2:
```
locust_random_performance:
      collections:
        -
          collection_name: sift_100m_128_l2
          ni_per: 50000
          build_index: true
          index_type: ivf_sq8
          index_param:
            nlist: 2048
          task:
            types:
              -
                type: query
                weight: 8
                params:
                  top_k: 10
                  nq: 10
                  search_param:
                    nprobe: 16
              -
                type: load
                weight: 1
              -
                type: get
                weight: 8
                params:
                  ids_length: 10
              -
                type: scene_test
                weight: 2
            connection_num: 1
            clients_num: 20
            spawn_rate: 2
            during_time: 302400
```

```
    @time_wrapper
    def scene_test(self, collection_name=None, vectors=None, ids=None):
        logger.debug("[scene_test] Start scene test : %s" % collection_name)
        self.create_collection(dimension=128, collection_name=collection_name)
        time.sleep(1)

        collection_info = self.get_info(collection_name)

        entities = utils.generate_entities(collection_info, vectors, ids)
        logger.debug("[scene_test] Start insert : %s" % collection_name)
        self.insert(entities, collection_name=collection_name)
        logger.debug("[scene_test] Start flush : %s" % collection_name)
        self.flush(collection_name=collection_name)

        self.count(collection_name=collection_name)

        logger.debug("[scene_test] Start create index : %s" % collection_name)
        self.create_index(field_name='float_vector', index_type="ivf_sq8", metric_type='l2',
                          collection_name=collection_name, index_param={'nlist': 2048})
        time.sleep(59)

        logger.debug("[scene_test] Start drop : %s" % collection_name)
        self.drop(collection_name=collection_name)
        logger.debug("[scene_test]Scene test close : %s" % collection_name)
```

### PR DESCRIPTION
**Pull request by jiangke-sr**
Signed-off-by: kejiang <ke.jiang@zilliz.com>

Related to #16781

### CODE REVIEW

**Comment by aakejiang** [comment]
rerun ut

**Comment by aakejiang** [comment]
rerun ut

**Comment by jennyli-z** [comment]
lgtm

**Comment by aakejiang** [comment]
rerun ut

**Pull request closed without merging**
