### PR TITLE
Add failed streaming unittest for query node

### LINKED ISSUE #7806: Unittests code coverage to 85%+ in query node
#### Expected result:
Unittests code coverage to 85%+ in query node

#### Environment:
- Milvus version(e.g. v2.0.0-RC2 or 8b23a93):
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:

### PR DESCRIPTION
**Pull request by bigsheeper**
Signed-off-by: bigsheeper <yihao.dai@zilliz.com>

Resolves: #7806

### CODE REVIEW

**Comment by scsven** [comment]
@bigsheeper Do you mean streaming? Maybe a typo in the commit message.

**Comment by bigsheeper** [comment]
> @bigsheeper Do you mean streaming? Maybe a typo in the commit message.

sorry，my fault

**Pull request merged**
