### PR TITLE
Fix 6419, check if num_rows is greater than zero in proxy

### LINKED ISSUE #6482: Check if num_rows is greater than zero in proxy
**What would you like to be added ?**
When receiving insert requests, proxy should check num_rows of all input field data.

**Why is this needed ?**
Improve the stability of proxy.

### PR DESCRIPTION
**Pull request by longjiquan**
Signed-off-by: dragondriver <jiquan.long@zilliz.com>

Related Issue: #6419

### CODE REVIEW

**Comment by DragonDriver** [comment]
test code:

```python
#!/usr/bin/env python

from pymilvus import Milvus, DataType
from pymilvus.grpc_gen import milvus_pb2 as milvus_types

ip = "127.0.0.1"
port = "19530"
dim = 128

c = "c_6419"

fields = {
    "fields": [
        {"name": "int64", "type": DataType.INT64, "is_primary": True, "auto_id": True},
        {"name": "fvec", "type": DataType.FLOAT_VECTOR,
         "params": {"dim": dim},
         "indexes": [{"index_type": "IVF_PQ", "metric_type": "L2"}]},
    ]
}

if __name__ == "__main__":
    client = Milvus(host=ip, port=port)

    if client.has_collection(c):
        client.drop_collection(c)

    client.create_collection(c, fields)

    with client._connection() as handler:
        req = milvus_types.InsertRequest(collection_name=c)
        resp = handler._stub.Insert(req, wait_for_ready=True, timeout=None)
        print(resp)
        req = milvus_types.InsertRequest(collection_name=c, num_rows=10)
        resp = handler._stub.Insert(req, wait_for_ready=True, timeout=None)
        print(resp)

    client.close()
```

output:

```
status {
  error_code: UnexpectedError
  reason: "num_rows(0) should be greater than 0"
}

status {
  error_code: UnexpectedError
  reason: "empty field data"
}
```

**Comment by czs007** [comment]
Please add  unit tests.

**Comment by DragonDriver** [comment]
> Please add unit tests.

PTAL @czs007

**Pull request merged**
