### PR TITLE
Refactor `RangeExpr` & `CompareExpr`

### LINKED ISSUE #6790: Refactor `RangeExpr` & `CompareExpr`
#### What would you like to be added:

Currently, `RangeExpr` & `CompareExpr` is described by the following protobuf syntax.
```protobuf
message RangeExpr {
  ColumnInfo column_info = 1;
  repeated OpType ops = 2;
  repeated GenericValue values = 3;
}

message CompareExpr {
  repeated ColumnInfo columns_info = 1;
  OpType op = 2;
}
```
It's better to change it to
```protobuf
message UnaryRangeExpr {
  ColumnInfo column_info = 1;
  OpType op = 2;
  GenericValue value = 3;
}

message BinaryRangeExpr {
  ColumnInfo column_info = 1;
  bool lower_inclusive = 2;
  bool upper_inclusive = 3;
  GenericValue lower_value = 4;
  GenericValue upper_value = 5;
}

message CompareExpr {
  ColumnInfo left_column_info = 1;
  ColumnInfo right_column_info = 2;
  OpType op = 3;
}
```

#### Why is this needed:

This makes the defination more clearly and reduces the number of validation steps.

### PR DESCRIPTION
**Pull request by xaxys**
- Refactor `RangeExpr` proto to `UnaryRangeExpr` & `BinaryRangeExpr`
- Refactor `CompareExpr`
- Unify variable name of AST node in `Expr.cpp`

Resolves: #6790 

Signed-off-by: xaxys <tpnnghd@163.com>

### CODE REVIEW

**Comment by xaxys** [comment]
sorry for messing up last PR :(

**Comment by xaxys** [comment]
/assign @xaxys
ready to merge

**Comment by czs007** [comment]
good job!
@xaxys  
please link an issue to illustrate your intention of this modification.

**Pull request merged**
