### PR TITLE
[skip ci]Update approvers

### PR DESCRIPTION
**Pull request by wxyucs**
Related issue: #7062
Signed-off-by: Xiangyu Wang <xiangyu.wang@zilliz.com>

### CODE REVIEW

**Comment by XuanYang-cn** [comment]
> Related issue: #7062
> Signed-off-by: Xiangyu Wang [xiangyu.wang@zilliz.com](mailto:xiangyu.wang@zilliz.com)

I don't have comments, but why sre-ci-robot is celebrating with hooray emoji :tada:

**Comment by scsven** [comment]
> > Related issue: #7062
> > Signed-off-by: Xiangyu Wang [xiangyu.wang@zilliz.com](mailto:xiangyu.wang@zilliz.com)
> 
> I don't have comments, but why sre-ci-robot is celebrating with hooray emoji 🎉

maybe I update the OWNERS files

**Comment by xiaofan-luan** [comment]
Approvers Let's work together to make our commits clean and tidy! @scsven please also update rules so everybody knows the standards.

**Pull request merged**
