### PR TITLE
enhance: Solve channel unbalance on datanode

### PR DESCRIPTION
**Pull request by weiliu1031**
issue: #33583
the old policy permit datanode has at most 2 more channels than other datanode. so if milvus has 2 datanode and 2 channels, both 2 channels will be assign to 1 datanode, left another datanode empty.

This PR refine the balance policy to solve channel unbalance on datanode

### CODE REVIEW

**Comment by weiliu1031** [comment]
rerun ut

**Review by XuanYang-cn — APPROVED** [review]
/lgtm

**Pull request merged**
