### PR TITLE
Organize mocks from types.go

### PR DESCRIPTION
**Pull request by yiwangdr**
remove mocks from internal/types and add them into internal/mocks

background:
Mocks from types.go are not well organized. 
This issue is blocking other projects.
Issue: #25465

### CODE REVIEW

**Comment by yiwangdr** [comment]
rerun ut

**Comment by yiwangdr** [comment]
@jiaoew1991 @congqixia @bigsheeper  if this PR looks good to you, could you help to merge it. It looks like I don't have the permission to merge it.

**Comment by jiaoew1991** [comment]
> @jiaoew1991 @congqixia @bigsheeper if this PR looks good to you, could you help to merge it. It looks like I don't have the permission to merge it.

It seems that cpu-e2e is not triggered automatically. 😓

**Comment by yiwangdr** [comment]
> @yiwangdr force push may do the trick

The failed e2e test looks not relevant to this PR. Can I check if this is an existing issue that is also happening to other PRs?

**Comment by yiwangdr** [comment]
@jiaoew1991 @congqixia @bigsheeper somehow cpu-e2e passed. I'm not sure why it rerun'ed.
Do I need to have gpu-e2e pass as well?

**Comment by congqixia** [comment]
@yiwangdr gpu-e2e is not stable so it's not mandatory to have `ci-passed` label with this workflow passed

**Pull request merged**
