### PR TITLE
Add dependency factory

### PR DESCRIPTION
**Pull request by godchen0212**
Add dependency factory
Issue #15308 

Signed-off-by: godchen0212 <qingxiang.chen@zilliz.com>

### CODE REVIEW

**Comment by godchen0212** [comment]
rerun ut

**Comment by godchen0212** [comment]
rerun ut

**Comment by soothing-rain** [comment]
rerun ut

**Comment by godchen0212** [comment]
rerun ut

**Comment by godchen0212** [comment]
rerun ut

**Comment by godchen0212** [comment]
rerun ut

**Comment by godchen0212** [comment]
rerun ut

**Comment by binbinlv** [comment]
When this pr will be merged? It blocks the test start of embedded milvus, thanks.

**Pull request merged**
