### PR TITLE
Use a pool for kafka consumer to reduce resource overhead

### PR DESCRIPTION
**Pull request by jaime0815**
issue #20627 
Signed-off-by: yun.zhang <yun.zhang@zilliz.com>

### CODE REVIEW

**Comment by jaime0815** [comment]
both search latency and MQ performance will be better than before.

before:
image

image

after
image
image

**Comment by xiaofan-luan** [comment]
think of reuse msgstream?

**Comment by jaime0815** [comment]
Use share pchannel strategy to replace the pooled consumer that only has one consumer to dispatch messages to the different collections.

**Pull request closed without merging**
