### PR TITLE
fix: erase pk empty check when pk index replace raw data

### PR DESCRIPTION
**Pull request by zhagnlu**
#30350

### CODE REVIEW

**Comment by zhagnlu** [comment]
rerun ut

**Comment by xiaofan-luan** [comment]
is this a problem for 2.3?

**Comment by zhagnlu** [comment]
rerun ut

**Comment by zhagnlu** [comment]
> is this a problem for 2.3?

yes, will cherry-pick to 2,.3

**Comment by zhagnlu** [comment]
rerun ut

**Comment by czs007** [comment]
@zhagnlu please pick to 2.3

**Pull request merged**
