### PR TITLE
support try-best reducer methods(#24075)

### PR DESCRIPTION
**Pull request by MrPresent-Han**
related: #24075

### CODE REVIEW

**Comment by MrPresent-Han** [comment]
rerun ut

**Comment by MrPresent-Han** [comment]
rerun ut

**Review by congqixia — COMMENTED** [review]
Quick question: why enlarge the limit in reduce period but not before query? Some record will cannot be hit if we only enlarge limit after query

**Comment by MrPresent-Han** [comment]
> Quick question: why enlarge the limit in reduce period but not before query? Some record will cannot be hit if we only enlarge limit after query

because there is no 'limit' in the process of retrieving, currently, all retrieve operation on segments will return all matched rows

**Review by congqixia — APPROVED** [review]
/lgtm

**Pull request merged**
