### PR TITLE
[test]Update the testcase with consistency

### PR DESCRIPTION
**Pull request by jingkl**
Signed-off-by: jingkl <jingjing.jia@zilliz.com>
issue:#16090

### CODE REVIEW

**Comment by binbinlv** [comment]
"CONSISTENCY_SESSION " in the case "test_search_with_consistency_bounded" is not right.

**Comment by jingkl** [comment]
> "CONSISTENCY_SESSION " in the case "test_search_with_consistency_bounded" is not right.

Already modified

**Pull request merged**
