### PR TITLE
fix flaws found in the process of ideal benchmark(#21504)

### PR DESCRIPTION
**Pull request by MrPresent-Han**
1. enable paramter autoBalance
2. adjust inappropriate log info when searching in shardcluster
issue: #21504 

Signed-off-by: MrPresent-Han <chun.han@zilliz.com>

### CODE REVIEW

**Comment by MrPresent-Han** [comment]
rerun ut

**Comment by MrPresent-Han** [comment]
rerun ut

**Review by congqixia — APPROVED** [review]
/lgtm

**Pull request merged**
