### PR TITLE
[skip ci]Remove RmqMsgStream docs

### PR DESCRIPTION
**Pull request by fishpenguin**
Signed-off-by: fishpenguin <kun.yu@zilliz.com>

/kind improvement

### CODE REVIEW

**Comment by xiaofan-luan** [comment]
why are we remove all old documents? do we have better documents right now?

**Comment by fishpenguin** [comment]
> why are we remove all old documents? do we have better documents right now?

These interfaces are expired, which separate msgstream into PulsarMsgStream and RmqMsgStream.  The two kinds of msgstreams have been united to msgstream.

**Comment by fishpenguin** [comment]
> why are we remove all old documents? do we have better documents right now?

New interface docs has been added in previous pr.

**Pull request merged**
