### PR TITLE
docker: move compose file from root path to docker folder

### PR DESCRIPTION
**Pull request by ericsyh**
**What type of PR is this?**

- [ ] API-change
- [ ] BUG
- [ ] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactorin
- [x] Repo organize

**Which issue(s) this PR fixes:**

Fixes # No open issue related.

**What this PR does / why we need it:**

When browsing the repo, i was confused compose-file is put under repo root path while where is a docker folder contains other related files. So i think it will be great to move the compose-file to the docker folder so that people will be more clear to get their target file under the corresponding path.

**Special notes for your reviewer:**

I also think it's quite mess that put some many docs file under root path like `DESIGN.md` , `INSTALL.md` , `RELEASE.md` , `SUPPORT.md`. Under the root path, it will be better that we only put the basic&necessary docs like README, CHANGELOG, CODE_OF_CONDUCT, CONTRIBUTING and move other docs especially manual docs to docs folder. 

**Additional documentation (e.g. design docs, usage docs, etc.):**

Not Available

### CODE REVIEW

**Comment by scsven** [comment]
@jeffoverflow Can we move the docker-compose.yaml to the docker directory?

**Comment by yhmo** [comment]
@ericsyh 
The "DCO" check doesn't pass, please sign your mail address in the commit.

**Comment by jeffoverflow** [comment]
@ericsyh Move the docker compose file will affect Github Action workflow.

**Comment by ericsyh** [comment]
> @ericsyh Move the docker compose file will affect Github Action workflow.

@jeffoverflow So all docker-compose  command in workflow should be updated as `docker-compose -f ./docker/docker-compose.yml run ubuntu-core` if we move the docker compose file?

Including (ubuntu as sample):
https://github.com/milvus-io/milvus/blob/master/.github/workflows/core.yml#L44
https://github.com/milvus-io/milvus/blob/master/.github/workflows/core.yml#L45
https://github.com/milvus-io/milvus/blob/master/.github/workflows/core.yml#L49
https://github.com/milvus-io/milvus/blob/master/.github/workflows/core.yml#L53
https://github.com/milvus-io/milvus/blob/master/.github/workflows/core.yml#L54
https://github.com/milvus-io/milvus/blob/master/.github/workflows/core.yml#L54

**Comment by jeffoverflow** [comment]
> https://github.com/milvus-io/milvus/blob/master/.github/workflows/core.yml#L44

@ericsyh Yea !

**Comment by ericsyh** [comment]
@jeffoverflow docker-compose pull requires the [.env](https://github.com/milvus-io/milvus/blob/master/.env), can i move it to docker path also?

**Comment by jeffoverflow** [comment]
> @jeffoverflow docker-compose pull requires the [.env](https://github.com/milvus-io/milvus/blob/master/.env), can i move it to docker path also?

@ericsyh You can try it.

**Comment by scsven** [comment]
@ericsyh Hi Eric, could you complete this PR as soon as possible? There is a large change on master incoming, I afraid your PR will meet an unsolvable conflict.

**Comment by ericsyh** [comment]
> @ericsyh Hi Eric, could you complete this PR as soon as possible? There is a large change on master incoming, I afraid your PR will meet an unsolvable conflict.

got it, i will fix related changes today.

**Comment by ericsyh** [comment]
@scsven @jeffoverflow I have finished the left changes on workflow and passed the CI, but no idea why this PR makes codecov decrease.

**Review by jeffoverflow — APPROVED** [review]

**Review by wxyucs — APPROVED** [review]

**Comment by scsven** [comment]
@ericsyh That is not required. Thanks for your contribution. :)

**Pull request merged**
