### PR TITLE
Fix wrong msg when load failed

### PR DESCRIPTION
**Pull request by xige-16**
issue: #19882 
/kind bug
Signed-off-by: xige-16 <xi.ge@zilliz.com>

### CODE REVIEW

**Review by congqixia — APPROVED** [review]
/lgtm

**Comment by jennyli-z** [comment]
image
https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20HA%20CI/detail/PR-19884/1/pipeline
One thing I am cuirous about is , it failed once ,and rerun can pass. Is there any potential issue in this pr or master code?

**Comment by xige-16** [comment]
> any potential issue in this p

**Comment by xige-16** [comment]
rerun ut

**Pull request merged**
