### PR TITLE
Fix typo in publish builder

### LINKED ISSUE #17343: [Bug]: Builder publish workflow not working
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
github workflow
```

### Current Behavior

see https://github.com/milvus-io/milvus/actions/runs/2425683636/workflow

### Expected Behavior

successfully run

### Steps To Reproduce

```markdown
merge a PR into master
```

### Milvus Log

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by haorenfsa**
Signed-off-by: shaoyue.chen <shaoyue.chen@zilliz.com>
/cc @yanliang567 @jennyli-z 

Fix #17343

### CODE REVIEW

**Review by jennyli-z — APPROVED** [review]

**Comment by haorenfsa** [comment]
Fix #17343

**Pull request merged**
