### PR TITLE
Add zstd compressor in util

### PR DESCRIPTION
**Pull request by yah01**
Signed-off-by: yah01 <yang.cen@zilliz.com>
We will compress data in message queue for the future with the util #15561

### CODE REVIEW

**Comment by xiaofan-luan** [comment]
do we have any test data on the compression ratio?

**Comment by congqixia** [comment]
@yah01 Since we are using parquet as storage format, it supports compress codec by default.  See the compress type it supports:
https://github.com/apache/parquet-format/blob/54e6133e887a6ea90501ddd72fff5312b7038a7c/src/main/thrift/parquet.thrift#L461-L469
Unless we want to compress the binlog binary again after the storage serialization, maybe it's better to utilize parquet's function.

**Comment by yah01** [comment]
Sounds like I miss some information... Let me test these algorithms first

**Comment by congqixia** [comment]
/reopen
@yah01 even binlog compression can be done in C side, we could utilize these compressor in other payloads.

**Comment by xiaofan-luan** [comment]
> /reopen @yah01 even binlog compression can be done in C side, we could utilize these compressor in other payloads.

for binlog in pulsar, zstd compression might still be valid?

**Comment by congqixia** [comment]
> > /reopen @yah01 even binlog compression can be done in C side, we could utilize these compressor in other payloads.
> 
> for binlog in pulsar, zstd compression might still be valid?

Yeap.

**Review by congqixia — APPROVED** [review]
@yah01 please add comment for all exported type/functions later. Others lgtm.
/lgtm

**Pull request merged**
