### PR TITLE
fix: [skip-e2e] Fix unstable SaveBinlogPath ut

### LINKED ISSUE #30507: [Bug]: Unitetest `TestServerSuite/TestSaveBinlogPath_SaveDroppedSegment/segID=1,_sealed_to_flushing` is not stable
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 18b979d
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Unit test is not stable

### Expected Behavior

Unit test shall pass stably

### Steps To Reproduce

_No response_

### Milvus Log

```
2024-02-04T09:49:53.9015390Z [2024/02/04 09:49:53.901 +00:00] [INFO] [datacoord/meta.go:407] ["meta update: setting segment state - complete"] [segmentID=1] ["target state"=Flushed]
2024-02-04T09:49:53.9020850Z [2024/02/04 09:49:53.901 +00:00] [INFO] [datacoord/server.go:1067] ["flush segment complete"] [id=1]
2024-02-04T09:49:53.9022485Z [2024/02/04 09:49:53.901 +00:00] [INFO] [datacoord/index_service.go:125] ["receive new flushed segment"] [segmentID=1]
2024-02-04T09:49:53.9028600Z     services_test.go:262: 
2024-02-04T09:49:53.9029677Z         	Error Trace:	/go/src/github.com/milvus-io/milvus/internal/datacoord/services_test.go:262
2024-02-04T09:49:53.9030906Z         	            				/go/pkg/mod/github.com/stretchr/testify@v1.8.4/suite/suite.go:112
2024-02-04T09:49:53.9031729Z         	Error:      	Not equal: 
2024-02-04T09:49:53.9032238Z         	            	expected: 5
2024-02-04T09:49:53.9032698Z         	            	actual  : 4
2024-02-04T09:49:53.9033604Z         	Test:       	TestServerSuite/TestSaveBinlogPath_SaveDroppedSegment/segID=1,_sealed_to_flushing
```

### Anything else?

https://github.com/milvus-io/milvus/actions/runs/7772737239/attempts/1

### PR DESCRIPTION
**Pull request by XuanYang-cn**
Fixes: #30507

### CODE REVIEW

**Comment by XuanYang-cn** [comment]
@Mergifyio refresh

**Review by congqixia — APPROVED** [review]
/lgtm

**Pull request merged**
