### PR TITLE
fix search failed when empty segment exist

### PR DESCRIPTION
**Pull request by weiliu1031**
issue: #27913

the skip empty logic will return `SegmentNotLoaded` when meet empty segment, fix it
/kind bug

### CODE REVIEW

**Review by congqixia — APPROVED** [review]
/lgtm

**Review by congqixia — APPROVED** [review]
/lgtm

**Comment by weiliu1031** [comment]
empty growing/sealed segment in query node is invalid, and we should avoid add empty growing/sealed segment to delegator's distribution.  if search/query request to read a empty segment, which is also regard as released segment,  it should return a `SegmentNotLoaded` error.

see also #27930

**Pull request closed without merging**
