### PR TITLE
enhance: decrease coordinator init time

### PR DESCRIPTION
**Pull request by yiwangdr**
This PR mainly improve two items:
1. Target observer should refresh loading status during init time. An uninitialized loading status blocks search/query. Currently, the target observer refreshes every 10 seconds, i.e. we'd need to wait for 10s for no reason. That's also the reason why we constantly see false log "collection unloaded" upon mixcoord restarts.
2. Delete session when service is stopped. So that the new service doesn't need to wait for the previous session to expire (~10s).

Item 1 is the major improvement of this PR, which should speed up init time by 10s.
Item 2 is not a big concern in most cases as coordinators usually shut down after stop(). In those cases, coordinator restart triggers serverID change which further triggers an existing logic that deletes expired session. This PR only fixes rare cases where serverID doesn't change.

integration test:
`go test -tags dynamic -v -coverprofile=profile.out -covermode=atomic tests/integration/coordrecovery/coord_recovery_test.go -timeout=20m`
Performance after the change:
Average init time of coordinators: 10s
Hardware: M2 Pro
Test setup: 1000 collections with 1000 rows (dim=128) per collection.

issue: #29409

### CODE REVIEW

**Comment by yiwangdr** [comment]
rerun ut

**Comment by yiwangdr** [comment]
rerun ut

**Comment by yiwangdr** [comment]
rerun ut

**Comment by yiwangdr** [comment]
rerun ut

**Review by congqixia — COMMENTED** [review]
/lgtm

**Review by congqixia — APPROVED** [review]
/lgtm

**Pull request merged**
