### PR TITLE
enhance: Improve bitset performance for AVX512

### PR DESCRIPTION
**Pull request by alexanderguzhva**
see #35478

optimized functions take 20%+ less time to run

### CODE REVIEW

**Comment by xiaofan-luan** [comment]
/assign @zhagnlu 
please help on reviewing that

**Comment by alexanderguzhva** [comment]
just in case, I did a thorough test and benchmarking using https://github.com/milvus-io/milvus/blob/master/internal/core/unittest/test_bitset.cpp (set `RUNNING_MODE` to `0` and `2`), which can test way more than we do in CI

**Pull request merged**
