### PR TITLE
enhance: Unify data type check APIs under internal/core

### PR DESCRIPTION
**Pull request by cydrain**
Issue: #22837 

Move and rename following C++ APIs:
datatype_sizeof() ==> GetDataTypeSize()
datatype_name() ==> GetDataTypeName()
datatype_is_vector() / IsVectorType() ==> IsVectorDataType()
datatype_is_variable() ==> IsVariableDataType()
datatype_is_sparse_vector() ==> IsSparseFloatVectorDataType()
datatype_is_string() / IsString() ==> IsDataTypeString()
datatype_is_floating() / IsFloat() ==> IsDataTypeFloat()
datatype_is_binary() ==> IsDataTypeBinary()
datatype_is_json() ==> IsDataTypeJson()
datatype_is_array() ==> IsDataTypeArray()
datatype_is_variable() == IsDataTypeVariable()
datatype_is_integer() / IsIntegral() ==> IsDataTypeInteger()

### CODE REVIEW

**Comment by czs007** [comment]
@cydrain please pick the non-float16 part to branch 2.4

**Comment by cydrain** [comment]
> @cydrain please pick the non-float16 part to branch 2.4

OK

**Pull request merged**
