### PR TITLE
Use singleton Params

### PR DESCRIPTION
**Pull request by jiaoew1991**
Signed-off-by: Enwei Jiao <enwei.jiao@zilliz.com>
issue : #18300

What changed in this PR
1. define global variable `Params` in paramtable/runtime.go
2. make all of the components use the global `Params` instead of the private one 
3. use only 1 `NodeID` in 1 process even in standalone mode, the NodeID will be saved in the global `Params`

### CODE REVIEW

**Comment by jiaoew1991** [comment]
What changed in this PR
1. define global variable `Params` in paramtable/runtime.go
2. make all of the components use the global `Params` instead of the private one 
3. use only 1 `NodeID` in 1 process even in standalone mode, the NodeID will be saved in the global `Params`

**Comment by jiaoew1991** [comment]
rerun ut

**Review by congqixia — APPROVED** [review]
/lgtm

**Pull request merged**
