### PR TITLE
enhance: Accelerate the loading of collection

### PR DESCRIPTION
**Pull request by bigsheeper**
Remove unnecessary ListIndex and DescribeCollection RPC call during loading.

issue: https://github.com/milvus-io/milvus/issues/37166

### CODE REVIEW

**Comment by chyezh** [comment]
\lgtm

**Comment by bigsheeper** [comment]
also related: https://github.com/milvus-io/milvus/issues/37630

**Comment by bigsheeper** [comment]
close due to https://github.com/milvus-io/milvus/pull/38059

**Pull request closed without merging**
