### PR TITLE
fix: before exiting, make sure the goroutine has exited

### PR DESCRIPTION
**Pull request by fengjun2016**
https://github.com/milvus-io/milvus/issues/35409

### CODE REVIEW

**Review by xiaofan-luan — COMMENTED** [review]
/lgtm
/approve

**Comment by jaime0815** [comment]
Hi @fengjun2016, please rebase onto master to fix the CI failures.

**Comment by jaime0815** [comment]
UT fail https://github.com/milvus-io/milvus/actions/runs/10368157426/job/28736664973?pr=35411

**Comment by fengjun2016** [comment]
> UT fail https://github.com/milvus-io/milvus/actions/runs/10368157426/job/28736664973?pr=35411

Hi@jaime0815 , done

**Pull request merged**
