### PR TITLE
Remove index dir

### PR DESCRIPTION
**Pull request by jaime0815**
issue: #12777  
This a spilt PR from #15107.

Signed-off-by: yun.zhang <yun.zhang@zilliz.com>

### CODE REVIEW

**Comment by XuanYang-cn** [comment]
```
CMake Error at src/CMakeLists.txt:22 (add_subdirectory):
  add_subdirectory given source "index" which is not an existing directory.
```

@jaime0815 Please make sure the compilation of knowhere is updated to use the `milvus-io/knowhere` repo if this PR wants to delete the embedded `index` directory so that CI and Github Actions won't fail during compilation.

**Comment by jaime0815** [comment]
> ```
> CMake Error at src/CMakeLists.txt:22 (add_subdirectory):
>   add_subdirectory given source "index" which is not an existing directory.
> ```
> 
> @jaime0815 Please make sure the compilation of knowhere is updated to use the `milvus-io/knowhere` repo if this PR wants to delete the embedded `index` directory so that CI and Github Actions won't fail during compilation.

This PR will compile failed,  it is a partial code of this [patch](https://github.com/milvus-io/milvus/pull/15107), the compiling will pass after merging the patch.

**Comment by XuanYang-cn** [comment]
> This PR will compile failed,  it is a partial code of this [patch](https://github.com/milvus-io/milvus/pull/15107), the compiling will pass after merging the patch.

So this PR should be held until #15107  is merged, and will be able to merge **after** rebasing the #15107  patch? Cuz failing PRs are not gonna be able to merge into master branch.

**Pull request merged**
