### PR TITLE
Update query_boolean_expr.md

### PR DESCRIPTION
**Pull request by xaxys**
Update query_boolean_expr.md

Related issue: #6460

Signed-off-by: xaxys <tpnnghd@163.com>

### CODE REVIEW

**Comment by czs007** [comment]
Can you translate it into English? @xaxys

**Comment by xaxys** [comment]
Sure

**Comment by xiaofan-luan** [comment]
I've already finished expression document and sent to pull request to mivlus-docs. @xaxys @FluorineDog 
https://github.com/milvus-io/milvus-docs/pull/294 anyone check this document?

**Pull request merged**
