### PR TITLE
fix: [Cherry-pick] pymilvus hangs after calling do_bulk_insert() with a non-exist collection name

### PR DESCRIPTION
**Pull request by yhmo**
resolve: #29342
pr: https://github.com/milvus-io/milvus/pull/29683

### CODE REVIEW

**Comment by samhuang-z** [comment]
rerun ut

**Comment by yhmo** [comment]
rerun ut

**Comment by yhmo** [comment]
rerun ut

**Comment by yhmo** [comment]
rerun ut

**Comment by samhuang-z** [comment]
rerun ut

**Comment by yhmo** [comment]
rerun ut

**Pull request closed without merging**
