### PR TITLE
use envoy and headless service to get `low latency、high throughput` support

### PR DESCRIPTION
**Pull request by sunyaofei**
**What type of PR is this?**

- [ ] API-change
- [ ] BUG
- [ ] Improvement
- [ ] Documentation
- [x] Feature
- [ ] Test and CI
- [ ] Code Refactoring

**Which issue(s) this PR fixes:**

https://github.com/milvus-io/milvus/issues/4543

**What this PR does / why we need it:**

use envoy and headless service under kubernetes to solve the problem

**Special notes for your reviewer:**

Not Available

**Additional documentation (e.g. design docs, usage docs, etc.):**

Not Available

### CODE REVIEW

**Comment by JinHai-CN** [comment]
DCO, Code static analysis and CI are failed, would you please fix them? @sunyaofei

**Comment by jeffoverflow** [comment]
Why use `DaemonSet` to deploy Milvus readonly server?

**Comment by sunyaofei** [comment]
> Why use `DaemonSet` to deploy Milvus readonly server?

See [daemonset-vs-deployment](https://github.com/sunyaofei/milvus/tree/deploy_with_envoy20201203/deploy#daemonset-vs-deployment), `DaemonSet` and `Deployment` are just two options while DaemonSet can guarantee the pods distributed evenly across all available nodes easily when it is necessary.

**Comment by jeffoverflow** [comment]
> > Why use `DaemonSet` to deploy Milvus readonly server?
> 
> See [daemonset-vs-deployment](https://github.com/sunyaofei/milvus/tree/deploy_with_envoy20201203/deploy#daemonset-vs-deployment), `DaemonSet` and `Deployment` are just two options while DaemonSet can guarantee the pods distributed evenly across all available nodes easily when it is necessary.

Is it possible to use [Pod affinity and anti-affinity](https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#inter-pod-affinity-and-anti-affinity) to guarantee the pods distributed evenly across all available nodes ?

**Comment by sunyaofei** [comment]
> > > Why use `DaemonSet` to deploy Milvus readonly server?
> > 
> > 
> > See [daemonset-vs-deployment](https://github.com/sunyaofei/milvus/tree/deploy_with_envoy20201203/deploy#daemonset-vs-deployment), `DaemonSet` and `Deployment` are just two options while DaemonSet can guarantee the pods distributed evenly across all available nodes easily when it is necessary.
> 
> Is it possible to use [Pod affinity and anti-affinity](https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#inter-pod-affinity-and-anti-affinity) to guarantee the pods distributed evenly across all available nodes ?

Yes, affinity is an option working with Deployment, but it's a little complex, especially when milvus ro pods need to accupy whole node(no two milvus ro pods in a same node, regardless of other type pods).
And [Pod Schedule](https://github.com/sunyaofei/milvus/tree/deploy_with_envoy20201203/deploy#pod-schedule) is not import part for this PR.

**Comment by sunyaofei** [comment]
> > > > Why use `DaemonSet` to deploy Milvus readonly server?
> > > 
> > > 
> > > See [daemonset-vs-deployment](https://github.com/sunyaofei/milvus/tree/deploy_with_envoy20201203/deploy#daemonset-vs-deployment), `DaemonSet` and `Deployment` are just two options while DaemonSet can guarantee the pods distributed evenly across all available nodes easily when it is necessary.
> > 
> > 
> > Is it possible to use [Pod affinity and anti-affinity](https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#inter-pod-affinity-and-anti-affinity) to guarantee the pods distributed evenly across all available nodes ?
> 
> Yes, affinity is an option working with Deployment, but it's a little complex, especially when milvus ro pods need to accupy whole node(no two milvus ro pods in a same node, regardless of other type pods).
> And [Pod Schedule](https://github.com/sunyaofei/milvus/tree/deploy_with_envoy20201203/deploy#pod-schedule) is not import part for this PR.

@jeffoverflow Are there any other problems that should be taken into acount ?

**Review by jeffoverflow — APPROVED** [review]

**Comment by jeffoverflow** [comment]
@sunyaofei `Deployment` is better suited to most  most user scenarios than `DaemonSet`.
See [typical uses cases for Deployment](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#use-case)

Some typical uses cases of a DaemonSet are: 
- running a cluster storage daemon on every node
- running a logs collection daemon on every node
- running a node monitoring daemon on every node

**Comment by sunyaofei** [comment]
> @sunyaofei `Deployment` is better suited to most user scenarios than `DaemonSet`.
> See [typical uses cases for Deployment](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#use-case)
> 
> Some typical uses cases of a DaemonSet are:
> 
> * running a cluster storage daemon on every node
> * running a logs collection daemon on every node
> * running a node monitoring daemon on every node

Thanks a lot, i got it. DaemonSet actually also works well when we need to strictly limit one and only one same type pod to one node.

**Review by JinHai-CN — APPROVED** [review]

**Pull request merged**
