### PR TITLE
print some group info in rocksmq monitor

### PR DESCRIPTION
**Pull request by aoiasd**
related: https://github.com/milvus-io/milvus/issues/19574 https://github.com/milvus-io/milvus/issues/18288
Signed-off-by: aoiasd <zhicheng.yue@zilliz.com>

### CODE REVIEW

**Comment by aoiasd** [comment]
rerun ut

**Comment by aoiasd** [comment]
rerun ut

**Comment by aoiasd** [comment]
rerun ut

**Review by congqixia — APPROVED** [review]
/lgtm

**Pull request merged**
