### PR TITLE
enhance: [GoSDK] move client pkg go files to sub one

### PR DESCRIPTION
**Pull request by congqixia**
Related to #31293

Client source files under client pkg cannot be evaluate correctly by codecov. This PR moves them to `milvusclient` sub-package to fix this issue and follow go major version best practice.

### CODE REVIEW

**Comment by congqixia** [comment]
rerun cpp-unit-test

**Comment by congqixia** [comment]
rerun go-sdk

**Comment by congqixia** [comment]
rerun cpp-unit-test

**Comment by congqixia** [comment]
rerun cpp-unit-test

**Comment by congqixia** [comment]
rerun go-sdk

**Review by ThreadDao — COMMENTED** [review]
/lgtm

**Pull request merged**
