### PR TITLE
Fix bug: override the compare function of SearchResultPair

### LINKED ISSUE #6627: Bug: wrong usage of std::sort and NaN when reducing search results
```c++
void
GetResultData(std::vector<std::vector<int64_t>>& search_records,
              std::vector<SearchResult*>& search_results,
              int64_t query_offset,
              bool* is_selected,
              int64_t topk) {
    auto num_segments = search_results.size();
    AssertInfo(num_segments > 0, "num segment must greater than 0");
    std::vector<SearchResultPair> result_pairs;
    for (int j = 0; j < num_segments; ++j) {
        auto distance = search_results[j]->result_distances_[query_offset];
        auto search_result = search_results[j];
        AssertInfo(search_result != nullptr, "search result must not equal to nullptr");
        result_pairs.push_back(SearchResultPair(distance, search_result, query_offset, j));
    }
    int64_t loc_offset = query_offset;
    AssertInfo(topk > 0, "topk must greater than 0");
    for (int i = 0; i < topk; ++i) {
        result_pairs[0].reset_distance();
        std::sort(result_pairs.begin(), result_pairs.end(), std::greater<>());
        auto& result_pair = result_pairs[0];
        auto index = result_pair.index_;
        is_selected[index] = true;
        result_pair.search_result_->result_offsets_.push_back(loc_offset++);
        search_records[index].push_back(result_pair.offset_++);
    }
}
```

In this function, we use `std::sort` and `std::greater` to sort hit records between all segments. In the topk loop, we will take the first record of `result_pairs` and then replace the first record of a new record. However, when the distance of new record is NaN, the `std::greater` will think NaN is greater than the other records in `result_pairs`, so after next process, we will take the new record with NaN distance. This is wrong and will result in that reducing process filter the wrong record.

This bug will cause #6569 

We should override the `greater` function like below:

```c++
struct SearchResultPair {
    float distance_;
    SearchResult* search_result_;
    int64_t offset_;
    int64_t index_;

    SearchResultPair(float distance, SearchResult* search_result, int64_t offset, int64_t index)
        : distance_(distance), search_result_(search_result), offset_(offset), index_(index) {
    }

    bool
    operator<(const SearchResultPair& pair) const {
        return std::isnan(pair.distance_) || (!std::isnan(distance_) && (distance_ < pair.distance_));
    }

    bool
    operator>(const SearchResultPair& pair) const {
        return std::isnan(pair.distance_) || (!std::isnan(distance_) && (distance_ > pair.distance_));
    }

    void
    reset_distance() {
        distance_ = search_result_->result_distances_[offset_];
    }
};
```

### PR DESCRIPTION
**Pull request by longjiquan**
Signed-off-by: dragondriver <jiquan.long@zilliz.com>

issue: #6627 #6569

### CODE REVIEW

**Comment by xige-16** [comment]
please add ut for the bug

**Comment by czs007** [comment]
good job.
/lgtm
/approve

**Pull request merged**
