### PR TITLE
Bump ants to v2.7.2 for performance improvement

### PR DESCRIPTION
**Pull request by panjf2000**
Signed-off-by: Andy Pan <i@andypan.me>

See the [release notes](https://github.com/panjf2000/ants/releases/tag/v2.7.0) of ants v2.7

### CODE REVIEW

**Comment by panjf2000** [comment]
rerun ut

**Comment by zhuwenxing** [comment]
rerun ut

**Comment by panjf2000** [comment]
Any updates?

**Comment by xiaofan-luan** [comment]
I'll take look into it~

**Comment by xiaofan-luan** [comment]
@panjf2000 
thanks for the contribution~
Any brief introduction about the benefit to upgrade?
And maybe something to the milvus developer about the project itself? We love the implmenetation

**Comment by panjf2000** [comment]
This [job](https://github.com/milvus-io/milvus/actions/runs/4499764556/jobs/7979945435?pr=22936) failed to upload the test coverage to codecov, I assume that it needs to be retried.

**Comment by jiaoew1991** [comment]
> This [job](https://github.com/milvus-io/milvus/actions/runs/4499764556/jobs/7979945435?pr=22936) failed to upload the test coverage to codecov, I assume that it needs to be retried.


Fixed it

**Pull request merged**
