### PR TITLE
Add default retrieve limit

### PR DESCRIPTION
**Pull request by xige-16**
/kind improvement 
issue: https://github.com/milvus-io/milvus/issues/24435
pr: https://github.com/milvus-io/milvus/pull/24782 https://github.com/milvus-io/milvus/pull/27054

Signed-off-by: xige-16 <xi.ge@zilliz.com>

### CODE REVIEW

**Comment by bigsheeper** [comment]
Still may be OOM? (Since we support get vector now.) Maybe we should make this check in segcore.

**Comment by bigsheeper** [comment]
related: https://github.com/milvus-io/milvus/issues/24435

**Comment by xige-16** [comment]
rerun ut

**Comment by xige-16** [comment]
rerun ut

**Pull request merged**
