### PR TITLE
Fix restore redrop enormous dup collections

### PR DESCRIPTION
**Pull request by XuanYang-cn**
/kind improvement
pr: #26029

### CODE REVIEW

**Comment by XuanYang-cn** [comment]
/run-cpu-e2e
rerun ut

**Comment by XuanYang-cn** [comment]
rerun ut

**Review by congqixia — APPROVED** [review]
/lgtm

**Comment by XuanYang-cn** [comment]
rerun ut

**Review by congqixia — APPROVED** [review]
/lgtm

**Pull request merged**
