### PR TITLE
[skip ci] Add requirements when build

### PR DESCRIPTION
**Pull request by shiyu22**
#7579

### CODE REVIEW

**Comment by czs007** [comment]
> #7579

please include `Signed-off-by` line.
like this:

```
Resolves: #7586
Signed-off-by: ss892714028 sida.shen@zilliz.com
```
@shiyu22 @shiyu09

**Comment by scsven** [comment]
@shiyu22 Please squash your commits local. Use this command: `git rebase -i master`.

**Comment by shiyu22** [comment]
The repo disappeared, close.

**Pull request closed without merging**
