### PR TITLE
Make DN fail faster when watching an invalid chan

### PR DESCRIPTION
**Pull request by XuanYang-cn**
See also: #11098

Signed-off-by: yangxuan <xuan.yang@zilliz.com>

/kind enhancement

### CODE REVIEW

**Review by congqixia — APPROVED** [review]
/lgtm

**Review by congqixia — APPROVED** [review]
/lgtm

**Comment by sunby** [comment]
@XuanYang-cn Maybe we can write a smaller function named `createFlowGrpah` and put these codes in it. This function is too large.

**Pull request merged**
