### PR TITLE
fix: parse error given duplicated plan cache key

### PR DESCRIPTION
**Pull request by tedxu**
See: #37016

### CODE REVIEW

**Comment by tedxu** [comment]
The bug can be reproduced by recreating a collection with the same name but different schema within 10 minutes. The reason is that the parse cache is keyed by collection name. 

In this PR, the parse cache is changed to cache only ASTs, not the parse expressions generated by AST visitors. Therefore schema is not necessary. The performance loss is neglectable, see following benchmark result:

Before:
```
BenchmarkNoPlanCache-8              7212            144032 ns/op           15849 B/op        178 allocs/op
```
After:
```
BenchmarkPlanCache/uncached-8               8457            143421 ns/op           15890 B/op        178 allocs/op
```

**Comment by tedxu** [comment]
rerun go-sdk

**Comment by tedxu** [comment]
rerun go-sdk

**Comment by tedxu** [comment]
Related issue: #37028

**Comment by tedxu** [comment]
rerun cpp-unit-test

**Review by congqixia — APPROVED** [review]
/lgtm

**Pull request merged**
