### PR TITLE
Make load operation parallel improve performance

### PR DESCRIPTION
**Pull request by yah01**
Signed-off-by: yah01 <yang.cen@zilliz.com>
#15736 #13264

### CODE REVIEW

**Comment by yah01** [comment]
The querycoord merges all (or the most) of segments for one querynode into single request ([ref](https://github.com/milvus-io/milvus/pull/15895)), and querynode processes LoadSegments request with only 1 goroutine. This increases 2x~3x performance for my local bench, it should be more significant for cluster with more querynodes

**Comment by congqixia** [comment]
Overall lgtm. Nice improvement! 
Just one concern here: the concurrent load might cause extra memory usage, roughly extra C*[core number]*[Segment size]

**Review by congqixia — APPROVED** [review]
/lgtm

**Pull request merged**
