### PR TITLE
fix: Reset cluster scope rate with paramtable values and force update it

### PR DESCRIPTION
**Pull request by congqixia**
See also #35496

### CODE REVIEW

**Comment by SimFG** [comment]
When the limit value is inf, it is best to skip it, because there is a cluster/db/collection/partition level limiter. When the number of collections is large, this may cause a large RPC request.

**Comment by congqixia** [comment]
> When the limit value is inf, it is best to skip it, because there is a cluster/db/collection/partition level limiter. When the number of collections is large, this may cause a large RPC request.

@SimFG the bug I met was that when the `quotaAndLimits.dml.insertRate.max` is set to 5, all proxies receives no limit. After update the reset logic, all proxies still get no update since the `hasUpdate` flag is always false for stable cluster configuration.

**Comment by SimFG** [comment]
The proxy limit is not completely obtained by rootcoord, but can also be configured. Before this pr, if quotaAndLimits.dml.insertRate.max is set to 5, if there are 5 proxies, the insert rate of each proxy is not infinite, but 5. Although the expectation is 1, it does not mean that there is no limit.

So if this is removed now, the expected result will be obtained, but an additional logic needs to be added, that is, if the value of the limit is inf, do not put this limit in the request. In this way, by default, the request to update the limit will be very small.

**Comment by congqixia** [comment]
> The proxy limit is not completely obtained by rootcoord, but can also be configured. Before this pr, if quotaAndLimits.dml.insertRate.max is set to 5, if there are 5 proxies, the insert rate of each proxy is not infinite, but 5. Although the expectation is 1, it does not mean that there is no limit.
> 
> So if this is removed now, the expected result will be obtained, but an additional logic needs to be added, that is, if the value of the limit is inf, do not put this limit in the request. In this way, by default, the request to update the limit will be very small.

@SimFG  yes, `Inf` is checked at line 1475, Inf rate will not be sent

**Pull request closed without merging**
