### PR TITLE
Changed from std::cout to LOG for error messages

### PR DESCRIPTION
**Pull request by erdustiggen**
Suggested fix for issue #328.
Please let me know if anything needs to be changed.

### CODE REVIEW

**Review by JinHai-CN — APPROVED** [review]

**Comment by jielinxu** [comment]
Hi @erdustiggen , thanks a lot for your time and effort in submitting the pull requests. As they are already merged, you become one of the top 50 Milvus contributors. 🎉 Could you please provide an email address so that we can contact you for further details? Thanks again!

**Comment by jielinxu** [comment]
@erdustiggen And welcome to join our community discusssion group on [Slack channel](https://join.slack.com/t/milvusio/shared_invite/enQtNzY1OTQ0NDI3NjMzLWNmYmM1NmNjOTQ5MGI5NDhhYmRhMGU5M2NhNzhhMDMzY2MzNDdlYjM5ODQ5MmE3ODFlYzU3YjJkNmVlNDQ2ZTk).

**Comment by jielinxu** [comment]
@all-contributors please add @erdustiggen for code

**Comment by jielinxu** [comment]
@all-contributors please add @erdustiggen for code

**Comment by jielinxu** [comment]
@all-contributors please add @erdustiggen for code

**Comment by jielinxu** [comment]
@all-contributors please add @erdustiggen for code

**Pull request merged**
