### PR TITLE
fix: err cannot be captured in defer in data_sync_service

### PR DESCRIPTION
**Pull request by fengjun2016**
https://github.com/milvus-io/milvus/issues/35447

### CODE REVIEW

**Comment by jaime0815** [comment]
Hi @fengjun2016 please resolve the DOC check error.

**Comment by fengjun2016** [comment]
> Hi @fengjun2016 please resolve the DOC check error.

I have signed, but not trigger doc check again to label doc-passed

截屏2024-08-13 17 50 07

**Comment by fengjun2016** [comment]
> Hi @fengjun2016 please resolve the DOC check error.

Thanks, done

**Pull request merged**
