### PR TITLE
Fix compile protocol buffer files error

### PR DESCRIPTION
**Pull request by BUPTAnderson**
Fix compile protocol buffer files error #8045

Signed-off-by: BUPTAnderson <yunlongkong@126.com>

### CODE REVIEW

**Comment by BUPTAnderson** [comment]
Hi xiaofan, I have checked the DCO settings and append Signed-off-by line to commit messages.
please review again, thx
ps: I have closed the non-conform pr #8046

**Comment by XuanYang-cn** [comment]
see #8045

**Comment by scsven** [comment]
@BUPTAnderson Thanks for your contribution!

**Pull request merged**
