### PR TITLE
feat: add segment,pipeline, replica and resourcegroup api for WebUI

### PR DESCRIPTION
**Pull request by jaime0815**
issue: #36621

### CODE REVIEW

**Comment by jaime0815** [comment]
rerun go-sdk

**Comment by jaime0815** [comment]
rerun cpp-unit-test

**Comment by jaime0815** [comment]
rerun cpp-unit-test

**Comment by jaime0815** [comment]
rerun cpp-unit-test

**Review by SimFG — COMMENTED** [review]
/lgtm

**Pull request merged**
