### PR TITLE
enhance: the return result of list db api

### PR DESCRIPTION
**Pull request by SimFG**
issue: #31543

### CODE REVIEW

**Comment by xiaofan-luan** [comment]
/assign @yanliang567

could we verify on this?

list databases don't require global permission
it returns all the db's this user has permission with

**Comment by SimFG** [comment]
@xiaofan-luan 
the `list databases` also need the global permission.
The current optimization is: even if you have list database permissions, only the dbs for which you have relevant permissions will be returned instead of all dbs. In other words: user `a` and user `b` both call the list database api and may return different permissions.

**Pull request merged**
