### PR TITLE
[Cherry-Pick] Control addFile concurrency to reduce memory peak

### PR DESCRIPTION
**Pull request by xige-16**
Cherry pick from https://github.com/milvus-io/milvus/pull/22776
fix issue: #22463 
/kind bug

Signed-off-by: xige-16 <xi.ge@zilliz.com>

### CODE REVIEW

**Comment by xige-16** [comment]
rerun ut

**Comment by xige-16** [comment]
rerun ut

**Comment by xige-16** [comment]
rerun ut

**Comment by xige-16** [comment]
rerun ut

**Comment by czs007** [comment]
will be shipped in 2.2.5

**Pull request closed without merging**
