### PR TITLE
Minor fixes

### PR DESCRIPTION
**Pull request by donno2048**
- Comment unused import
- Correct `assert` usage in never reached code

### CODE REVIEW

**Comment by scsven** [comment]
/kind improvement

Hi @donno2048, thanks for your contribution! The DCO check is failed, to fix this, [this](https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md) may be helpful. And another thing is that squash commits into one is recommended because multiple commits merging by the bot will make the commit history not clear.

**Comment by donno2048** [comment]
@scsven just force pushed

**Comment by scsven** [comment]
This change doesn't need a ci test, so I set it ci-passed manually.

**Comment by scsven** [comment]
@donno2048 Thanks for your contribution, this pull request will be merged by bot. :)

**Comment by donno2048** [comment]
> This change doesn't need a ci test, so I set it ci-passed manually.

Looks like the bot doesn't think so 😆

**Comment by scsven** [comment]
> > This change doesn't need a ci test, so I set it ci-passed manually.
> 
> Looks like the bot doesn't think so 😆

Aha, I will remove the wrong rules.

**Comment by donno2048** [comment]
@scsven mind adding the `ci-passed` label again?

**Comment by scsven** [comment]
It's merged into the master branch. Thanks for your contribution!

**Pull request merged**
