### PR TITLE
enhance: Use load pool for `CreateTextIndex`

### PR DESCRIPTION
**Pull request by congqixia**
Related to #37895

Only resolves the starving issue which caused goroutine leakage

### CODE REVIEW

**Comment by xiaofan-luan** [comment]
Why to use a load pool for index building?
That doesn't seems to be a good fix.
/hold

**Comment by congqixia** [comment]
@xiaofan-luan it was building temporary text index in load process. At least it shall not use dynamic pool. Don't think it's a good idea to open other pool in querynode.

**Pull request merged**
