### PR TITLE
[skip ci] remove useless content

### PR DESCRIPTION
**Pull request by shiyu22**
Signed-off-by: shiyu22 shiyu.chen@zilliz.com

### CODE REVIEW

**Comment by yanliang567** [comment]
@shiyu22 you shall sign off the commit

**Comment by shiyu22** [comment]
> @shiyu22 you shall sign off the commit

I have added it to the content, does it not work? And how to add in command?

**Comment by yanliang567** [comment]
you shall sign off in commit instead of in pr content. maybe recommit is easier for you

**Pull request merged**
