### PR TITLE
enhance: [GoSDK] Use generic column base and add unit tests

### PR DESCRIPTION
**Pull request by congqixia**
Related to #31293

Previous column is written using go before 1.18, which does not support generic type. After migrating client pkg to main repo, generic base could be used to reduce lots of duplicated code.

### CODE REVIEW

**Comment by congqixia** [comment]
rerun cpp-unit-test

**Comment by congqixia** [comment]
rerun cpp-unit-test

**Review by ThreadDao — COMMENTED** [review]
/lgtm

**Pull request merged**
