### PR TITLE
fix: used wrong label for query received_nq metrics

### PR DESCRIPTION
**Pull request by Reidddddd**
issue: #37982

### CODE REVIEW

**Comment by Reidddddd** [comment]
rerun go-sdk

**Comment by Reidddddd** [comment]
failed with ```[pytest : test] [2024-11-25 08:15:22 - ERROR - pymilvus.decorators]: RPC error: [search], <MilvusException: (code=65535, message=not allowed to retrieve raw data of field text_sparse_emb)>, <Time:{'RPC start': '2024-11-25 08:15:22.913176', 'RPC error': '2024-11-25 08:15:22.915668'}> (decorators.py:140)```

seems to be not relevant

**Comment by Reidddddd** [comment]
Hi @xiaofan-luan , can please take a look, a very simple patch

**Comment by xiaofan-luan** [comment]
@Reidddddd 
we need an issue and description for this pr to merge

**Comment by Reidddddd** [comment]
> @Reidddddd we need an issue and description for this pr to merge

Issue is here: https://github.com/milvus-io/milvus/issues/37982

**Comment by Reidddddd** [comment]
append issue & pr ticket in the commit message

**Comment by Reidddddd** [comment]
rerun cpp-unit-test

**Comment by Reidddddd** [comment]
Hi @xiaofan-luan, ci passed, and commit message is updated as well, thx

**Pull request merged**
