### PR TITLE
fix grafana dashboard could not show namespace

### PR DESCRIPTION
**Pull request by xiedeyantu**
fix grafana dashboard could not show namespace.

### CODE REVIEW

**Comment by xiedeyantu** [comment]
@jiaoew1991 Please help to have a look ?

**Comment by jiaoew1991** [comment]
@LoveEachDay please help to review this PR

**Review by LoveEachDay — COMMENTED** [review]
label_values requires two arguments:
1. metrics name
2. metric label
By default we use `kube_pod_info` to retrieve all the namespaces in your kubernetes cluster.

**Comment by xiedeyantu** [comment]
> label_values requires two arguments:
> 
> 1. metrics name
> 2. metric label
>    By default we use `kube_pod_info` to retrieve all the namespaces in your kubernetes cluster.

But you won't see all the namespaces using `kube_pod_info`.

**Comment by xiedeyantu** [comment]
> label_values requires two arguments:
> 
> 1. metrics name
> 2. metric label
>    By default we use `kube_pod_info` to retrieve all the namespaces in your kubernetes cluster.

@LoveEachDay Two arguments can not work for me. Please have a look ?

**Comment by LoveEachDay** [comment]
> > label_values requires two arguments:
> > 
> > 1. metrics name
> > 2. metric label
> >    By default we use `kube_pod_info` to retrieve all the namespaces in your kubernetes cluster.
> 
> @LoveEachDay Two arguments can not work for me. Please have a look ?

You  can change the dashboard at your own grafana.

**Comment by LoveEachDay** [comment]
If `kube_pod_info` doesn't contain all the namespaces, you'd better check the log of pod `kube-state-metrics`.

**Comment by xiedeyantu** [comment]
> If `kube_pod_info` doesn't contain all the namespaces, you'd better check the log of pod `kube-state-metrics`.

@LoveEachDay Hi, thanks for reply.
Firstly, I can change my grafana dashboard json, but next user will meet this problem.
Secondly, using pod kube-state-metrics is not a suitable way, we need only to dependent on milvus itself.
So, it need to be fixed. My way may be not good way.

**Pull request closed without merging**
