### PR TITLE
enhance: generally improve the performance of mix compactions

### PR DESCRIPTION
**Pull request by tedxu**
See #37234

### CODE REVIEW

**Comment by tedxu** [comment]
The changes made by this PR include:
1. Skip Protobuf serde in mix compactions,
2. Remove useless size checkes, which is heavy in param table.
3. Refine the statistics collection code in segment writing.

Benchmark result before this PR:
```
BenchmarkMixCompactor-8   	       1	25943904125 ns/op	2013010864 B/op	19245985 allocs/op
```
After:
```
BenchmarkMixCompactor-8   	       1	14394981167 ns/op	1664913408 B/op	13345230 allocs/op
```

**Comment by tedxu** [comment]
rerun go-sdk
/run-cpu-e2e
rerun cpp-unit-test

**Comment by tedxu** [comment]
rerun cpp-unit-test

**Review by congqixia — APPROVED** [review]
/lgtm

**Pull request merged**
