### PR TITLE
Use the same lint rules with golint in revive

### PR DESCRIPTION
**Pull request by wxyucs**
Signed-off-by: Xiangyu Wang <xiangyu.wang@zilliz.com>

/kind improvement
/cc @congqixia

### CODE REVIEW

**Comment by congqixia** [comment]
@scsven  just tested with current configuration. If we want `revive` behave like `golint`, we need to remove all configuration of revive. By `all configuration`, I mean the whole block under revive
```
revive:
    ignore-generated-header: true
    severity: warning
    confidence: 0.8
...
```

**Comment by scsven** [comment]
> @scsven just tested with current configuration. If we want `revive` behave like `golint`, we need to remove all configuration of revive. By `all configuration`, I mean the whole block under revive
> 
> ```
> revive:
>     ignore-generated-header: true
>     severity: warning
>     confidence: 0.8
> ...
> ```

@congqixia updated.

**Comment by scsven** [comment]
@congqixia I fixed all the linter errors.

**Review by congqixia — APPROVED** [review]
/lgtm

**Comment by congqixia** [comment]
btw, we need add a rule to run code check as long as .golangci.yaml is changed

**Pull request merged**
