### PR TITLE
Remove VectorMemNMIndex index

### PR DESCRIPTION
**Pull request by cqy123456**
ivf_flat_nm has been removed in knohwere, so VectorMemNMIndex can not keep in milvus.
issue: https://github.com/milvus-io/milvus/issues/27026

### CODE REVIEW

**Comment by xige-16** [comment]
These functions can be removed
https://github.com/milvus-io/milvus/blob/45d9fb5929e400f42f7d35d51046189089b2ad85/internal/core/src/index/Utils.cpp#L49-L55

https://github.com/milvus-io/milvus/blob/45d9fb5929e400f42f7d35d51046189089b2ad85/internal/core/src/index/Utils.cpp#L80-L83

**Comment by cqy123456** [comment]
NM_List and  is_in_nm_list are useful in the later,  because knowhere deserialize  will only accept a controllable memory space but not a map of memory space.
Old ivf_flat_nm index format will be convert to new format before deserialize function call.

**Pull request merged**
