### PR TITLE
Fix failure while connect kafka with SASL_SSL

### PR DESCRIPTION
**Pull request by jaime0815**
issue #26599

### CODE REVIEW

**Comment by weiZhenkun** [comment]
when can merge this PR?
when can we release 2.3.1?

**Comment by weiZhenkun** [comment]
@jaime0815 can you fix them?

**Comment by jaime0815** [comment]
> @jaime0815 can you fix them?

it is blocked by #26626 to fix the pipeline job fails.

**Comment by weiZhenkun** [comment]
> > @jaime0815 can you fix them?
> 
> it is blocked by #26626 to fix the pipeline job fails.

Thanks. It is very important for us.

**Comment by weiZhenkun** [comment]
@jaime0815 Please merge, thanks!

**Comment by weiZhenkun** [comment]
@xiaocai2333  @godchen0212  Please review, thanks.

**Pull request merged**
