### PR TITLE
enhance: refactor variable column to reduce memory cost (#33875)

### PR DESCRIPTION
**Pull request by zhagnlu**
cherry-pick commit from master:
pr: #33875

### CODE REVIEW

**Comment by zhagnlu** [comment]
rerun ut

**Comment by zhagnlu** [comment]
rerun ut

**Comment by klboke** [comment]
@zhagnlu 
image
Hello. I noticed that in this PR, you removed the assertion check for the written file size. Could you please explain the rationale behind this decision? Is it because this check would never be triggered?

**Pull request merged**
