### PR TITLE
fix transfer node meta err

### LINKED ISSUE #22404: [Bug]: [ResourceGroup] The capacity of customer resource group is 0 after querycoord kill chaos
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20230223-8dc51144
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka):  pulsar  
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus 2.3.0.dev38
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

1. Create a cluster with 4 querynodes
2. Create `RG_0` and `RG_1` and their available querynodes are both 1
3. Create collection `ResourceGroup_111` and insert data, create index
4. Load 2 replicas of `ResourceGroup_111` into 'RG_0' and `RG_1`
5. pod kill querycoord and wait pods ready after remove chaos
6. sleep 6m
7. describe resource group: num_available_node is 1, but capacity is 0.
```
ResourceGroupInfo:

[2023-02-23T18:21:42.331Z]         <name:RG_0>, 

[2023-02-23T18:21:42.331Z]         <capacity:0>, 

[2023-02-23T18:21:42.331Z]         <num_available_node:1>, 

[2023-02-23T18:21:42.331Z]         <num_loaded_replica:{'ResourceGroup_111': 1}>, 

[2023-02-23T18:21:42.331Z]         <num_outgoing_node:{}>, 

[2023-02-23T18:21:42.331Z]         <num_incoming_node:{}>  (api_request.py:31)
```

### Expected Behavior

expect capacity is 1

### Steps To Reproduce

_No response_

### Milvus Log

cluster: devops
namespace: chaos-testing
jenkins pipeline: https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-resource-group/detail/chaos-test-resource-group/31/pipeline/312

Logs:
[artifacts-querycoord-pod-kill-31-pytest-logs.tar.gz](https://github.com/milvus-io/milvus/files/10823461/artifacts-querycoord-pod-kill-31-pytest-logs.tar.gz)

[artifacts-querycoord-pod-kill-31-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/10823463/artifacts-querycoord-pod-kill-31-server-logs.tar.gz)

Pods:
```
02:22:43  querycoord-pod-kill-31-milvus-datacoord-7488b9647-m9wzp          1/1     Running             0               17m     10.102.7.50     devops-node11   <none>           <none>
02:22:43  querycoord-pod-kill-31-milvus-datanode-6bf498fdcc-4sn9j          1/1     Running             0               17m     10.102.6.149    devops-node10   <none>           <none>
02:22:43  querycoord-pod-kill-31-milvus-datanode-6bf498fdcc-5wb2k          1/1     Running             0               17m     10.102.7.55     devops-node11   <none>           <none>
02:22:43  querycoord-pod-kill-31-milvus-indexcoord-888c9584f-rgtxc         1/1     Running             0               17m     10.102.7.54     devops-node11   <none>           <none>
02:22:43  querycoord-pod-kill-31-milvus-indexnode-5cdf65764-ng5cq          1/1     Running             0               17m     10.102.7.47     devops-node11   <none>           <none>
02:22:43  querycoord-pod-kill-31-milvus-proxy-55964bbd65-4f4fh             1/1     Running             0               17m     10.102.7.49     devops-node11   <none>           <none>
02:22:43  querycoord-pod-kill-31-milvus-querycoord-559b47b46-l5h58         1/1     Running             0               11m     10.102.7.125    devops-node11   <none>           <none>
02:22:43  querycoord-pod-kill-31-milvus-querynode-896ff45bb-59rz6          1/1     Running             0               17m     10.102.7.48     devops-node11   <none>           <none>
02:22:43  querycoord-pod-kill-31-milvus-querynode-896ff45bb-cq2bm          1/1     Running             0               17m     10.102.6.150    devops-node10   <none>           <none>
02:22:43  querycoord-pod-kill-31-milvus-querynode-896ff45bb-klvkc          1/1     Running             0               17m     10.102.9.5      devops-node13   <none>           <none>
02:22:43  querycoord-pod-kill-31-milvus-querynode-896ff45bb-nh2ng          1/1     Running             0               17m     10.102.5.181    devops-node21   <none>           <none>
02:22:43  querycoord-pod-kill-31-milvus-rootcoord-57967b5598-d9p76         1/1     Running             0               17m     10.102.7.52     devops-node11   <none>           <none>
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by weiliu1031**
Signed-off-by: Wei Liu <wei.liu@zilliz.com>
fix #22404

### CODE REVIEW

**Comment by weiliu1031** [comment]
rerun ut

**Review by jiaoew1991 — APPROVED** [review]
/lgtm

**Pull request merged**
