### PR TITLE
Update .clang-tidy-ignore

### PR DESCRIPTION
**Pull request by Ayushchaudhary-Github**
Fix: non function comment

### CODE REVIEW

**Comment by scsven** [comment]
/kind improvement

Hi @YushChaudhary, thanks for your contribution, but DCO is missing in this commit, which is required. To solve this problem, follow commands in https://github.com/milvus-io/milvus/pull/9022/checks?check_run_id=3765052406

**Comment by YushChaudhary** [comment]
I install the DCO still anything not happen.

**Comment by xiaofan-luan** [comment]
Hi Yush, welcome. thanks for your contribution! The DCO check is failed, to fix this please check https://github.com/milvus-io/milvus/blob/master/CONTRIBUTING.md.  

Another thing is that squash commits into one is recommended because multiple commits merging by the bot will make the commit history not clear.

If you make changes only for comments, you can start your commit with [skip ci] so the ci check won't be applied

**Review by Ayushchaudhary-Github — COMMENTED** [review]
This is my commit message

Signed-off-by: Ayush Chaudhary<https://github.com/YushChaudhary>

**Comment by xiaofan-luan** [comment]
> This is my commit message
> 
> Signed-off-by: Ayush Chaudharyhttps://github.com/YushChaudhary

You will have to do git commit -sm "commit message",  "Signed-off-by: Ayush Chaudharyhttps://github.com/YushChaudhary" this message should be auto generated by -s  flag, CONTRIBUTING.md talks about how to commit in detail, thanks~

**Pull request closed without merging**
