### PR TITLE
Print Milvus banner when start service

### LINKED ISSUE #5916: Add Milvus banner when start service
**Please state your issue using the following template and, most importantly, in English.**

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. E.g. I wish I could use Milvus to do [...]

**Describe the solution you'd like**
Add Milvus banner when start service:
```
  Edition: %s
  Git Commit Hash: %s
  Git Branch: %s
  UTC Build Time: %s
  GoVersion: %s
```

### PR DESCRIPTION
**Pull request by cydrain**
Resolves: #5916 

Signed-off-by: yudong.cai <yudong.cai@zilliz.com>

### CODE REVIEW

**Review by wxyucs — APPROVED** [review]
/lgtm
/approve
/kind feature

**Comment by jeffoverflow** [comment]
I would like Milvus to print the version information in the following style
 `"Edition: %s\n"+
   "Git Commit Hash: %s\n"+
   "Git Branch: %s\n"+
   "UTC Build Time: %s\n"+
   "GoVersion: %s\n"`

**Pull request merged**
