### PR TITLE
enhance: add the cost response for the rest api

### PR DESCRIPTION
**Pull request by SimFG**
issue: https://github.com/milvus-io/milvus/issues/30436

### CODE REVIEW

**Comment by PowderLi** [comment]
I wonder that there is no need to update restful v1
only restful v2 is required

**Comment by PowderLi** [comment]
whether return cost or not, should we add a switch to control ?

**Comment by SimFG** [comment]
> whether return cost or not, should we add a switch to control ?

I think it is unnecessary, because there is no switch to control the return result of rpc, and this part is not functional. If the return value is controlled by the switch, I think it is a bit strange, and there will be inconsistencies in the functions between the cloud and offline, and there will be compatibility issues.

**Pull request merged**
