### PR TITLE
Switch to knowhere v1.0.1 and forked gorocksdb v0.0.1

### PR DESCRIPTION
**Pull request by soothing-rain**
Issue: #15585

### CODE REVIEW

**Comment by congqixia** [comment]
/hold 
@soothing-rain A pr shall have only one commit and have a kind tag.

**Comment by congqixia** [comment]
@jennyli-z this missing-related-issue tag issue, shall we keep this PR open for a moment?

**Comment by jennyli-z** [comment]
> 
yes, it would be better, wait a moment.

**Comment by jennyli-z** [comment]
> @jennyli-z this missing-related-issue tag issue, shall we keep this PR open for a moment?

yes

**Pull request merged**
