### PR TITLE
Use jemalloc in QueryNode, DataNode and IndexNode

### PR DESCRIPTION
**Pull request by bigsheeper**
Signed-off-by: bigsheeper <yihao.dai@zilliz.com>

issues: #16943

### CODE REVIEW

**Comment by xiaofan-luan** [comment]
/lgtm

hope jemalloc solve most of the memory issues in Cpp side

**Comment by bigsheeper** [comment]
> /lgtm
> 
> hope jemalloc solve most of the memory issues in Cpp side

in my computer's test, the memory performance well, let's focus on the next benchmark result

**Comment by xige-16** [comment]
may fix #16150

**Pull request merged**
