### PR TITLE
fix: Check resource when loading deltalogs

### PR DESCRIPTION
**Pull request by congqixia**
Related to #36887

`LoadDeltaLogs` API did not check memory usage. When system is under high delete load pressure, this could result into OOM quit.

This PR add resource check for `LoadDeltaLogs` actions and separate internal deltalog loading function with public one.

### CODE REVIEW

**Comment by congqixia** [comment]
rerun go-sdk

**Review by XuanYang-cn — APPROVED** [review]
/lgtm

**Pull request merged**
