### PR TITLE
Update mergify.yml for related issue

### LINKED ISSUE #6534: Require related issue in Pull Request
**Please state your issue using the following template and, most importantly, in English.**

**Describe the solution you'd like**
To make sure each PR link to an issue, otherwise blocking automatic merging.

### PR DESCRIPTION
**Pull request by jeffoverflow**
Signed-off-by: quicksilver <zhifeng.zhang@zilliz.com>

fixed: #6534

issue: #6534 

/cc @scsven

### CODE REVIEW

**Comment by scsven** [comment]
@jeffoverflow We don’t want users to use keywords that close Issue, so please make check in this rule. 
github close issue keyword: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

**Comment by jeffoverflow** [comment]
@scsven We can refer to Kubernetes contributing  best practices https://github.com/kubernetes/community/blob/master/contributors/guide/contributing.md#best-practices

**Comment by scsven** [comment]
> > @jeffoverflow We don’t want users to use keywords that close Issue, so please make check in this rule.
> > github close issue keyword: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue
> 
> @scsven
> I would like the contributor to close issue using this keyword.
> We can refer to Kubernetes contributing best practices https://github.com/kubernetes/community/blob/master/contributors/guide/contributing.md#best-practices

@jeffoverflow According to @xiaofan-luan demands yesterday

/assign @xiaofan-luan

**Pull request merged**
