### PR TITLE
Support return dropped segments info in GetSegmentInfo rpc

### PR DESCRIPTION
**Pull request by wayblink**
related #17607 
Signed-off-by: wayblink <anyang.wang@zilliz.com>

### CODE REVIEW

**Comment by xiaofan-luan** [comment]
@wayblink why is this segment dropped? what happened if it is cleaned up?

**Comment by wayblink** [comment]
> @wayblink why is this segment dropped? what happened if it is cleaned up?

Related to: https://github.com/milvus-io/milvus/issues/17607.  Currently GetSegmentInfo can only return healthy segments. In querycoord, we need dropped segment infos through GetSegmentInfo as we removed segmentInfo out of VchannelInfo. 

Dropped segments in meta may be cleaned up after compaction or drop. It supposed to have no impact on query because data operation should finish before meta operation. So we can just return nil if it is cleaned.

What do you think?

**Pull request merged**
