### PR TITLE
Fix bug for json_contains_all has multiple array elements

### PR DESCRIPTION
**Pull request by xiaocai2333**
issue: #26430

### CODE REVIEW

**Comment by xiaocai2333** [comment]
rerun ut

**Review by yah01 — COMMENTED** [review]
/lgtm

**Review by longjiquan — COMMENTED** [review]
/lgtm

**Review by longjiquan — COMMENTED** [review]
/lgtm

**Comment by czs007** [comment]
actually ci-e2e passed

**Pull request merged**
