### PR TITLE
enhance: speed up GetByCollection/AndNode (2.4 patch)

### PR DESCRIPTION
**Pull request by yiwangdr**
Related to https://github.com/milvus-io/milvus/issues/32165

Avoid iterating through all replicas/collections if possible. Iteration is expensive when there are large number of replicas/collections.

### CODE REVIEW

**Comment by xiaofan-luan** [comment]
please make static check on that before commit

**Comment by yiwangdr** [comment]
rerun ut

**Review by xiaofan-luan — COMMENTED** [review]
GetResourceGroupByCollection and GetByCollectionAndRG should also be optimized

**Comment by czs007** [comment]
@yiwangdr  please pick to master

**Pull request merged**
