### PR TITLE
Skip remove if reassigns to the original node

### PR DESCRIPTION
**Pull request by XuanYang-cn**
See also: #15966, #17432

Signed-off-by: yangxuan <xuan.yang@zilliz.com>

/kind improvement

### CODE REVIEW

**Comment by jennyli-z** [comment]
2c0e42f0-fa21-4df2-90ce-d001863dfb84
datanode for this pr , runs memory above 1G, much more than usual, probably better check if it is caused by the code change in this pr, or the latest master code. Thanks.

**Comment by XuanYang-cn** [comment]
> 2c0e42f0-fa21-4df2-90ce-d001863dfb84
> datanode for this pr , runs memory above 1G, much more than usual, probably better check if it is caused by the code change in this pr, or the latest master code. Thanks.

I've found and fixed the leak and this should no long exists

**Review by congqixia — APPROVED** [review]
/lgtm

**Pull request merged**
