### PR TITLE
enhance: check the auth in some rest v2 api

### PR DESCRIPTION
**Pull request by SimFG**
/kind improvement
link master proto: https://github.com/milvus-io/milvus-proto/blob/master/proto/milvus.proto

### CODE REVIEW

**Review by congqixia — APPROVED** [review]
/lgtm

**Comment by congqixia** [comment]
BTW, there are still some other API not checking authentication. Is that ok by now? @SimFG

**Comment by SimFG** [comment]
@congqixia it's ok, because some apis don't have the permission check. What has been added so far is mainly those that were missed.

**Pull request merged**
