### PR TITLE
Modify lastSyncTime in advance to prevent multiple flush binlogs

### PR DESCRIPTION
**Pull request by xiaocai2333**
Signed-off-by: cai.zhang <cai.zhang@zilliz.com>
issue: #22034

### CODE REVIEW

**Comment by xiaocai2333** [comment]
set `datanode.segment.syncPeriod` to 60. 
test with this pr:
test code:
```
def insert(coll, i=0, flush=False):
    vectors = [[random.random() for _ in range(128)]]
    data = []
    for _ in range(63):
        data.append([i])
    data.append(vectors)
    coll.insert(data)
    print(f"insert {i}")
    if flush:
        coll.flush()


if __name__ == "__main__":
    connections.connect(host="localhost", port=19530, Secure=True)
    coll = create_collection()
    i = 0
    while True:
        insert(coll, i, False)
        i += 1

```
image

**Comment by xiaofan-luan** [comment]
you need a ut on it

**Review by congqixia — APPROVED** [review]
/lgtm

**Pull request merged**
