### PR TITLE
Make DML failed if quota exceeds and remove autoindex config

### PR DESCRIPTION
**Pull request by bigsheeper**
Signed-off-by: bigsheeper <yihao.dai@zilliz.com>

issues: https://github.com/milvus-io/milvus/issues/18635

### CODE REVIEW

**Comment by czs007** [comment]
@soothing-rain  please take a look at datacoord/meta.go

**Comment by czs007** [comment]
@soothing-rain please take a look at datacoord/meta.go

**Comment by soothing-rain** [comment]
Note: this involves not only just bulk load but all `SaveBinlogPath` operations.

**Comment by bigsheeper** [comment]
> Note: this involves not only just bulk load but all `SaveBinlogPath` operations.

Yes, any dml operation would be failed if disk quota exceeds when `SaveBinlogPath`. I think it's reasonable.

**Pull request merged**
