### PR TITLE
fix: checkResultTicker leak

### PR DESCRIPTION
**Pull request by fengjun2016**
https://github.com/milvus-io/milvus/issues/35376

### CODE REVIEW

**Comment by jaime0815** [comment]
Hi @fengjun2016  Please rebase master to fix the integration test failures.

**Comment by fengjun2016** [comment]
> Hi @fengjun2016 Please rebase master to fix the integration test failures.

I just follow your instructions to rebase master, why remove the label lgtm

截屏2024-08-13 17 48 24

**Pull request merged**
