### PR TITLE
Load delete from channel checkpoint

### PR DESCRIPTION
**Pull request by bigsheeper**
/kind bug

related: https://github.com/milvus-io/milvus/issues/23959

### CODE REVIEW

**Comment by jiaoew1991** [comment]
related to  https://github.com/milvus-io/milvus/issues/23921

**Review by yah01 — APPROVED** [review]
/lgtm

**Review by yah01 — APPROVED** [review]
/lgtm

**Review by congqixia — APPROVED** [review]
/approve

**Pull request merged**
