### PR TITLE
fix: [cp][2.5] use max MvccTs for iterator

### PR DESCRIPTION
**Pull request by PwzXxm**
issue: #37158
pr: #37247

Signed-off-by: Patrick Weizhi Xu <weizhi.xu@zilliz.com>
(cherry picked from commit 5ed7230c53d07caf1c594381743cc90d78daa312)

### CODE REVIEW

**Comment by PwzXxm** [comment]
rerun go-sdk

**Comment by PwzXxm** [comment]
rerun go-sdk

**Comment by PwzXxm** [comment]
rerun go-sdk

**Comment by PwzXxm** [comment]
For exact MVCC view, we need to pass the channel-mvccTs back to SDK. Do it in later PR.

**Review by congqixia — APPROVED** [review]
lgtm as temp solution
/lgtm

**Pull request merged**
