### PR TITLE
enhance: [GoSDK] Add APIs for backup tool

### PR DESCRIPTION
**Pull request by congqixia**
Related to #31291

This PR:

- Add Backup&Restore RBAC APIs
- Add GetPersistentSegmentInfo API
- Add GetServerVersion API
- Add flush task stats

### CODE REVIEW

**Comment by congqixia** [comment]
rerun go-sdk

**Comment by congqixia** [comment]
rerun cpp-unit-test

**Comment by congqixia** [comment]
rerun go-sdk

**Comment by congqixia** [comment]
rerun cpp-unit-test

**Comment by congqixia** [comment]
rerun go-sdk

**Comment by congqixia** [comment]
rerun go-sdk

**Review by ThreadDao — COMMENTED** [review]
/lgtm

**Pull request merged**
