### PR TITLE
ft:GitHub Issue Form Added

### LINKED ISSUE #9017: Upgrade our issue templates to use GitHub issue forms
## Title
GitHub has recently rolled out a [public beta for their issue forms](https://github.blog/changelog/2021-06-23-issues-forms-beta-for-public-repositories/) feature. This would allow you to create interactive issue templates and validate them 🤯.

## Description
This repository currently uses the older issue template format. Your task is to create GitHub issue forms for this repository. We can use this repo's issue templates as a reference for this PR.

### PR DESCRIPTION
**Pull request by Hard-Coder05**
closes #9017

### CODE REVIEW

**Comment by Hard-Coder05** [comment]
> Hi @Hard-Coder05. Thanks for your contribution! Would you mind dividing this pull request into three? It will be helpful to reviewing and merging. And I will help you to complete these commits one by one. :)

Yeah sure! Let me know what the 3 PRs shall look like? And what do you expect?

**Comment by scsven** [comment]
> > Hi @Hard-Coder05. Thanks for your contribution! Would you mind dividing this pull request into three? It will be helpful to reviewing and merging. And I will help you to complete these commits one by one. :)
> 
> 
> 
> Yeah sure! Let me know what the 3 PRs shall look like? And what do you expect?

For three templates changes, each PR contains an old file removed and a new file created. I will check if each changes are correct.

**Pull request closed without merging**
