### PR TITLE
fix: Functional-notation casting vulnerability fix

### PR DESCRIPTION
**Pull request by abd-770**
Fix for issue: https://github.com/milvus-io/milvus/issues/35200

### CODE REVIEW

**Comment by abd-770** [comment]
@bigsheeper @czs007 Some checks are missing for this pr. Can you check what's causing this issue? Or anything else to be done from our side

**Comment by abd-770** [comment]
@zhagnlu I have force pushed the commit to re-run some of the scans that were skipped. Can you initiate the /lgtm to run the scans.

**Comment by abd-770** [comment]
rerun ut

**Comment by jaime0815** [comment]
hi @abd-770  please rebase the master branch to fix CI failures.

**Pull request merged**
