### PR TITLE
Fix code checker error

### PR DESCRIPTION
**Pull request by jiaoew1991**
/kind improvement

### CODE REVIEW

**Comment by yiwangdr** [comment]
Thanks for the quick fix. 

Could you also fix this error: 
`pkg/util/paramtable/service_param_test.go:79:3: not enough arguments in call to SParams.init`
the bt param is missing.

**Comment by jiaoew1991** [comment]
> service_param_test



> Thanks for the quick fix.
> 
> Could you also fix this error: `pkg/util/paramtable/service_param_test.go:79:3: not enough arguments in call to SParams.init` the bt param is missing.

I don't see this problem in the code 🤔

**Comment by yiwangdr** [comment]
> kg/util/paramtable/service_param_test.go

hmm. does `make static-check` generate any errors?

**Comment by yiwangdr** [comment]
> > service_param_test
> 
> > Thanks for the quick fix.
> > Could you also fix this error: `pkg/util/paramtable/service_param_test.go:79:3: not enough arguments in call to SParams.init` the bt param is missing.
> 
> I don't see this problem in the code 🤔

hmm. does make static-check generate any errors?

**Review by congqixia — APPROVED** [review]
/lgtm

**Pull request merged**
