### PR TITLE
[cherry-pick]Add CSV file import function

### PR DESCRIPTION
**Pull request by KumaJie**
issue: #27148

from pr: #27149

### CODE REVIEW

**Comment by yhmo** [comment]
rerun ut

**Comment by yhmo** [comment]
@KumaJie 
The "Mac Code Checker" could not pass because there is a dependency change in CI. Please fetch the latest code and rebase your branch and push again.

Steps:
1. git fetch xxx
2. git rebase -i xxx/2.3
3. git push -f origin 2.3

**Comment by KumaJie** [comment]
> @KumaJie The "Mac Code Checker" could not pass because there is a dependency change in CI. Please fetch the latest code and rebase your branch and push again.
> 
> Steps:
> 
> 1. git fetch xxx
> 2. git rebase -i xxx/2.3
> 3. git push -f origin 2.3

I read the "Mac Code Checker" logs. The failed reason is used csv `InputOffset` but it only support in go >= 1.19. I meet same issue in merge to master branch. 
Could I cherry-pick pr #28080 to this branch or upgrade "Mac Code Checker" go version to 1.19?

**Comment by yhmo** [comment]
Hi @KumaJie, I just submitted a pr to fix a bulkinsert bug: https://github.com/milvus-io/milvus/pull/28227
Your pr conflicts with my pr. After rebasing the latest code, you need to replace "SingleBlockSize" with "ReadBufferSize" in the csv_parser.go.

**Comment by KumaJie** [comment]
> Hi @KumaJie, I just submitted a pr to fix a bulkinsert bug: #28227 Your pr conflicts with my pr. After rebasing the latest code, you need to replace "SingleBlockSize" with "ReadBufferSize" in the csv_parser.go.

got it.

**Comment by yhmo** [comment]
> > @KumaJie The "Mac Code Checker" could not pass because there is a dependency change in CI. Please fetch the latest code and rebase your branch and push again.
> > Steps:
> > 
> > 1. git fetch xxx
> > 2. git rebase -i xxx/2.3
> > 3. git push -f origin 2.3
> 
> I read the "Mac Code Checker" logs. The failed reason is used csv `InputOffset` but it only support in go >= 1.19. I meet same issue in merge to master branch. Could I cherry-pick pr #28080 to this branch or upgrade "Mac Code Checker" go version to 1.19?

Yes, you can cherry-pick the #28080 to 2.3. 
Keep this pr 28161 pending until the 28080 is merged into 2.3.

**Pull request merged**
