### PR TITLE
Fix load hang when restart querynode many time in short time

### PR DESCRIPTION
**Pull request by xige-16**
Signed-off-by: xige-16 <xi.ge@zilliz.com>

may fix the issue #6098

### CODE REVIEW

**Comment by xiaofan-luan** [comment]
any unit test on this fix?

**Review by bigsheeper — APPROVED** [review]

**Comment by bigsheeper** [comment]
Fix #6443

**Comment by xige-16** [comment]
fix #6325

**Comment by xige-16** [comment]
> any unit test on this fix?

Test simulation node restart has been added, Please review again. @xiaofan-luan

**Pull request merged**
