### PR TITLE
Cherry pick 0.11.0 20200918

### PR DESCRIPTION
**Pull request by shengjun1985**
**What type of PR is this?**

- [ ] API-change
- [ ] BUG
- [ ] Improvement
- [ ] Documentation
- [ ] Feature
- [ ] Test and CI
- [ ] Code Refactoring
- [x]  cherry-pick

**Which issue(s) this PR fixes:**

Fixes #

**What this PR does / why we need it:**

cherry-pick from 0.11.0

**Special notes for your reviewer:**

Not Available

**Additional documentation (e.g. design docs, usage docs, etc.):**

Not Available
Source PR:
#3765 #3780 #3787 #3783 #3798 #3788 #3797 #3803

### CODE REVIEW

**Comment by sworddish** [comment]
Had this cherry pick been merged into 1.0 ? I don't find the changes in the 1.0 release. The bug fix "dead circle when merge failed (#3787) " is critical to the system stability due to our recent press test. @shengjun1985 @yhmo

**Comment by shengjun1985** [comment]
Now, these commits are in the branch "experimental".

**Comment by yhmo** [comment]
> Had this cherry pick been merged into 1.0 ? I don't find the changes in the 1.0 release. The bug fix "dead circle when merge failed (#3787) " is critical to the system stability due to our recent press test. @shengjun1985 @yhmo

Hi @sworddish 
There are log of difference of implementation of 1.0 and 0.11.0. The 0.11.0 use a while(true) circle to merge segments, so it could lead to dead circle when failed to merge. But in the v1.0, no such circle, so it should not have this bug. Did you encounter similar problem in v1.0?

**Comment by sworddish** [comment]
> > Had this cherry pick been merged into 1.0 ? I don't find the changes in the 1.0 release. The bug fix "dead circle when merge failed (#3787) " is critical to the system stability due to our recent press test. @shengjun1985 @yhmo
> 
> Hi @sworddish
> There are log of difference of implementation of 1.0 and 0.11.0. The 0.11.0 use a while(true) circle to merge segments, so it could lead to dead circle when failed to merge. But in the v1.0, no such circle, so it should not have this bug. Did you encounter similar problem in v1.0?

OK, seems not related to this bug, we will deep dive into our issues, thanks

**Pull request merged**
