### PR TITLE
Enable etcd auto compaction for every 1000 revision

### LINKED ISSUE #7277: Refine ci etcd memory usage
#### What would you like to be added:
Enable etcd auto compaction to reduce the memory growth rate and db size.
#### Why is this needed:
During the ci tests, the memory growth of etcd is very steep. 
image

And we also find several keys are modified very frequently, enabling auto compaction can remove old kv history rapidly.
image

### PR DESCRIPTION
**Pull request by LoveEachDay**
Enable etcd auto compaction to reduce the memory growth rate and db size.

Resolves: #7277 
Signed-off-by: Edward Zeng jie.zeng@zilliz.com

### CODE REVIEW

**Review by jeffoverflow — COMMENTED** [review]
/approve
/lgtm

**Comment by czs007** [comment]
/lgtm
/approve

@LoveEachDay 
It would be better to add the relevant configuration to the installation document so that external users can also modify the parameters.

**Comment by LoveEachDay** [comment]
@czs007 We'd refine the install documentation after we make the same changes to milvus-helm repo.

**Pull request merged**
