### PR TITLE
[skip e2e] Add comment for initSession

### PR DESCRIPTION
**Pull request by longjiquan**
Signed-off-by: dragondriver <jiquan.long@zilliz.com>
/kind improvement
/cc @czs007 @xiaofan-luan @scsven @congqixia @yanliang567

### CODE REVIEW

**Comment by congqixia** [comment]
@DragonDriver it should be skip e2e insteaf of skip ci

**Comment by DragonDriver** [comment]
> @DragonDriver it should be skip e2e insteaf of skip ci

OK, got it. Thanks for the corrections.

**Review by congqixia — APPROVED** [review]
/lgtm

**Pull request merged**
