### PR TITLE
Fix ut data race

### PR DESCRIPTION
**Pull request by longjiquan**
Signed-off-by: dragondriver <jiquan.long@zilliz.com>
issue: #16937

### CODE REVIEW

**Comment by longjiquan** [comment]
rerun ut

**Review by congqixia — COMMENTED** [review]
Hi @longjiquan , I don't think this will fix the data race issue. Since the tests do not run in parallel mode by default. The root issue here was that the server instance is read and write in  different goroutines.

**Comment by longjiquan** [comment]
rerun ut

**Pull request merged**
