### PR TITLE
Fix GetMemoryCount, get min as total memory

### LINKED ISSUE #15933: [Bug]: Wrong total memory when docker memory limit is not set
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

get an enormous total memory value (9223372036854771712) from GetMemoryCount when docker limit is not set

### Expected Behavior

get the right memory value

### Steps To Reproduce

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by bigsheeper**
Signed-off-by: bigsheeper <yihao.dai@zilliz.com>

resolves: #15933

### CODE REVIEW

**Comment by bigsheeper** [comment]
rerun ut

**Comment by xiaofan-luan** [comment]
did we test it under a docker environment?

**Comment by bigsheeper** [comment]
> did we test it under a docker environment?

not yet, I could make a test next week

**Comment by bigsheeper** [comment]
before:
Screenshot from 2022-03-24 17-53-53

after:
Screenshot from 2022-03-24 17-51-59

So as we can see, it works

**Pull request merged**
