### PR TITLE
Fix compile protocol buffer files error

### PR DESCRIPTION
**Pull request by BUPTAnderson**
Fix compile protocol buffer files error (#8045)

### CODE REVIEW

**Comment by BUPTAnderson** [comment]
> issue: #6534

issue: #8045

**Comment by BUPTAnderson** [comment]
@XuanYang-cn  Hi XuanYang, please review.

**Comment by BUPTAnderson** [comment]
@jeffoverflow  Hi jeffoverflow, please review.

**Comment by xiaofan-luan** [comment]
@BUPTAnderson Hi BUPT, please check the the DCO settings, you you don't know how to do it please check https://github.com/milvus-io/milvus/blob/master/CONTRIBUTING.md

**Pull request closed without merging**
