### PR TITLE
Remove extra colons when minio port is empty

### PR DESCRIPTION
**Pull request by zxh326**

### CODE REVIEW

**Comment by congqixia** [comment]
hi @zxh326 , thanks for the contribution. The DCO check fails. Could you please fix that?

**Comment by xiaofan-luan** [comment]
To learn more about DCO, see https://github.com/milvus-io/milvus/blob/master/CONTRIBUTING.md

**Comment by zxh326** [comment]
> To learn more about DCO, see https://github.com/milvus-io/milvus/blob/master/CONTRIBUTING.md

DCO already done. 

```
> https://github.com/krallin/tini/releases/download/v0.19.0/tini:
failed to load cache key: Get "https://objects.githubusercontent.com/github-production-release-asset...": net/http: TLS handshake timeout
---
```
It looks like network problem, need retest

**Comment by jennyli-z** [comment]
> 
`milvus/jenkins` &`continuous-integration/jenkins/pr-merge ` run the same e2e test, so passed one is enough. 
   currently, `ci-passed` label is not being added because of `codecov/patch`
middle_img_v2_9723e889-acb2-418a-b1bf-a08df77d2a7g

**Comment by zxh326** [comment]
> > 
> 
> `milvus/jenkins` &`continuous-integration/jenkins/pr-merge ` run the same e2e test, so passed one is enough. currently, `ci-passed` label is not being added because of `codecov/patch` middle_img_v2_9723e889-acb2-418a-b1bf-a08df77d2a7g

ok...will add some tests later.

**Comment by xiaofan-luan** [comment]
everything lgtm, all we need is a test case @zxh326

**Comment by xiaofan-luan** [comment]
@zxh326 hi my man, are you still working on this?

**Comment by zxh326** [comment]
> @zxh326 hi my man, are you still working on this?

Some test cases have been added and should now be waiting for review?

**Comment by xiaofan-luan** [comment]
I just reopen the issue and rerun test, thought there is no blocking issue on bringing in the issue

**Pull request closed without merging**
