### PR TITLE
Avoid allocating a zero-bytes vector each search time

### PR DESCRIPTION
**Pull request by yah01**
Signed-off-by: yah01 <yang.cen@zilliz.com>
/kind improvement
related #20765

### CODE REVIEW

**Comment by yah01** [comment]
Also, the branch which checks invalid segment offset may be removed, need to check how Knowhere produces it

**Comment by yah01** [comment]
rerun ut

**Comment by yah01** [comment]
rerun ut

**Comment by yah01** [comment]
rerun ut

**Comment by yah01** [comment]
rerun ut

**Review by jiaoew1991 — APPROVED** [review]
/lgtm

**Pull request merged**
