### PR TITLE
[skip e2e] Add dependency install script for embedded Milvus

### PR DESCRIPTION
**Pull request by soothing-rain**
issue: #15711

/kind enhancement

Signed-off-by: Yuchen Gao <yuchen.gao@zilliz.com>

### CODE REVIEW

**Comment by jennyli-z** [comment]
It looks similar with https://github.com/milvus-io/milvus/blob/master/scripts/install_deps.sh .
what's the main difference?

**Comment by soothing-rain** [comment]
> It looks similar with https://github.com/milvus-io/milvus/blob/master/scripts/install_deps.sh . what's the main difference?

This is used for embedded milvus. We added installing openblas and removed go & cmake install check.

**Review by congqixia — APPROVED** [review]
/lgtm

**Pull request merged**
