### PR TITLE
feat: [2.4]datacoord/node watch based on rpc

### PR DESCRIPTION
**Pull request by yiwangdr**
issue: https://github.com/milvus-io/milvus/issues/25309

### CODE REVIEW

**Comment by xiaofan-luan** [comment]
keep it open

**Comment by xiaofan-luan** [comment]
@yiwangdr 
please help on rebasing it and merge

**Comment by yiwangdr** [comment]
> @yiwangdr please help on rebasing it and merge

Sure. Is 2.4 branch still alive though? 
Could you help to merge master https://github.com/milvus-io/milvus/pull/32036?

**Comment by yiwangdr** [comment]
rerun ut

**Pull request merged**
