### PR TITLE
Stop loading stats after segment released

### PR DESCRIPTION
**Pull request by yah01**
/kind bug
fix https://github.com/milvus-io/milvus/issues/25011

### CODE REVIEW

**Comment by yah01** [comment]
rerun ut

**Comment by yah01** [comment]
rerun ut

**Comment by yah01** [comment]
TODO: as the segment has loaded the data, we could check whether primary key exists directly by the `InsertRecord`, a delete message would be delivered to a segment if all the conditions:
- Pass BF (if exists)
- Actually exists in the segment
Then we could avoid much performance downgrade due to many useless delete messages are delivered to the segment

**Comment by yah01** [comment]
rerun ut

**Comment by yah01** [comment]
rerun ut

**Comment by yah01** [comment]
rerun ut

**Comment by yah01** [comment]
rerun ut

**Comment by yah01** [comment]
rerun ut

**Comment by yah01** [comment]
rerun ut

**Comment by yah01** [comment]
rerun ut

**Comment by yah01** [comment]
rerun ut

**Review by congqixia — APPROVED** [review]
/lgtm

**Pull request merged**
