### PR TITLE
Fix DiskANN can't recovery after querynode reboots

### PR DESCRIPTION
**Pull request by yah01**
/kind bug
related #22460 
Also fix missing to throw exception when failed to remove dir

### CODE REVIEW

**Comment by jiaoew1991** [comment]
Could you add a UT or e2e test to cover this case?

**Comment by yah01** [comment]
> Could you add a UT or e2e test to cover this case?

e2e can't cover this because we can't to create such a dir, for now DiskANN unittest can't run due to we need to enable DiskANN with compile option "disk_index=ON"

**Comment by yah01** [comment]
rerun ut

**Review by jiaoew1991 — APPROVED** [review]
/lgtm

**Pull request merged**
