### PR TITLE
Implement integer bitwise "and", "or" and "xor" operator.

### LINKED ISSUE #24490: [Feature]: bitwise AND and OR operators in filter expression
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

We are going to use Milvus in our product. However, our product has document permission similar to Linux file permission.
We are going to use an integer to store the document permission in each bit within the document entity. And we want to use the bitwise operator to filter the permission against the user's.
 
Unfortunately, the bitwise operator is not available in Milvus now.

### Describe the solution you'd like.

I hope there are bitwise operators in filter expression like other modern expression systems.

### Describe an alternate solution.

If no such operator, we have to flatten the permission in multiple fields and use 'or' to check the permission. I can assume it hits the system query performance since the "or" operator is very difficult to optimize.

### Anything else? (Additional Context)

_No response_

### PR DESCRIPTION
**Pull request by topikachu**
Fix #24490
Add bitwise operator in pb definition.
Implement the operator in go and cpp modules.

### CODE REVIEW

**Comment by topikachu** [comment]
image

I've tested e2e locally and it's OK. Any idea?

**Comment by topikachu** [comment]
image
I run integration tests locally by './scripts/run_intergration_test.sh' without any error.
Any idea?

**Comment by xiaocai2333** [comment]
Great job!
you need to rebase to the latest commit.

**Comment by topikachu** [comment]
> Great job! you need to rebase to the latest commit.

The integration test on the master branch fails :(
image

Could somebody in milvus fix this?

**Comment by topikachu** [comment]
rerun ut

**Comment by xiaofan-luan** [comment]
UT Reruned

**Comment by xiaofan-luan** [comment]
/assign @xiaocai2333 
please help to review the code

**Comment by jiaoew1991** [comment]
Overall, there doesn't seem to be any problem. After running CI, it can be merged ！

**Comment by xiaocai2333** [comment]
@topikachu  you need to rebase to the latest commit. and it can be merged.

**Comment by xiaofan-luan** [comment]
sorry for the inconvenience, the code stack is moving very fast

**Comment by xiaofan-luan** [comment]
keep it

**Comment by xiaofan-luan** [comment]
@topikachu could you rebase with the latest master?
We can help on the UTs if there are still any issues

**Comment by xiaofan-luan** [comment]
@topikachu 
Hi Gongyi, would like a discussion on how we can make the pull request in?

**Pull request closed without merging**
