### PR TITLE
fix: fix cal_distance default implementation

### PR DESCRIPTION
**Pull request by chasingegg**
#31243

### CODE REVIEW

**Comment by xiaofan-luan** [comment]
@chasingegg 
will this has effect on 2.3?
if so please cherry pick to 2.3 branch as well.

**Comment by chasingegg** [comment]
> @chasingegg will this has effect on 2.3? if so please cherry pick to 2.3 branch as well.
This code is only at main branch.

**Review by congqixia — APPROVED** [review]
/lgtm

**Pull request merged**
