### PR TITLE
feat: Add an interface for aggregation functions

### PR DESCRIPTION
**Pull request by ashkrisk**
Issue: #37441

Right now this is a rough draft and not ready to be merged, but I would appreciate any and all feedback. In particular I would love to feedback on:
- The overall approach
- The organisation of the code - are there better places for me to intercept the query execution flow and introduce aggregation logic?

In the current approach, there are three components to each aggregation function:
- Proto file changes, for storing intermediate representations of the aggregates
- Implement the C++ interface for aggregation function
- Implement the Golang interface for the aggregation function

As an example, the `max` function is implemented through the aggregation interface.

Test cases still need to be added.

### CODE REVIEW

**Comment by ashkrisk** [comment]
Right now this is a rough draft and not ready to be merged, but I would appreciate any and all feedback. In particular I would love to feedback on:
- The overall approach
- The organisation of the code - are there better places for me to intercept the query execution flow and introduce aggregation logic?


In the current approach, there are three components to each aggregation function:
- Proto file changes, for storing intermediate representations of the aggregates
- Implement the C++ interface for aggregation function
- Implement the Golang interface for the aggregation function

As an example, the `max` function is implemented through the aggregation interface.

Test cases still need to be added.

**Comment by xiaofan-luan** [comment]
/assign @MrPresent-Han 
please help on it

**Comment by MrPresent-Han** [comment]
Hello, [ashkrisk](https://github.com/ashkrisk)
I'm working on aggregation for milvus, like the 'group by count(*)' in sql
Currently I'm developing cpp part and it's very happy to see your implement in the go-layer, which looks very constructive

**Comment by ashkrisk** [comment]
@MrPresent-Han does this mean that can take care of the C++ part entirely? In that case it would be very helpful if you could raise a draft PR, I can modify the Golang parts to match, would that work?

If it's too early for a draft PR, if you can give me a brief description of how you're planning to implement the C++ part that's fine as well. Thanks!

**Comment by xiaofan-luan** [comment]
maybe we can create a discord group on this discussion?
@yhmo 
can you help to do so

**Comment by MrPresent-Han** [comment]
> @MrPresent-Han does this mean that can take care of the C++ part entirely? In that case it would be very helpful if you could raise a draft PR, I can modify the Golang parts to match, would that work?
> 
> If it's too early for a draft PR, if you can give me a brief description of how you're planning to implement the C++ part that's fine as well. Thanks!

@ashkrisk
Sure, look forward to cooperate with you on this topic. I believe that your golang code can help us on this feature.
I will set up cpp part pr in the recent days, maybe we can communicate in the discord channel

**Comment by ashkrisk** [comment]
Looks like most of the content of this PR is already covered under https://github.com/milvus-io/milvus/pull/37536. @MrPresent-Han I'm happy to help if you need any assistance, but for now I'm closing this PR in favor of #37536.

**Pull request closed without merging**
