### PR TITLE
Handle distance Inf correctly

### PR DESCRIPTION
**Pull request by cydrain**
Issue: #21701
Signed-off-by: yudong.cai <yudong.cai@zilliz.com>

### CODE REVIEW

**Comment by cydrain** [comment]
rerun ut

**Comment by cydrain** [comment]
rerun ut

**Review by congqixia — APPROVED** [review]
lgtm 
@yanliang567 please check common_func change in test code

**Comment by yanliang567** [comment]
/lgtm
the test script part changes look good to me

**Pull request merged**
