### PR TITLE
enhance: no need database check in restful sdk

### PR DESCRIPTION
**Pull request by smellthemoon**
#38077 
remove the check for two reason
1. server will do the same to make sure use the correct database;
2. each req has an additional overhead of calling the proxy to check database.

### CODE REVIEW

**Comment by czs007** [comment]
pytest : test] [gw5] [ 37%] FAILED testcases/test_vector_operations.py::TestInsertVectorNegative::test_insert_vector_with_invalid_database_name 

[pytest : test] 

[pytest : test] =================================== FAILURES ===================================

[pytest : test] ____ TestInsertVectorNegative.test_insert_vector_with_invalid_database_name ____

[pytest : test] [gw5] linux -- Python 3.10.12 /usr/local/bin/python3

[pytest : test] [gw5] linux -- Python 3.10.12 /usr/local/bin/python3[gw5] linux -- Python 3.10.12 /usr/local/bin/python3

[pytest : test] 

[pytest : test] self = <test_vector_operations.TestInsertVectorNegative object at 0x7f3f03cd50c0>

[pytest : test] 

[pytest : test]     def test_insert_vector_with_invalid_database_name(self):

[pytest : test]         """

[pytest : test]         Insert a vector with an invalid database name

[pytest : test]         """

[pytest : test]         # create a collection

[pytest : test]         name = gen_collection_name()

[pytest : test]         dim = 128

[pytest : test]         payload = {

[pytest : test]             "collectionName": name,

[pytest : test]             "dimension": dim,

[pytest : test]         }

[pytest : test]         rsp = self.collection_client.collection_create(payload)

[pytest : test]         assert rsp['code'] == 0

[pytest : test]         rsp = self.collection_client.collection_describe(name)

[pytest : test]         assert rsp['code'] == 0

[pytest : test]         # insert data

[pytest : test]         nb = 10

[pytest : test]         data = get_data_by_payload(payload, nb)

[pytest : test]         payload = {

[pytest : test]             "collectionName": name,

[pytest : test]             "data": data,

[pytest : test]         }

[pytest : test]         body_size = sys.getsizeof(json.dumps(payload))

[pytest : test]         logger.info(f"body size: {body_size / 1024 / 1024} MB")

[pytest : test]         success = False

[pytest : test]         rsp = self.vector_client.vector_insert(payload, db_name="invalid_database")

[pytest : test] >       assert rsp['code'] == 800

[pytest : test] E       assert 100 == 800

[pytest : test] 

[pytest : test] testcases/test_vector_operations.py:829: AssertionError

**Comment by smellthemoon** [comment]
> pytest : test] [gw5] [ 37%] FAILED testcases/test_vector_operations.py::TestInsertVectorNegative::test_insert_vector_with_invalid_database_name
> 
> [pytest : test]
> 
> [pytest : test] =================================== FAILURES ===================================
> 
> [pytest : test] ____ TestInsertVectorNegative.test_insert_vector_with_invalid_database_name ____
> 
> [pytest : test] [gw5] linux -- Python 3.10.12 /usr/local/bin/python3
> 
> [pytest : test] [gw5] linux -- Python 3.10.12 /usr/local/bin/python3[gw5] linux -- Python 3.10.12 /usr/local/bin/python3
> 
> [pytest : test]
> 
> [pytest : test] self = <test_vector_operations.TestInsertVectorNegative object at 0x7f3f03cd50c0>
> 
> [pytest : test]
> 
> [pytest : test] def test_insert_vector_with_invalid_database_name(self):
> 
> [pytest : test] """
> 
> [pytest : test] Insert a vector with an invalid database name
> 
> [pytest : test] """
> 
> [pytest : test] # create a collection
> 
> [pytest : test] name = gen_collection_name()
> 
> [pytest : test] dim = 128
> 
> [pytest : test] payload = {
> 
> [pytest : test] "collectionName": name,
> 
> [pytest : test] "dimension": dim,
> 
> [pytest : test] }
> 
> [pytest : test] rsp = self.collection_client.collection_create(payload)
> 
> [pytest : test] assert rsp['code'] == 0
> 
> [pytest : test] rsp = self.collection_client.collection_describe(name)
> 
> [pytest : test] assert rsp['code'] == 0
> 
> [pytest : test] # insert data
> 
> [pytest : test] nb = 10
> 
> [pytest : test] data = get_data_by_payload(payload, nb)
> 
> [pytest : test] payload = {
> 
> [pytest : test] "collectionName": name,
> 
> [pytest : test] "data": data,
> 
> [pytest : test] }
> 
> [pytest : test] body_size = sys.getsizeof(json.dumps(payload))
> 
> [pytest : test] logger.info(f"body size: {body_size / 1024 / 1024} MB")
> 
> [pytest : test] success = False
> 
> [pytest : test] rsp = self.vector_client.vector_insert(payload, db_name="invalid_database")
> 
> [pytest : test] > assert rsp['code'] == 800
> 
> [pytest : test] E assert 100 == 800
> 
> [pytest : test]
> 
> [pytest : test] testcases/test_vector_operations.py:829: AssertionError

because in rootcoord, first see whether the collection exist and then see the db exist, has already change it logic in rootcoord.

**Comment by smellthemoon** [comment]
@czs007 But I am not sure whether I should change the code or the test case here, because the errors reported here are actually correct. The root cause is that, under a non-existent db, restful would report an error of db not exist, but pymilvus would report an error of collection not found.

**Comment by smellthemoon** [comment]
rerun go-sdk

**Pull request merged**
