### PR TITLE
Stop blocking until all channels & segments released (#25328)

### PR DESCRIPTION
**Pull request by yah01**
/kind improvement
Also fixed data race while stopping

### CODE REVIEW

**Comment by yah01** [comment]
rerun ut

**Comment by yah01** [comment]
rerun ut

**Comment by yah01** [comment]
rerun ut

**Comment by yah01** [comment]
rerun ut

**Comment by yah01** [comment]
rerun ut

**Review by congqixia — APPROVED** [review]
/lgtm

**Pull request merged**
