### PR TITLE
fix deadlock when loading segments

### PR DESCRIPTION
**Pull request by MrPresent-Han**
related: #25781

### CODE REVIEW

**Comment by yah01** [comment]
We need to check whether this slow down loading significantly

**Comment by MrPresent-Han** [comment]
> We need to check whether this slow down loading significantly

**Comment by yah01** [comment]
rerun ut

**Comment by MrPresent-Han** [comment]
sync_mode, 127segment, 2 replica, 8core per query node:
time_cost: 31.37s memory_size:21.7G

截屏2023-07-27 13 47 14

**Comment by MrPresent-Han** [comment]
rerun ut

**Comment by yah01** [comment]
rerun ut

**Comment by MrPresent-Han** [comment]
rerun ut

**Comment by congqixia** [comment]
rerun ut

**Comment by czs007** [comment]
Is it not good to forcibly change the underlying logic to serial here?

**Comment by yah01** [comment]
> Is it good to forcibly change the underlying logic to serial here?

Milvus loads segment concurrently in the field level, which means different fields are still been loading concurrently, even for the same segment.

For a collection with only a few fields (id, vec), this may significantly slows down the load performance, otherwises, it should work well.

I prefer to add one more thread pool, or it's time to introduce a coroutine lib for segcore

**Pull request closed without merging**
