### PR TITLE
Update hello_milvus.py

### PR DESCRIPTION
**Pull request by jjyaoao**
related to #23969
When I tried to run through tests/python_client/chaos/scripts/hello_milvus.py, I found that I would encounter the following error:
image
And the Demo cannot be executed repeatedly after one execution
image
This PR goes to try to fix this issue

### CODE REVIEW

**Comment by jiaoew1991** [comment]
@jjyaoao welcome! Thank you for you first PR

**Comment by jiaoew1991** [comment]
@jjyaoao  You should open an issue to describe this enhancement first, link this PR to the issue.

**Comment by jjyaoao** [comment]
> @jjyaoao You should open an issue to describe this enhancement first, link this PR to the issue.

Thanks for the reminder, I've tried open an issue at #23969

**Comment by xiaofan-luan** [comment]
@jjyaoao thanks for the contribution! should be able to merge

**Pull request merged**
