### PR TITLE
Add methods to compress/decompress small blocks

### PR DESCRIPTION
**Pull request by yah01**
Signed-off-by: yah01 <yang.cen@zilliz.com>
/kind improvement

### CODE REVIEW

**Comment by yah01** [comment]
rerun ut

**Comment by yah01** [comment]
> need more testcases to increase the coverage

It seems something wrong with the codecov... It reports many uncovered lines not in my patch, it happens to another PRs

**Review by congqixia — APPROVED** [review]
/lgtm

**Pull request merged**
