### PR TITLE
Merge syncCPLagTooBehind policy into syncPeriodically policy

### PR DESCRIPTION
**Pull request by bigsheeper**
/kind improvement

The *syncCPLagTooBehind* policy and the *syncPeriodically* policy exhibit similarities. By integrating *syncCPLagTooBehind* policy into *syncPeriodically* policy, the latter will initiate segment sync when the min buffer ts lags behind the current consumed ts by a duration exceeding the SyncPeriod (defaulted to 10 minutes).

### CODE REVIEW

**Comment by bigsheeper** [comment]
retun ut

**Comment by Bennu-Li** [comment]
retun ut

**Pull request merged**
