### PR TITLE
Replace error code with merr for RateLimiter

### PR DESCRIPTION
**Pull request by yah01**
/kind improvement

### CODE REVIEW

**Comment by bigsheeper** [comment]
Is pymilvus retry logical still work with merr?
img_v2_0cf5514c-d611-41a0-8a17-915520871c2g

**Comment by yah01** [comment]
> Is the retry logic of Pymilvus still working properly with merr? img_v2_0cf5514c-d611-41a0-8a17-915520871c2g

yes, this PR keep the `ErrorCode` be still `RateLimit`, additionally set the new `Code` field, see "merr/utils.go: 123"

**Pull request merged**
