### PR TITLE
Fix dataset's memory leak in knowWhere when search

### PR DESCRIPTION
**Pull request by xige-16**
fix issue: #7338 
Signed-off-by: xige-16 <xi.ge@zilliz.com>

### CODE REVIEW

**Review by op-hunter — APPROVED** [review]

**Review by wxyucs — APPROVED** [review]
/approve

**Comment by SuoSiFire** [comment]
@xige-16  @yhmo 
Excuse me，does this problem exist in the milvus v1.1.1 ?

**Pull request merged**
