### PR TITLE
Replaced nill with context

### LINKED ISSUE #10406: [Bug]: `nil` `context.Context` passed to function
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:
- Deployment mode(standalone or cluster):
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

`id, sampled, found = InfoFromContext(nil)`
`sp, ctx := StartSpanFromContext(nil)`
`sp, ctx = StartSpanFromContextWithOperationName(nil, "test")`

we should not pass a nil Context, even if a function permits it; pass context.TODO if you are unsure about which Context to use

### Expected Behavior

`sp, ctx := StartSpanFromContext(context.TODO())`
`sp, ctx = StartSpanFromContextWithOperationName(context.TODO(), "test")`
`id, sampled, found = InfoFromContext(context.TODO())`

### Steps To Reproduce

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by Biki-das**
fix #10406

### CODE REVIEW

**Comment by yhmo** [comment]
Seems the ut failure doesn't relate with code change. Wait to re-run the unittest.

**Comment by Biki-das** [comment]
> Seems the ut failure doesn't relate with code change. Wait to re-run the unittest.

ok

**Comment by Biki-das** [comment]
@yhmo i would like to be a collaborator for this project and help to maintain the repo

**Comment by godchen0212** [comment]
Hi @Biki-das, thanks for your positive contribution. I have checked this pull request and I will share some things with you. We already know that our code does not conform to the usual golang usage habits and does not conform to golangci-lint. But in this unittest case, the input parameter nil is an error injection. We hope that when the input parameter is nil, it will return related errors, which is in line with expectations. Thanks for your contributions again.

**Comment by Biki-das** [comment]
@godchen0212 yeah sure you can close it

**Comment by xiaofan-luan** [comment]
> @yhmo i would like to be a collaborator for this project and help to maintain the repo
 well
Hi Biki, I'm currently working on the flow for new coming maintainers/contributors， the detailed rules should go public in around 1-2 weeks. To become a commiter of milvus we would expect you contribute 1-2 big features and actively review other's contribution, to become an approver we would expect you to join the tech meeting in time, be familiar with most of the code in milvus so you can do the basic judge whether a patch is in valid ~ Keep contribution and approvers will recommend you once we think you are ready.

**Pull request closed without merging**
