### PR TITLE
fix balance generate reduce task

### LINKED ISSUE #22199: [Bug]: [ResourceGroup] Failed to get replicas info after transferring all nodes of the resource group
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master-20230214-68f146d5
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka): pulsar   
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus 2.3.0.dev34
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

1. deploy a cluster with 4 query nodes
2. create one RG named `RG_!` and transfer 2 query nodes from default_RG into the `RG_1`
3. load collection with 2 replicas into RG_1 and default_RG
4. transfer all (2) query nodes from RG_1 to default_RG
5. get replica info and return the error
```
pymilvus.exceptions.MilvusException: <MilvusException: (code=15, message=failed to get replica info, err=failed to get shard leader for shard collectionID:439465881914226722 channelName:"fouram-op-38-6366-rootcoord-dml_26_439465881914226722v0" seek_position:<channel_name:"fouram-op-38-6366-rootcoord-dml_26_439465881914226722v0" msgID:"\010\255\004\020\210\023\030\000 \000" msgGroup:"datanode-7-fouram-op-38-6366-rootcoord-dml_26_439465881914226722v0-true" timestamp:439472461476265985 > flushedSegmentIds:439465881916627910 flushedSegmentIds:439465881916227621 flushedSegmentIds:439465881916227576 dropped_segmentIds:439465881915227033 dropped_segmentIds:439465881916027388 dropped_segmentIds:439465881915227035 dropped_segmentIds:439465881914426734 dropped_segmentIds:439465881915827284 dropped_segmentIds:439465881914826883 , the collection not loaded or leader is offline[NodeNotFound(0)])>
```

### Expected Behavior

get replicas and return current replica info, included normal and abnormal replicas

### Steps To Reproduce

_No response_

### Milvus Log

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by weiliu1031**
Signed-off-by: Wei Liu <wei.liu@zilliz.com>
fix #22199 #22217 #22224 #22231 #22246

### CODE REVIEW

**Comment by weiliu1031** [comment]
rerun ut

**Comment by weiliu1031** [comment]
rerun ut

**Comment by weiliu1031** [comment]
rerun ut

**Review by congqixia — APPROVED** [review]
/lgtm

**Pull request merged**
