### PR TITLE
fix: add some check fieldata dim (#31564) 

### PR DESCRIPTION
**Pull request by bigsheeper**
issue: https://github.com/milvus-io/milvus/issues/30138
issue: https://github.com/milvus-io/milvus/issues/31724

pr: https://github.com/milvus-io/milvus/pull/31564

### CODE REVIEW

**Comment by bigsheeper** [comment]
rerun ut

**Comment by yanliang567** [comment]
rerun failed tests

**Comment by bigsheeper** [comment]
rerun ut

**Comment by czs007** [comment]
@bigsheeper race detected

**Pull request merged**
