### PR TITLE
enable auto balance paramter(#21504)

### PR DESCRIPTION
**Pull request by MrPresent-Han**
Signed-off-by: MrPresent-Han <chun.han@gmail.com>
issue: #21504

### CODE REVIEW

**Review by congqixia — APPROVED** [review]
/lgtm

**Comment by xiaofan-luan** [comment]
can we disable balance on collection level

**Comment by MrPresent-Han** [comment]
> can we disable balance on collection level

I think milvus need the ability to change this sort of parameters dynamically, which will be much more convenient

**Comment by xiaofan-luan** [comment]
> > can we disable balance on collection level
> 
> I think milvus need the ability to change this sort of parameters dynamically, which will be much more convenient

Yep, @jiaoew1991 already worked on that, should be able to release on 2.3

**Pull request merged**
