### PR TITLE
Fix gcp oauth token not cached

### PR DESCRIPTION
**Pull request by haorenfsa**
Signed-off-by: shaoyue.chen <shaoyue.chen@zilliz.com>
issue: #20043

### CODE REVIEW

**Review by congqixia — APPROVED** [review]
/lgtm

**Comment by congqixia** [comment]
Hi @haorenfsa , do we need to export this 2.2 branch?

**Comment by haorenfsa** [comment]
> Hi @haorenfsa , do we need to export this 2.2 branch?

Yes

**Pull request merged**
