### PR TITLE
fix: Fix load slowly

### PR DESCRIPTION
**Pull request by bigsheeper**
When there're a lot of loaded collections, they would occupy the target observer scheduler’s pool. This prevents loading collections from updating the current target in time, slowing down the load process.
This PR adds a separate target dispatcher for loading collections.

issue: https://github.com/milvus-io/milvus/issues/37166

### CODE REVIEW

**Comment by xiaofan-luan** [comment]
But there are several question to ask before we merge this pr:
1. how many collections do we have at that time? is it more than 10k?
2. we get 16 goroutines pull the target, how long does it pull the target? if it's 10 milliseconds each, then we can support 1600 collections, with 128 goroutines we are able to support more than 10k?
3. the random policy seems to be too complicated. simply do a shuffle 	
        rand.Seed(time.Now().UnixNano())
	rand.Shuffle(len(keys), func(i, j int) {
		keys[i], keys[j] = keys[j], keys[i]
	})

**Comment by xiaofan-luan** [comment]
with the shuffle, even if we can not the schedule in 10 seconds it won't matter. there is always a possibility it can be executed at some time.

The other thing we can do is at TargetObserver, we can introduce a version mechanism at datacoord. So if one collection meta has been updated (A new segment or channel) then the version is changed. Querycoord cached the meta so it doesn't need to fetch the same information again

**Comment by xiaofan-luan** [comment]
> with the shuffle, even if we can not the schedule in 10 seconds it won't matter. there is always a possibility it can be executed at some time.
> 
> The other thing we can do is at TargetObserver, we can introduce a version mechanism at datacoord. So if one collection meta has been updated (A new segment or channel) then the version is changed. Querycoord cached the meta so it doesn't need to fetch the same information again

most of the collection meta won't change in the next 10 seconds, which means we only need to fetch limited collections

**Comment by bigsheeper** [comment]
/unhold

I'll implement the version mechanism in the next pr

**Comment by bigsheeper** [comment]
related to: https://github.com/milvus-io/milvus/issues/37630

**Pull request merged**
