### PR TITLE
Use std::numeric_limits instead of MAXFLOAT to fix porting issue

### PR DESCRIPTION
**Pull request by cydrain**
Signed-off-by: yudong.cai <yudong.cai@zilliz.com>

### CODE REVIEW

**Comment by haorenfsa** [comment]
`LONG_MAX` in 64bit system is about `9.2e+18`,
while old `MAXFLOAT` in `math.h` is `3.40282347e+38F.`

while `FLT_MAX` is `3.402823466e+38F`, glibc uses `FLT_MAX` as `MAXFLOAT` as well in `values.h`

so maybe `FLT_MAX` is a better choice


FYI:

limits.h
```c++
/* Minimum and maximum values a `signed long int' can hold.  */
#  if __WORDSIZE == 64
#   define LONG_MAX     9223372036854775807L
#  else
#   define LONG_MAX     2147483647L
#  endif
```

math.h
```C++
# ifdef __USE_XOPEN
/* X/Open wants another strange constant.  */
#  define MAXFLOAT	3.40282347e+38F
# endif
```

float.h
```C++
#define FLT_MAX 3.402823466e+38F 
```

values.h
```C++
#include <float.h>

#define	MAXDOUBLE	DBL_MAX
#define	MAXFLOAT	FLT_MAX
```

**Comment by scsven** [comment]
https://en.cppreference.com/w/cpp/types/numeric_limits

**Pull request merged**
