### PR TITLE
Handle flowgraph releasing properly

### PR DESCRIPTION
**Pull request by XuanYang-cn**
See also: #15846

Signed-off-by: yangxuan <xuan.yang@zilliz.com>

/assign @congqixia 
/cc @congqixia

### CODE REVIEW

**Comment by XuanYang-cn** [comment]
rerun macos ut

**Comment by XuanYang-cn** [comment]
rerun macos check

**Comment by XuanYang-cn** [comment]
rerun ut

**Comment by XuanYang-cn** [comment]
rerun ut

**Review by congqixia — APPROVED** [review]
/lgtm

**Pull request merged**
