### PR TITLE
Fix LoadBalance doesn't save the modification to replicas' shards

### PR DESCRIPTION
**Pull request by yah01**
Signed-off-by: yah01 <yang.cen@zilliz.com>
#17053

### CODE REVIEW

**Comment by congqixia** [comment]
@yah01 there was some data race during unit test:
```
2022-05-18T04:21:06.8947622Z ==================
2022-05-18T04:21:06.8952287Z WARNING: DATA RACE[2022/05/18 04:21:06.893 +00:00] [DEBUG] [task.go:2358] ["LoadBalance: update shard leader"] [triggerTaskID=433284099753902088] [taskID=433284099753902090] [oldLeader=2] [newLeader=3]
2022-05-18T04:21:06.8953583Z 
2022-05-18T04:21:06.8957965Z Write at 0x00c0040c6158 by goroutine 623:
2022-05-18T04:21:06.8960884Z   github.com/milvus-io/milvus/internal/querycoord.(*queryNode).getNodeInfo()
2022-05-18T04:21:06.8962138Z       /go/src/github.com/milvus-io/milvus/internal/querycoord/querynode.go:434 +0x497
2022-05-18T04:21:06.8963357Z   github.com/milvus-io/milvus/internal/querycoord.(*queryNodeCluster).getNodeInfoByID()
2022-05-18T04:21:06.8964538Z       /go/src/github.com/milvus-io/milvus/internal/querycoord/cluster.go:604 +0x138
2022-05-18T04:21:06.8965748Z   github.com/milvus-io/milvus/internal/querycoord.(*loadBalanceTask).globalPostExecute.func3()
2022-05-18T04:21:06.8966936Z       /go/src/github.com/milvus-io/milvus/internal/querycoord/task.go:2336 +0x134
2022-05-18T04:21:06.8967692Z 
2022-05-18T04:21:06.8971624Z Previous write at 0x00c0040c6158 by goroutine 856:
2022-05-18T04:21:06.8973372Z   github.com/milvus-io/milvus/internal/querycoord.(*queryNode).getNodeInfo()
2022-05-18T04:21:06.8974184Z       /go/src/github.com/milvus-io/milvus/internal/querycoord/querynode.go:434 +0x497
2022-05-18T04:21:06.8975964Z   github.com/milvus-io/milvus/internal/querycoord.(*queryNodeCluster).getNodeInfoByID()
2022-05-18T04:21:06.8977149Z       /go/src/github.com/milvus-io/milvus/internal/querycoord/cluster.go:604 +0x138
2022-05-18T04:21:06.8978360Z   github.com/milvus-io/milvus/internal/querycoord.(*loadBalanceTask).globalPostExecute.func3()
2022-05-18T04:21:06.8979538Z       /go/src/github.com/milvus-io/milvus/internal/querycoord/task.go:2336 +0x134
2022-05-18T04:21:06.8980312Z 
2022-05-18T04:21:06.8981509Z Goroutine 623 (running) created at:
2022-05-18T04:21:06.8984845Z   github.com/milvus-io/milvus/internal/querycoord.(*loadBalanceTask).globalPostExecute()
2022-05-18T04:21:06.8985671Z       /go/src/github.com/milvus-io/milvus/internal/querycoord/task.go:2333 +0x27d
2022-05-18T04:21:06.8987317Z   github.com/milvus-io/milvus/internal/querycoord.(*TaskScheduler).scheduleLoop()
2022-05-18T04:21:06.8988495Z       /go/src/github.com/milvus-io/milvus/internal/querycoord/task_scheduler.go:690 +0x5a4
2022-05-18T04:21:06.8989515Z 
2022-05-18T04:21:06.8990716Z Goroutine 856 (running) created at:
2022-05-18T04:21:06.8994161Z   github.com/milvus-io/milvus/internal/querycoord.(*loadBalanceTask).globalPostExecute()
2022-05-18T04:21:06.8995377Z       /go/src/github.com/milvus-io/milvus/internal/querycoord/task.go:2333 +0x27d
2022-05-18T04:21:06.8996661Z   github.com/milvus-io/milvus/internal/querycoord.(*TaskScheduler).scheduleLoop()
2022-05-18T04:21:06.8997702Z       /go/src/github.com/milvus-io/milvus/internal/querycoord/task_scheduler.go:690 +0x5a4
2022-05-18T04:21:06.8998431Z ==================
2022-05-18T04:21:06.9001834Z ==================
2022-05-18T04:21:06.9006065Z WARNING: DATA RACE
2022-05-18T04:21:06.9009948Z Write at 0x00c0040c6140 by goroutine 623:
2022-05-18T04:21:06.9017823Z   github.com/milvus-io/milvus/internal/querycoord.(*queryNode).getNodeInfo()
2022-05-18T04:21:06.9019056Z       /go/src/github.com/milvus-io/milvus/internal/querycoord/querynode.go:435 +0x4f5
2022-05-18T04:21:06.9020293Z   github.com/milvus-io/milvus/internal/querycoord.(*queryNodeCluster).getNodeInfoByID()
2022-05-18T04:21:06.9021540Z       /go/src/github.com/milvus-io/milvus/internal/querycoord/cluster.go:604 +0x138
2022-05-18T04:21:06.9023270Z   github.com/milvus-io/milvus/internal/querycoord.(*loadBalanceTask).globalPostExecute.func3()
2022-05-18T04:21:06.9024063Z       /go/src/github.com/milvus-io/milvus/internal/querycoord/task.go:2336 +0x134
2022-05-18T04:21:06.9024940Z 
2022-05-18T04:21:06.9030081Z Previous write at 0x00c0040c6140 by goroutine 856:
2022-05-18T04:21:06.9031260Z   github.com/milvus-io/milvus/internal/querycoord.(*queryNode).getNodeInfo()
2022-05-18T04:21:06.9032004Z       /go/src/github.com/milvus-io/milvus/internal/querycoord/querynode.go:435 +0x4f5
2022-05-18T04:21:06.9035607Z   github.com/milvus-io/milvus/internal/querycoord.(*queryNodeCluster).getNodeInfoByID()
2022-05-18T04:21:06.9036261Z       /go/src/github.com/milvus-io/milvus/internal/querycoord/cluster.go:604 +0x138
2022-05-18T04:21:06.9036923Z   github.com/milvus-io/milvus/internal/querycoord.(*loadBalanceTask).globalPostExecute.func3()
2022-05-18T04:21:06.9037575Z       /go/src/github.com/milvus-io/milvus/internal/querycoord/task.go:2336 +0x134
2022-05-18T04:21:06.9038032Z 
2022-05-18T04:21:06.9038188Z Goroutine 623 (running) created at:
2022-05-18T04:21:06.9040990Z   github.com/milvus-io/milvus/internal/querycoord.(*loadBalanceTask).globalPostExecute()
2022-05-18T04:21:06.9041630Z       /go/src/github.com/milvus-io/milvus/internal/querycoord/task.go:2333 +0x27d
2022-05-18T04:21:06.9042426Z   github.com/milvus-io/milvus/internal/querycoord.(*TaskScheduler).scheduleLoop()
2022-05-18T04:21:06.9043616Z       /go/src/github.com/milvus-io/milvus/internal/querycoord/task_scheduler.go:690 +0x5a4
2022-05-18T04:21:06.9043915Z 
2022-05-18T04:21:06.9044065Z Goroutine 856 (running) created at:
2022-05-18T04:21:06.9044774Z   github.com/milvus-io/milvus/internal/querycoord.(*loadBalanceTask).globalPostExecute()
2022-05-18T04:21:06.9045567Z       /go/src/github.com/milvus-io/milvus/internal/querycoord/task.go:2333 +0x27d
2022-05-18T04:21:06.9046195Z   github.com/milvus-io/milvus/internal/querycoord.(*TaskScheduler).scheduleLoop()
2022-05-18T04:21:06.9046818Z       /go/src/github.com/milvus-io/milvus/internal/querycoord/task_scheduler.go:690 +0x5a4
2022-05-18T04:21:06.9047191Z ==================
2022-05-18T04:21:06.9048087Z ==================
2022-05-18T04:21:06.9048362Z WARNING: DATA RACE
2022-05-18T04:21:06.9048803Z Write at 0x00c0040c6148 by goroutine 623:
2022-05-18T04:21:06.9049363Z   github.com/milvus-io/milvus/internal/querycoord.(*queryNode).getNodeInfo()
2022-05-18T04:21:06.9050338Z       /go/src/github.com/milvus-io/milvus/internal/querycoord/querynode.go:436 +0x54f
2022-05-18T04:21:06.9050967Z   github.com/milvus-io/milvus/internal/querycoord.(*queryNodeCluster).getNodeInfoByID()
2022-05-18T04:21:06.9051593Z       /go/src/github.com/milvus-io/milvus/internal/querycoord/cluster.go:604 +0x138
2022-05-18T04:21:06.9052384Z   github.com/milvus-io/milvus/internal/querycoord.(*loadBalanceTask).globalPostExecute.func3()
2022-05-18T04:21:06.9053405Z       /go/src/github.com/milvus-io/milvus/internal/querycoord/task.go:2336 +0x134
2022-05-18T04:21:06.9053673Z 
2022-05-18T04:21:06.9053854Z Previous write at 0x00c0040c6148 by goroutine 856:
2022-05-18T04:21:06.9054396Z   github.com/milvus-io/milvus/internal/querycoord.(*queryNode).getNodeInfo()
2022-05-18T04:21:06.9055006Z       /go/src/github.com/milvus-io/milvus/internal/querycoord/querynode.go:436 +0x54f
2022-05-18T04:21:06.9056493Z   github.com/milvus-io/milvus/internal/querycoord.(*queryNodeCluster).getNodeInfoByID()
2022-05-18T04:21:06.9057508Z       /go/src/github.com/milvus-io/milvus/internal/querycoord/cluster.go:604 +0x138
2022-05-18T04:21:06.9058165Z   github.com/milvus-io/milvus/internal/querycoord.(*loadBalanceTask).globalPostExecute.func3()
2022-05-18T04:21:06.9058965Z       /go/src/github.com/milvus-io/milvus/internal/querycoord/task.go:2336 +0x134
2022-05-18T04:21:06.9059232Z 
2022-05-18T04:21:06.9059523Z Goroutine 623 (running) created at:
2022-05-18T04:21:06.9060121Z   github.com/milvus-io/milvus/internal/querycoord.(*loadBalanceTask).globalPostExecute()
2022-05-18T04:21:06.9060737Z       /go/src/github.com/milvus-io/milvus/internal/querycoord/task.go:2333 +0x27d
2022-05-18T04:21:06.9061333Z   github.com/milvus-io/milvus/internal/querycoord.(*TaskScheduler).scheduleLoop()
2022-05-18T04:21:06.9062075Z       /go/src/github.com/milvus-io/milvus/internal/querycoord/task_scheduler.go:690 +0x5a4
2022-05-18T04:21:06.9062362Z 
2022-05-18T04:21:06.9062655Z Goroutine 856 (running) created at:
2022-05-18T04:21:06.9063392Z   github.com/milvus-io/milvus/internal/querycoord.(*loadBalanceTask).globalPostExecute()
2022-05-18T04:21:06.9064030Z       /go/src/github.com/milvus-io/milvus/internal/querycoord/task.go:2333 +0x27d
2022-05-18T04:21:06.9064629Z   github.com/milvus-io/milvus/internal/querycoord.(*TaskScheduler).scheduleLoop()
2022-05-18T04:21:06.9065247Z       /go/src/github.com/milvus-io/milvus/internal/querycoord/task_scheduler.go:690 +0x5a4
2022-05-18T04:21:06.9065622Z ==================
2022-05-18T04:21:06.9066352Z ==================
2022-05-18T04:21:06.9066618Z WARNING: DATA RACE
2022-05-18T04:21:06.9066927Z Write at 0x00c0040c6150 by goroutine 623:
2022-05-18T04:21:06.9077910Z   github.com/milvus-io/milvus/internal/querycoord.(*queryNode).getNodeInfo()
2022-05-18T04:21:06.9078652Z       /go/src/github.com/milvus-io/milvus/internal/querycoord/querynode.go:437 +0x5ee
2022-05-18T04:21:06.9079299Z   github.com/milvus-io/milvus/internal/querycoord.(*queryNodeCluster).getNodeInfoByID()
2022-05-18T04:21:06.9079928Z       /go/src/github.com/milvus-io/milvus/internal/querycoord/cluster.go:604 +0x138
2022-05-18T04:21:06.9080578Z   github.com/milvus-io/milvus/internal/querycoord.(*loadBalanceTask).globalPostExecute.func3()
2022-05-18T04:21:06.9081223Z       /go/src/github.com/milvus-io/milvus/internal/querycoord/task.go:2336 +0x134
2022-05-18T04:21:06.9081495Z 
2022-05-18T04:21:06.9081677Z Previous write at 0x00c0040c6150 by goroutine 856:
2022-05-18T04:21:06.9082219Z   github.com/milvus-io/milvus/internal/querycoord.(*queryNode).getNodeInfo()
2022-05-18T04:21:06.9082825Z       /go/src/github.com/milvus-io/milvus/internal/querycoord/querynode.go:437 +0x5ee
2022-05-18T04:21:06.9083451Z   github.com/milvus-io/milvus/internal/querycoord.(*queryNodeCluster).getNodeInfoByID()
2022-05-18T04:21:06.9084077Z       /go/src/github.com/milvus-io/milvus/internal/querycoord/cluster.go:604 +0x138
2022-05-18T04:21:06.9084726Z   github.com/milvus-io/milvus/internal/querycoord.(*loadBalanceTask).globalPostExecute.func3()
2022-05-18T04:21:06.9085361Z       /go/src/github.com/milvus-io/milvus/internal/querycoord/task.go:2336 +0x134
2022-05-18T04:21:06.9085853Z 
2022-05-18T04:21:06.9086187Z Goroutine 623 (running) created at:
2022-05-18T04:21:06.9086750Z   github.com/milvus-io/milvus/internal/querycoord.(*loadBalanceTask).globalPostExecute()
2022-05-18T04:21:06.9087359Z       /go/src/github.com/milvus-io/milvus/internal/querycoord/task.go:2333 +0x27d
2022-05-18T04:21:06.9088280Z   github.com/milvus-io/milvus/internal/querycoord.(*TaskScheduler).scheduleLoop()
2022-05-18T04:21:06.9089004Z       /go/src/github.com/milvus-io/milvus/internal/querycoord/task_scheduler.go:690 +0x5a4
2022-05-18T04:21:06.9089379Z 
2022-05-18T04:21:06.9089632Z Goroutine 856 (running) created at:
2022-05-18T04:21:06.9090188Z   github.com/milvus-io/milvus/internal/querycoord.(*loadBalanceTask).globalPostExecute()
2022-05-18T04:21:06.9090898Z       /go/src/github.com/milvus-io/milvus/internal/querycoord/task.go:2333 +0x27d
2022-05-18T04:21:06.9091586Z   github.com/milvus-io/milvus/internal/querycoord.(*TaskScheduler).scheduleLoop()
2022-05-18T04:21:06.9092301Z       /go/src/github.com/milvus-io/milvus/internal/querycoord/task_scheduler.go:690 +0x5a4
2022-05-18T04:21:06.9092761Z ==================
```

**Comment by yah01** [comment]
rerun ut

**Review by congqixia — APPROVED** [review]
/lgtm

**Pull request merged**
