### PR TITLE
enhance: Delete all metrics after the nodes stop

### PR DESCRIPTION
**Pull request by bigsheeper**
1. Delete all metrics after the nodes stop
2. Delete limiter rate metrics when collection dropped

issue: https://github.com/milvus-io/milvus/issues/32063, https://github.com/milvus-io/milvus/issues/32062

### CODE REVIEW

**Review by LoveEachDay — APPROVED** [review]
/lgtm

**Comment by bigsheeper** [comment]
rerun ut

**Comment by bigsheeper** [comment]
rerun ut

**Pull request closed without merging**
