### PR TITLE
Update demo link in README

### PR DESCRIPTION
**Pull request by wh201906**
Signed-off-by: wh201906 <wh201906@yandex.com>
Issue #15578
The old website https://zilliz.com/milvus-demos is unused now.
Change it to https://milvus.io/milvus-demos/

### CODE REVIEW

**Comment by xiaofan-luan** [comment]
@wh201906 good catch. Please submit with DCO. see the contributing guide https://github.com/milvus-io/milvus/blob/master/CONTRIBUTING.md

**Comment by xiaofan-luan** [comment]
the commit message style should be 
fix xxxx or related to xxxx
signedoff by xxx

**Comment by wh201906** [comment]
@xiaofan-luan Hello. Is the commit message style correct now?

**Pull request merged**
