### PR TITLE
Fix mem leak of flush cache in DataNode

### LINKED ISSUE #6858: Memory leak in flush cache of DataNode
The Cache struct lacks a remove function, classic mem leak scenario.

As DataNode keeps running, there will be more and more segmentID in the `Cache` struct, so we have to add a `Remove` function in `Cache`, and when the segment done flushing , this segmentID will be removed from the `Cache`

### PR DESCRIPTION
**Pull request by XuanYang-cn**
Resolves: #6858

Signed-off-by: yangxuan <xuan.yang@zilliz.com>

### CODE REVIEW

**Review by sunby — APPROVED** [review]

**Comment by XuanYang-cn** [comment]
> Maybe we can describe this issue in more detail.

Done

**Pull request merged**
