### PR TITLE
feat: record the number of times milvus turns into force-deny-writing states

### LINKED ISSUE #34961: [Enhancement]: record the number of times milvus turns into force-deny-writing states
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

I want to add a metric to record the number of times milvus turns into force-deny-writing states.

### Why is this needed?

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by longjiquan**
/kind improvement
fix: #34961

### CODE REVIEW

**Comment by bigsheeper** [comment]
Remove `RootCoordQuotaStates`?

**Comment by longjiquan** [comment]
> Remove `RootCoordQuotaStates`?

This metric is widely used in the dashboard now.

**Review by LoveEachDay — APPROVED** [review]
/lgtm

**Pull request merged**
