### PR TITLE
enhance: add metrics for restful apis

### PR DESCRIPTION
**Pull request by PowderLi**
issue: #34968

### CODE REVIEW

**Review by Yherealtita — COMMENTED** [review]
module.exports = {
  "settings": {
    // overriding the default, false, for local testing
    "enableInteropTests": true,
    "testAllImplementations": true
  },
  "implementations": [{
    "name": "My Company",
    "implementation": "My Implementation Name",
    "issuers": [{
      "id": "urn:uuid:my:implementation:issuer:id",
      "endpoint": "https://localhost:40443/issuers/foo/credentials/issue",
      "tags": ["eddsa-rdfc-2022"]
    }],
    "verifiers": [{
      "id": "https://localhost:40443/verifiers/z19uokPn3b1Z4XDbQSHo7VhFR",
      "endpoint": "https://localhost:40443/verifiers/z19uokPn3b1Z4XDbQSHo7VhFR/credentials/verify",
      "tags": ["eddsa-rdfc-2022"]
    }]
  }, {
    // Add additional implementations as needed
  }];

**Comment by congqixia** [comment]
@PowderLi could you please cherry pick this pr to 2.4 branch? the restful metrics is needed for next release

**Review by Yherealtita — COMMENTED** [review]
-

**Pull request merged**
