### PR TITLE
Set max read concurrency ratio to improve concurrent read performance [cherry-pick #18911]

### PR DESCRIPTION
**Pull request by bigsheeper**
Signed-off-by: bigsheeper <yihao.dai@zilliz.com>

issues: https://github.com/milvus-io/milvus/issues/18910

### CODE REVIEW

**Comment by bigsheeper** [comment]
rerun ut

**Comment by jennyli-z** [comment]
rerun ut

**Comment by jennyli-z** [comment]
rerun ut

**Pull request merged**
