### PR TITLE
fix: mvcc database space exceeded for embed etcd

### LINKED ISSUE #30314: [Bug]: [one pod standalone]when Milvus recovers from pod kill chaos, most of its interfaces are not available
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:master-20240126-7ced0af1-amd64
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

1. all search/query failed:`collection not loaded`
2. flush all failed:
```

[2024-01-26T07:50:39.687Z] <name>: Hello_Milvus

[2024-01-26T07:50:39.687Z] <description>: 

[2024-01-26T07:50:39.687Z] <schema>: {'auto_id': False, 'description': '', 'fields': [{'name': 'int64', 'description': '', 'type': <DataType.INT64: 5>, 'is_primary': True, 'auto_id': False}, {'name': 'float', 'description': '', 'type': <DataType.FLOAT: 10>}, {'n......  (api_request.py:37)

[2024-01-26T07:50:39.687Z] [2024-01-26 07:47:32 - DEBUG - ci_test]: (api_request)  : [Collection.flush] args: [], kwargs: {'timeout': 180} (api_request.py:62)

[2024-01-26T07:50:39.687Z] [2024-01-26 07:50:32 - ERROR - pymilvus.decorators]: RPC error: [flush], <MilvusException: (code=500, message=channel not found[channel=by-dev-rootcoord-dml_2_447284044378545664v0])>, <Time:{'RPC start': '2024-01-26 07:47:32.703287', 'RPC error': '2024-01-26 07:50:32.649750'}> (decorators.py:134)

[2024-01-26T07:50:39.687Z] [2024-01-26 07:50:32 - ERROR - ci_test]: Traceback (most recent call last):

[2024-01-26T07:50:39.687Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 32, in inner_wrapper

[2024-01-26T07:50:39.688Z]     res = func(*args, **_kwargs)

[2024-01-26T07:50:39.688Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 63, in api_request

[2024-01-26T07:50:39.688Z]     return func(*arg, **kwargs)

[2024-01-26T07:50:39.688Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 314, in flush

[2024-01-26T07:50:39.688Z]     conn.flush([self.name], timeout=timeout, **kwargs)

[2024-01-26T07:50:39.688Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 135, in handler

[2024-01-26T07:50:39.688Z]     raise e from e

[2024-01-26T07:50:39.688Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 131, in handler

[2024-01-26T07:50:39.688Z]     return func(*args, **kwargs)

[2024-01-26T07:50:39.688Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 170, in handler

[2024-01-26T07:50:39.688Z]     return func(self, *args, **kwargs)

[2024-01-26T07:50:39.688Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 110, in handler

[2024-01-26T07:50:39.688Z]     raise e from e

[2024-01-26T07:50:39.688Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 74, in handler

[2024-01-26T07:50:39.688Z]     return func(*args, **kwargs)

[2024-01-26T07:50:39.688Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 1335, in flush

[2024-01-26T07:50:39.688Z]     check_status(response.status)

[2024-01-26T07:50:39.688Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/utils.py", line 58, in check_status

[2024-01-26T07:50:39.688Z]     raise MilvusException(status.code, status.reason, status.error_code)

[2024-01-26T07:50:39.688Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=500, message=channel not found[channel=by-dev-rootcoord-dml_2_447284044378545664v0])>

[2024-01-26T07:50:39.688Z]  (api_request.py:45)
```
```

[2024-01-26T07:53:36.970Z] <name>: QueryChecker__q3nvggGS

[2024-01-26T07:53:36.970Z] <description>: 

[2024-01-26T07:53:36.970Z] <schema>: {'auto_id': False, 'description': '', 'fields': [{'name': 'int64', 'description': '', 'type': <DataType.INT64: 5>, 'is_primary': True, 'auto_id': False}, {'name': 'float', 'description': '', 'type': <DataType.FLOAT:......  (api_request.py:37)

[2024-01-26T07:53:36.970Z] [2024-01-26 07:44:54 - DEBUG - ci_test]: (api_request)  : [Collection.flush] args: [], kwargs: {'timeout': 180} (api_request.py:62)

[2024-01-26T07:53:36.971Z] [2024-01-26 07:47:32 - ERROR - pymilvus.decorators]: RPC error: [flush], <MilvusException: (code=65535, message=failed to flush collection 447284044378546654: etcdserver: mvcc: database space exceeded)>, <Time:{'RPC start': '2024-01-26 07:44:54.643498', 'RPC error': '2024-01-26 07:47:32.568409'}> (decorators.py:134)

[2024-01-26T07:53:36.971Z] [2024-01-26 07:47:32 - ERROR - ci_test]: Traceback (most recent call last):

[2024-01-26T07:53:36.971Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 32, in inner_wrapper

[2024-01-26T07:53:36.971Z]     res = func(*args, **_kwargs)

[2024-01-26T07:53:36.971Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 63, in api_request

[2024-01-26T07:53:36.971Z]     return func(*arg, **kwargs)

[2024-01-26T07:53:36.971Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 314, in flush

[2024-01-26T07:53:36.971Z]     conn.flush([self.name], timeout=timeout, **kwargs)

[2024-01-26T07:53:36.971Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 135, in handler

[2024-01-26T07:53:36.971Z]     raise e from e

[2024-01-26T07:53:36.971Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 131, in handler

[2024-01-26T07:53:36.971Z]     return func(*args, **kwargs)

[2024-01-26T07:53:36.971Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 170, in handler

[2024-01-26T07:53:36.971Z]     return func(self, *args, **kwargs)

[2024-01-26T07:53:36.971Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 110, in handler

[2024-01-26T07:53:36.971Z]     raise e from e

[2024-01-26T07:53:36.971Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 74, in handler

[2024-01-26T07:53:36.971Z]     return func(*args, **kwargs)

[2024-01-26T07:53:36.971Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 1335, in flush

[2024-01-26T07:53:36.971Z]     check_status(response.status)

[2024-01-26T07:53:36.971Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/utils.py", line 58, in check_status

[2024-01-26T07:53:36.971Z]     raise MilvusException(status.code, status.reason, status.error_code)

[2024-01-26T07:53:36.971Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=65535, message=failed to flush collection 447284044378546654: etcdserver: mvcc: database space exceeded)>

[2024-01-26T07:53:36.971Z]  (api_request.py:45)
```

3. create new collections failed:
```
[2024-01-26T07:44:41.455Z] [2024-01-26 07:44:41 - DEBUG - ci_test]: (api_request)  : [Collection] args: ['e2e__6Q9S3j7j', {'auto_id': False, 'description': '', 'fields': [{'name': 'int64', 'description': '', 'type': <DataType.INT64: 5>, 'is_primary': True, 'auto_id': False}, {'name': 'float', 'description': '', 'type': <DataType.FLOAT: 10>}, {'name': 'varchar', 'description': '', 'type': <DataType.VAR......, kwargs: {'consistency_level': 'Strong'} (api_request.py:62)

[2024-01-26T07:44:41.455Z] [2024-01-26 07:44:41 - ERROR - pymilvus.decorators]: RPC error: [create_collection], <MilvusException: (code=65535, message=etcdserver: mvcc: database space exceeded)>, <Time:{'RPC start': '2024-01-26 07:44:41.083880', 'RPC error': '2024-01-26 07:44:41.086827'}> (decorators.py:134)

[2024-01-26T07:44:41.455Z] [2024-01-26 07:44:41 - ERROR - ci_test]: Traceback (most recent call last):

[2024-01-26T07:44:41.455Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 32, in inner_wrapper

[2024-01-26T07:44:41.455Z]     res = func(*args, **_kwargs)

[2024-01-26T07:44:41.455Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 63, in api_request

[2024-01-26T07:44:41.455Z]     return func(*arg, **kwargs)

[2024-01-26T07:44:41.455Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/orm/collection.py", line 147, in __init__

[2024-01-26T07:44:41.455Z]     conn.create_collection(self._name, schema, **kwargs)

[2024-01-26T07:44:41.455Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 135, in handler

[2024-01-26T07:44:41.455Z]     raise e from e

[2024-01-26T07:44:41.455Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 131, in handler

[2024-01-26T07:44:41.455Z]     return func(*args, **kwargs)

[2024-01-26T07:44:41.455Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 170, in handler

[2024-01-26T07:44:41.455Z]     return func(self, *args, **kwargs)

[2024-01-26T07:44:41.455Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 110, in handler

[2024-01-26T07:44:41.455Z]     raise e from e

[2024-01-26T07:44:41.455Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/decorators.py", line 74, in handler

[2024-01-26T07:44:41.455Z]     return func(*args, **kwargs)

[2024-01-26T07:44:41.455Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/grpc_handler.py", line 304, in create_collection

[2024-01-26T07:44:41.455Z]     check_status(status)

[2024-01-26T07:44:41.455Z]   File "/usr/local/lib/python3.8/dist-packages/pymilvus/client/utils.py", line 58, in check_status

[2024-01-26T07:44:41.455Z]     raise MilvusException(status.code, status.reason, status.error_code)

[2024-01-26T07:44:41.455Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=65535, message=etcdserver: mvcc: database space exceeded)>

[2024-01-26T07:44:41.455Z]  (api_request.py:45)

[2024-01-26T07:44:41.455Z] [2024-01-26 07:44:41 - ERROR - ci_test]: (api_response) : <MilvusException: (code=65535, message=etcdserver: mvcc: database space exceeded)> (api_request.py:46)
```

### Expected Behavior

_No response_

### Steps To Reproduce

_No response_

### Milvus Log

failed job:https://qa-jenkins.milvus.io/blue/organizations/jenkins/chaos-test-cron/detail/chaos-test-cron/10981/pipeline

log:
[artifacts-one-pod-standalone-pod-kill-10981-server-logs.tar.gz](https://github.com/milvus-io/milvus/files/14061831/artifacts-one-pod-standalone-pod-kill-10981-server-logs.tar.gz)

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by LoveEachDay**
Fix #30314

### CODE REVIEW

**Comment by xiaofan-luan** [comment]
@LoveEachDay 
is their a reason to hold this pr?

**Comment by LoveEachDay** [comment]
> @LoveEachDay is their a reason to hold this pr?

@xiaofan-luan  The deployment had been failed. 
image
And our cpu-e2e-test won't take embedded milvus tests failure into account.

**Pull request merged**
