### PR TITLE
enhance: Maintain collection-patitions mapping in qc meta

### PR DESCRIPTION
**Pull request by congqixia**
Related to #32165

Add collection to partitionIDs mapping to avoid interation on all partitions loaded when trying to get all partitions with collection id

### CODE REVIEW

**Comment by yiwangdr** [comment]
Thanks for the fix. Could you apply the fix to this similar issue as well:
https://github.com/milvus-io/milvus/blob/674991d07c53d507cb9609672a1dd5801ef2524f/internal/querycoordv2/meta/replica_manager.go#L240C26-L251

**Comment by yiwangdr** [comment]
In the long term, we probably need to wrap collections, partitions and collectionPartitions into one struct for better maintenance, as potentially there is a data consistency issue.
For now it lgtm.

**Comment by congqixia** [comment]
> In the long term, we probably need to wrap collections, partitions and collectionPartitions into one struct for better maintenance, as potentially there is a data consistency issue. For now it lgtm.

@yiwangdr
Agree! One thing we need to keep in mind is that Milvus allows both `LoadCollection` & `LoadPartitions`. The design here need to support both operation and backward meta compatibility.

**Pull request merged**
