### PR TITLE
Support query return vector output field

### LINKED ISSUE #6299: Support query vector field
**Please state your issue using the following template and, most importantly, in English.**

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. E.g. I wish I could use Milvus to do [...]

**Describe the solution you'd like**
Support query vector field

### PR DESCRIPTION
**Pull request by cydrain**
Resolves: #6299
Signed-off-by: yudong.cai <yudong.cai@zilliz.com>

### CODE REVIEW

**Comment by xige-16** [comment]
any unit test on this fix?

**Comment by cydrain** [comment]
This is system level functionality, unit test cannot cover.
I have asked tester team to add cases to cover this.

**Pull request merged**
