### PR TITLE
 Optimize multi logical exprs performance when meet some situations

### PR DESCRIPTION
**Pull request by zhagnlu**
#26261

### CODE REVIEW

**Comment by czs007** [comment]
Add some unit tests?

**Comment by czs007** [comment]
Add some unit tests?

**Comment by zhagnlu** [comment]
rerun ut

**Comment by xiaofan-luan** [comment]
this optimization works better with the following tricks
1. we should simply pass in the filter to later expr so we could optimize even if not all the result is 1 or 0.
3. put high filtering rate filter or fast filtering field(like int) in the left operator(Need a simple rule based optimizer)

**Pull request merged**
