### PR TITLE
Fix use address of loop var

### LINKED ISSUE #7432: Using address of loop variable
See code below
https://github.com/milvus-io/milvus/blob/b718bcb1c7410db8e9261025b95502e39743a355/internal/proxy/metrics_info.go#L136-L150
https://github.com/milvus-io/milvus/blob/b718bcb1c7410db8e9261025b95502e39743a355/internal/proxy/metrics_info.go#L211-L225
Use address of loop variable will cause all results having the last iterated value

### PR DESCRIPTION
**Pull request by congqixia**
Fix use address of loop variable

Fix #7432 

Signed-off-by: Congqi Xia <congqi.xia@zilliz.com>

### CODE REVIEW

**Comment by DragonDriver** [comment]
/lgtm
thx for pointing out this. @congqixia 
i think we will be more careful when use the address of loop var after this pr.

**Comment by congqixia** [comment]
> /lgtm
> thx for pointing out this. @congqixia
> i think we will be more careful when use the address of loop var after this pr.

@DragonDriver Agree. Actually, this kind of error can be detected by golangci-lint but hard to detect by naked eyes. However, lots of check rules are disabled now. Maybe we shall schedule to enable them step by step? @scsven @xiaofan-luan @czs007

**Comment by yanliang567** [comment]
manually label ci-passed

**Pull request merged**
