### PR TITLE
[skip ci] update benchmark scripts on 0.10.4 

### PR DESCRIPTION
**Pull request by del-zhenwu**
**What type of PR is this?**

- [ ] API-change
- [ ] BUG
- [ ] Improvement
- [ ] Documentation
- [ ] Feature
- [x] Test and CI
- [ ] Code Refactoring

**Which issue(s) this PR fixes:**

Fixes #https://github.com/milvus-io/milvus/issues/4210

**What this PR does / why we need it:**

Not Available

**Special notes for your reviewer:**

Not Available

**Additional documentation (e.g. design docs, usage docs, etc.):**

Not Available

### CODE REVIEW

**Comment by JinHai-CN** [comment]
Comments are needed for each test cases or function to identify:
1. The purpose of the function
2. Test steps and condition
3. Expected result.

**Comment by JinHai-CN** [comment]
Does this PR connect with any issue?

**Comment by del-zhenwu** [comment]
> Comments are needed for each test cases or function to identify:
> 
> 1. The purpose of the function
> 2. Test steps and condition
> 3. Expected result.

It's benchmark scripts, not scheduled to be executed in CI stages, comments have been added for the main class and core functions

**Comment by JinHai-CN** [comment]
Have you found the Codacy Static Code Analysis failed? If you check it in detail (https://app.codacy.com/gh/milvus-io/milvus/pullRequest?prid=6485934), you may find there are lots of Python language issues in it. Try to fix it.

**Review by cydrain — APPROVED** [review]

**Comment by JinHai-CN** [comment]
LGTM

**Pull request merged**
