### PR TITLE
enhance: avoid memory copy and serde in mix compaction

### PR DESCRIPTION
**Pull request by tedxu**
See: #37234

### CODE REVIEW

**Comment by tedxu** [comment]
In this PR, the serialization / deserialization operations and memory copies are avoided in mix compaction. From which, the mix compaction performance is improved significantly. See benchmark results below:

Before:
```
BenchmarkMixCompactor-8   	       1	1509607958 ns/op	1605694208 B/op	13207679 allocs/op
```
After
```
BenchmarkMixCompactor-8             3	   472317972 ns/op	924115029 B/op	  7417982 allocs/op
```

**Comment by tedxu** [comment]
rerun cpp-unit-test

**Comment by xiaofan-luan** [comment]
This looks great!

**Pull request merged**
