### PR TITLE
fix: Unnecessary close subscription may block datacoord forever

### PR DESCRIPTION
**Pull request by weiliu1031**
issue: #29709 #29712
1. when deregister a datanode,  datacoord will try to clean up all subscriptions on this data node. but the close progress cloud block forever with holding `channel_manager's` lock. which will stuck the data coord service. 
2. there used a wrong subName, which actually doesn't clean up the subscriptions.

This PR removed the unnecessary close subscription progress, to avoid it block the datacoord service forever

### CODE REVIEW

**Comment by weiliu1031** [comment]
rerun ut

**Comment by czs007** [comment]
Is it feasible to omit the "unsub" operation here ？
The "unsub" operation was previously implemented to prevent the backlog from exceeding the limit.

**Comment by xiaofan-luan** [comment]
all the pulsar subscription should be cleaned by pulsar itself.

**Comment by samhuang-z** [comment]
rerun ut

**Pull request closed without merging**
