### PR TITLE
Fix a nil pointer problem and improve comments

### PR DESCRIPTION
**Pull request by sunby**
Issue: #7624
Signed-off-by: sunby <bingyi.sun@zilliz.com>

### CODE REVIEW

**Review by congqixia — APPROVED** [review]
/lgtm

**Comment by czs007** [comment]
rebase master and retry @sunby

**Comment by xiaofan-luan** [comment]
need details about under which cases the issue will be hit

**Comment by sunby** [comment]
> need details about under which cases the issue will be hit

I will add a unit test about this issue.

**Comment by sunby** [comment]
> need details about under which cases the issue will be hit

Actually this case will not happen unless the meta about a segment is deleted manually

**Pull request merged**
