### PR TITLE
enhance: refactor bitmap index and internal hybrid index

### PR DESCRIPTION
**Pull request by zhagnlu**
#32900

### CODE REVIEW

**Comment by zhagnlu** [comment]
rerun ut

**Comment by zhagnlu** [comment]
rerun ut

**Comment by zhagnlu** [comment]
rerun ut

**Review by longjiquan — COMMENTED** [review]
/lgtm

**Comment by czs007** [comment]
@zhagnlu  @xiaofan-luan  We should discuss whether to expose the HybridIndex indetype to the outside or hide it under AutoIndex, while exposing the BitMap Index.

**Comment by czs007** [comment]
@zhagnlu  the changed code is not related to the title.

**Comment by zhagnlu** [comment]
> @zhagnlu the changed code is not related to the title.

sorry, mix dev branch, update it now

**Comment by zhagnlu** [comment]
rerun ut

**Comment by zhagnlu** [comment]
rerun ut

**Pull request merged**
