### PR TITLE
[test]Update insert testcase from 1.0 to 2.0

### PR DESCRIPTION
**Pull request by jingkl**
Signed-off-by: jingkl <jingjing.jia@zilliz.com>
 issue #15474

testcase | notes
-- | --
test_insert_collection_not_existed | Delete
test_insert_search | Update
_test_insert_segment_row_count | Delete
test_insert_ids | Delete function duplication
test_insert_ids_fields | Delete function duplication
def test_insert_ids_not_match | Delete function duplication
test_insert_twice_ids_no_ids | Update
test_insert_not_ids | Update
test_insert_ids_length_not_match_batch | Delete function duplication
test_insert_ids_length_not_match_single | Repeated cases
test_insert_partition | Repeated cases
test_insert_partition_with_ids | Update
test_insert_default_partition | Update
test_insert_partition_not_existed | Update
test_insert_partition_repeatedly | Update
test_insert_with_field_type_not_match | Update
test_insert_with_field_vector_more | Delete function duplication
test_insert_with_no_field_vector_value | Update
test_insert_with_no_field_vector_type | Update
test_insert_with_no_field_vector_name | Update
test_collection_insert_rows_count_multi_threading | Delete function duplication
_test_insert_disable_auto_flush | Delete deprecated case
test_insert_binary_partition | Update
test_insert_binary_multi_times | Update
test_insert_binary_after_create_index | Delete function duplication
test_insert_binary_create_index | Update
test_insert_binary_search | Update
test_insert_async_invalid_params | Update
test_insert_async_invalid_params_raise_exception | Repeated cases
test_insert_entity_multi_collections | Delete function duplication
test_drop_collection_insert_entity_another | Delete unsuitable for functional testing
test_create_index_insert_entity_another | Delete unsuitable for functional testing
test_insert_entity_create_index_another | Delete unsuitable for functional testing
test_insert_entity_sleep_create_index_another | Deleted of Repeated cases
test_search_entity_insert_entity_another | Delete unsuitable for functional testing
test_insert_entity_search_entity_another | Delete unsuitable for functional testing
test_insert_entity_sleep_search_entity_another | Deleted of Repeated cases
_test_insert_entity_during_release_collection | Deleted of deprecated case
test_insert_ids_invalid | Updated
test_insert_with_invalid_collection_name | Deleted of deprecated case
test_insert_with_invalid_partition_name | Updated
test_insert_with_invalid_field_type | Updated
test_insert_with_invalid_field_value | Updated
test_insert_with_invalid_field_entity_value | Updated
test_insert_with_invalid_field_name | Updated
test_insert_with_invalid_field_value | Updated
test_insert_with_invalid_field_entity_value | Updated
test_insert_ids_invalid | Updated
test_insert_with_invalid_field_type | Updated
test_insert_with_invalid_field_entities_value | Updated

</byte-sheet-html-origin>

### CODE REVIEW

**Comment by binbinlv** [comment]
@jingkl could you please solve the following comments, thanks.

1. please format the code style like "future, _ = collection_w.insert(data=df, _async=True,check_task=CheckTasks.err_res, check_items=error)"
2. The case "TestInsertOperation::test_insert_search" could be deleted for duplicate of basic search test case.
3. It seems the test case "TestInsertOperation::test_insert_twice_ids_no_ids" does not do what the name and comments describes.
4. The case "TestInsertBinary::test_insert_binary_search" could be deleted for duplicate of basic search test case.
5. It seems that the two cases are same scenarios: "TestInsertOperation::test_insert_with_no_vector_field_dtype" and "test_insert_with_invalid_field_type:: test_insert_with_invalid_field_type".

**Comment by jingkl** [comment]
> @jingkl could you please solve the following comments, thanks.
> 
> 1. please format the code style like "future, _ = collection_w.insert(data=df, _async=True,check_task=CheckTasks.err_res, check_items=error)"
> 2. The case "TestInsertOperation::test_insert_search" could be deleted for duplicate of basic search test case.
> 3. It seems the test case "TestInsertOperation::test_insert_twice_ids_no_ids" does not do what the name and comments describes.
> 4. The case "TestInsertBinary::test_insert_binary_search" could be deleted for duplicate of basic search test case.
> 5. It seems that the two cases are same scenarios: "TestInsertOperation::test_insert_with_no_vector_field_dtype" and "test_insert_with_invalid_field_type:: test_insert_with_invalid_field_type".

ok,I have modified

**Comment by binbinlv** [comment]
The following line should be formated in test case "test_insert_with_no_vector_field_dtype"

df =[field_one , field_two ,vec_field]

**Pull request merged**
