### PR TITLE
Support windows compliation

### PR DESCRIPTION
**Pull request by matrixji**
- remove dl dependency while compiling some lib under MSYS
- int types aligement in golang
- core/src/utils adaptation for compile under MSYS

issue: #7706

Signed-off-by: Ji Bin <matrixji@live.com>

### CODE REVIEW

**Comment by xiaofan-luan** [comment]
@matrixji are we merging all the related issue in? we should do so since Milvus 2.0 GA is in.

**Comment by xiaofan-luan** [comment]
Also we saperate milvus and knowhere, which should make your patch a little bit easier.

**Comment by xiaofan-luan** [comment]
@soothing-rain @jaime0815 please followup the following issues to make milvus running on windows platform

**Comment by jaime0815** [comment]
I saw this patch didn't change knowhere, so integrating it knowhere branch is not difficult. we can progress it after knowhere branch merges to master. @soothing-rain

**Comment by soothing-rain** [comment]
> I saw this patch didn't change knowhere, so integrating it to knowhere branch is not difficult. we can progress it after knowhere branch merges to master. @soothing-rain

Sounds good :)

**Comment by matrixji** [comment]
> @matrixji are we merging all the related issue in? we should do so since Milvus 2.0 GA is in.
Compile and run under windows will be finished in several commits. Another PR just rebased recently #9105, and some CI-related PRs may come later after all code adaptations merged.

**Comment by soothing-rain** [comment]
> I saw this patch didn't change knowhere, so integrating it to knowhere branch is not difficult. we can progress it after knowhere branch merges to master. @soothing-rain

Any idea which day will knowhere branch be merged into master?

**Comment by jaime0815** [comment]
> > I saw this patch didn't change knowhere, so integrating it to knowhere branch is not difficult. we can progress it after knowhere branch merges to master. @soothing-rain
> 
> Any idea which day will knowhere branch be merged into master?

this week

**Comment by xiaofan-luan** [comment]
@matrixji do we support milvus compilation already or we need more patches later?

**Comment by matrixji** [comment]
> @matrixji do we support milvus compilation already or we need more patches later?

I see external knowhere already merged, I'm porting it based on external windows(msys) based knowhere.
Some adaptation work for knowhere is already ongoing [!68](https://github.com/milvus-io/knowhere/pull/68)

BTW: Currently, I see milvus master using knowhere 1.0.1 which is from knowhere 1.x branch. So any guys could help to answer what's our version strategy for knowhere in milvus master?

If we plan to use knowhere 1.x branch for a long time, then I'd like to do some additional porting work for: `knowhere/1.x + windows` >> `milvis/master + windows`

**Comment by xiaofan-luan** [comment]
> > @matrixji do we support milvus compilation already or we need more patches later?
> 
> I see external knowhere already merged, I'm porting it based on external windows(msys) based knowhere. Some adaptation work for knowhere is already ongoing [!68](https://github.com/milvus-io/knowhere/pull/68)
> 
> BTW: Currently, I see milvus master using knowhere 1.0.1 which is from knowhere 1.x branch. So any guys could help to answer what's our version strategy for knowhere in milvus master?
> 
> If we plan to use knowhere 1.x branch for a long time, then I'd like to do some additional porting work for: `knowhere/1.x + windows` >> `milvis/master + windows`

We just separate milvus into two parts, distributed part and Knowhere the execution engine.
So any change could just be put into Knowhere project and finally we'll remove vector search code in Milvus repo

**Comment by xiaofan-luan** [comment]
Knowhere and Milvus will be maintained separately as two projects and their version and release will happened on their own need

**Pull request merged**
