### PR TITLE
Fix expression on integer overflow case (#24867, #24893, #24920, #24943)

### PR DESCRIPTION
**Pull request by longjiquan**
issue: https://github.com/milvus-io/milvus/issues/23646

### CODE REVIEW

**Comment by yah01** [comment]
/hold
@longjiquan plz cherry-pick with #25016 and then unhold this

**Comment by longjiquan** [comment]
rerun ut

**Comment by longjiquan** [comment]
rerun ut

**Comment by longjiquan** [comment]
> /hold @longjiquan plz cherry-pick with #25016 and then unhold this

thx for the fix and this pr already picked the fix.
/unhold

**Pull request merged**
