### PR TITLE
fix: incorrect dim set when creating BM25 doc sparse array

### PR DESCRIPTION
**Pull request by zhengbuqian**
issue: https://github.com/milvus-io/milvus/issues/35853

### CODE REVIEW

**Comment by zhengbuqian** [comment]
issue: #35853

**Review by SonyK16 — COMMENTED** [review]
it looks very good man, for real. But please, be careful. I recommend you to delete the code from GitHub or to turn it imto private file. Don't save anything on iCloud. Save it on a cold hardware. Last month I lost 12TB of data because the fruit company blocked my account....imageimage

**Pull request merged**
