### PR TITLE
try to upgrade to 1.18

### PR DESCRIPTION
**Pull request by jiaoew1991**
Signed-off-by: Enwei Jiao <enwei.jiao@zilliz.com>
issue: https://github.com/milvus-io/milvus/issues/18111

### CODE REVIEW

**Comment by xiaofan-luan** [comment]
looks good to me.
@LoveEachDay any concerns?

**Comment by LoveEachDay** [comment]
> looks good to me. @LoveEachDay any concerns?

@jiaoew1991 @xiaofan-luan  We'll try a 100m milvus cluster stability test to check whether any performance downgradation. If everything goes well, then we can merge this pr.

**Comment by jennyli-z** [comment]
This pr only change the dockerfile to build builder image can be merged first, as ci does not use this dockerfile to build.
After this is merged, robot will create a pr like https://github.com/milvus-io/milvus/pull/15410/files, we will not let this merge, as there's many code change to fit the 1.18 version, we can hold on that pr to do more testing.

**Pull request merged**
