### PR TITLE
Add a SyncSegments to sync meta between DN and DC

### PR DESCRIPTION
**Pull request by XuanYang-cn**
See also: #19072

Signed-off-by: yangxuan <xuan.yang@zilliz.com>

### CODE REVIEW

**Comment by XuanYang-cn** [comment]
/hold

#19312 #19313

**Comment by XuanYang-cn** [comment]
rerun ut

**Comment by XuanYang-cn** [comment]
rerun ut

**Review by congqixia — APPROVED** [review]
/lgtm

**Pull request merged**
