### PR TITLE
Fix an issue that causes flush hanging

### PR DESCRIPTION
**Pull request by soothing-rain**
issue: #16288

Signed-off-by: Yuchen Gao <yuchen.gao@zilliz.com>

### CODE REVIEW

**Review by congqixia — COMMENTED** [review]
Re-sending tt in flowgraph need one condition satisified: there are still incoming timetick from dml channels, which means the collection cannot be dropped during the Datacoord recovery procedure. Are there any policy to handle this case?

**Comment by soothing-rain** [comment]
> Re-sending tt in flowgraph need one condition satisified: there are still incoming timetick from dml channels, which means the collection cannot be dropped during the Datacoord recovery procedure. Are there any policy to handle this case?

Good catch.

Just gave it a try. It is facinating that

**Review by congqixia — APPROVED** [review]
/lgtm

**Pull request merged**
