### PR TITLE
fix:wrong warning log when idf oracle find L0 segment lacks

### PR DESCRIPTION
**Pull request by aoiasd**
relate: https://github.com/milvus-io/milvus/issues/35853

### CODE REVIEW

**Comment by aoiasd** [comment]
rerun cpp-unit-test

**Comment by aoiasd** [comment]
rerun go-sdk

**Comment by aoiasd** [comment]
rerun cpp-unit-test

**Comment by aoiasd** [comment]
rerun cpp-unit-test

**Review by congqixia — APPROVED** [review]
/lgtm

**Pull request merged**
