### PR TITLE
Remove Dead Code, use signed type

### PR DESCRIPTION
**Pull request by FluorineDog**
Signed-off-by: fluorinedog <fluorinedog@gmail.com>

### CODE REVIEW

**Comment by czs007** [comment]
You can delete the code instead of commenting out the code.

**Comment by czs007** [comment]
Link an issue to illustrate your intention of this modification.

**Comment by FluorineDog** [comment]
#6420

**Comment by czs007** [comment]
> #6420

@FluorineDog 
You didn't describe anything in this issue, so what is the point of opening this issue?

**Pull request merged**
