### PR TITLE
Upgrade to knowhere-v1.1.12

### PR DESCRIPTION
**Pull request by cydrain**
Signed-off-by: yudong.cai <yudong.cai@zilliz.com>

### CODE REVIEW

**Comment by xiaofan-luan** [comment]
@cydrain do we want to bring in 2.1?

**Comment by longjiquan** [comment]
LGTM

**Comment by cydrain** [comment]
> @cydrain do we want to bring in 2.1?
we have discussed this before, knowhere-v1.1.12 has not been fully tested, merging into Milvus 2.1 will bring unknown risk.

**Pull request merged**
