### PR TITLE
enhance: [GoSDK] Remove example in main pkg to make ut script work

### PR DESCRIPTION
**Pull request by congqixia**
Related to #31293

Example with main func/package causes `go list` command failed with vcs error. This PR removes example files with main package. The example snippet shall be added back in runnable test format.

### CODE REVIEW

**Comment by congqixia** [comment]
rerun go-sdk

**Comment by congqixia** [comment]
rerun go-sdk

**Review by ThreadDao — COMMENTED** [review]
/lgtm

**Pull request merged**
