### PR TITLE
remove useless log in querycoord

### PR DESCRIPTION
**Pull request by weiliu1031**
Signed-off-by: Wei Liu <wei.liu@zilliz.com>
issue: #27345

### CODE REVIEW

**Comment by weiliu1031** [comment]
> @weiliu1031 E2e jenkins job failed, comment `/run-cpu-e2e` can trigger the job again.

failed in install step

**Comment by yanliang567** [comment]
@weiliu1031 please rebase the master, we have updated the tests

**Review by congqixia — APPROVED** [review]
/lgtm

**Pull request merged**
