### PR TITLE
fix component not exit when liveness check failed

### PR DESCRIPTION
**Pull request by weiliu1031**
Signed-off-by: Wei Liu <wei.liu@zilliz.com>
issue: #27021

when livenessCheck exit, datacoord's exit callback doesn't trigger, which produce a idle datacoord.

### CODE REVIEW

**Comment by weiliu1031** [comment]
> @weiliu1031 ut workflow job failed, comment `rerun ut` can trigger the job again.

image
ut failed due to disconnected from etcd

**Comment by weiliu1031** [comment]
> @weiliu1031 E2e jenkins job failed, comment `/run-cpu-e2e` can trigger the job again.

image
unstable case

**Comment by weiliu1031** [comment]
> @weiliu1031 E2e jenkins job failed, comment `/run-cpu-e2e` can trigger the job again.

create index timeout

**Review by congqixia — APPROVED** [review]
/lgtm

**Pull request merged**
