### PR TITLE
enhance: Reduce bloom filter lock contention between insert and delete in query coord

### PR DESCRIPTION
**Pull request by weiliu1031**
issue: #32530

cause ProcessDelete need to check whether pk exist in bloom filter, and ProcessInsert need to update pk to bloom filter, when execute ProcessInsert and ProcessDelete in parallel, it will cause race condition in segment's bloom filter

This PR execute ProcessInsert and ProcessDelete in serial to avoid block each other

### CODE REVIEW

**Comment by weiliu1031** [comment]
rerun ut

**Comment by weiliu1031** [comment]
rerun ut

**Review by congqixia — APPROVED** [review]
/lgtm

**Pull request merged**
