### PR TITLE
Drop indexes on segments when dropping partition

### PR DESCRIPTION
**Pull request by xiaocai2333**
issue: #17535 
Signed-off-by: Cai.Zhang <cai.zhang@zilliz.com>

### CODE REVIEW

**Comment by xiaofan-luan** [comment]
due to #17648, segment will never be deleted or marked as drop.

**Review by xiaofan-luan — COMMENTED** [review]
createIndexForSegment need to ignore partition not existed case.

We need to add log about indexIDs and IndexBuildIDs before we call RemoveIndexService

**Comment by xiaocai2333** [comment]
rerun ut

**Comment by xiaocai2333** [comment]
rerun ut

**Pull request closed without merging**
