### PR TITLE
fix: [Cherry-pick] sync action load segment with lack collection index info list 

### PR DESCRIPTION
**Pull request by aoiasd**
relate: https://github.com/milvus-io/milvus/issues/28779 https://github.com/milvus-io/milvus/issues/28637
pr: https://github.com/milvus-io/milvus/pull/28788

### CODE REVIEW

**Comment by aoiasd** [comment]
rerun ut

**Comment by aoiasd** [comment]
rerun ut

**Comment by aoiasd** [comment]
rerun ut

**Comment by aoiasd** [comment]
rerun ut

**Review by congqixia — APPROVED** [review]
/lgtm

**Pull request merged**
