### PR TITLE
Fix arrow compile error

### PR DESCRIPTION
**Pull request by jiaoew1991**
/kind improvement

### CODE REVIEW

**Comment by jiaoew1991** [comment]
should be affected by this commit https://github.com/conan-io/conan-center-index/commit/eec8b0073a02776872ff04f803b46a691a14ff1a#diff-8bccf85b8738fe9963099a68c25d98d0160fb1ed06657221ea2daebea2c685f0R49

**Review by congqixia — APPROVED** [review]
/lgtm

**Comment by PowderLi** [comment]
```
"arrow:with_thrift": True,
```
need to be removed

ERROR: arrow/11.0.0: option 'with_thrift' doesn't exist
Possible options are ['shared', 'fPIC', 'gandiva', 'parquet', 'substrait', 'skyhook', 'acero', 'cli', 'compute', 'dataset_modules', 'deprecated', 'encryption', 'filesystem_layer', 'hdfs_bridgs', 'plasma', 'simd_level', 'runtime_simd_level', 'with_backtrace', 'with_boost', 'with_csv', 'with_cuda', 'with_flight_rpc', 'with_flight_sql', 'with_gcs', 'with_gflags', 'with_glog', 'with_grpc', 'with_jemalloc', 'with_mimalloc', 'with_json', 'with_llvm', 'with_openssl', 'with_opentelemetry', 'with_orc', 'with_protobuf', 'with_re2', 'with_s3', 'with_utf8proc', 'with_brotli', 'with_bz2', 'with_lz4', 'with_snappy', 'with_zlib', 'with_zstd']

**Comment by jiaoew1991** [comment]
> ```
> "arrow:with_thrift": True,
> ```
> 
> need to be removed
> 
> or update arrow/11.0.0 to arrow/13.0.0
> 
> ERROR: arrow/11.0.0: option 'with_thrift' doesn't exist Possible options are ['shared', 'fPIC', 'gandiva', 'parquet', 'substrait', 'skyhook', 'acero', 'cli', 'compute', 'dataset_modules', 'deprecated', 'encryption', 'filesystem_layer', 'hdfs_bridgs', 'plasma', 'simd_level', 'runtime_simd_level', 'with_backtrace', 'with_boost', 'with_csv', 'with_cuda', 'with_flight_rpc', 'with_flight_sql', 'with_gcs', 'with_gflags', 'with_glog', 'with_grpc', 'with_jemalloc', 'with_mimalloc', 'with_json', 'with_llvm', 'with_openssl', 'with_opentelemetry', 'with_orc', 'with_protobuf', 'with_re2', 'with_s3', 'with_utf8proc', 'with_brotli', 'with_bz2', 'with_lz4', 'with_snappy', 'with_zlib', 'with_zstd']

`rm -rf ~/.conan/data/arrow`

**Pull request merged**
