### PR TITLE
fix: update ubuntu base image version

### PR DESCRIPTION
**Pull request by jenkoon**
related to #33945
FIX CVEs of milvus base image: LOW: 32,  MEDIUM: 50, **Total FIX: 82**
image
image

### CODE REVIEW

**Comment by weiZhenkun** [comment]
@LoveEachDay @czs007  Please review, thanks.

**Comment by weiZhenkun** [comment]
master fix: https://github.com/milvus-io/milvus/pull/33944

**Comment by weiZhenkun** [comment]
issue: #33945

**Comment by xiaofan-luan** [comment]
@weiZhenkun 
there is an compile issue on old master. can  you rebase with latest master and rerun the ut

**Comment by xiaofan-luan** [comment]
@zwd1208 @LoveEachDay 
any questions?

**Comment by weiZhenkun** [comment]
> @weiZhenkun there is an compile issue on old master. can you rebase with latest master and rerun the ut

I am not change on Amazonlinux 2023 and rockylinux8 and MacOS, I just change the AMD64 Ubuntu 20.04.
I will trigger UT again.

**Comment by weiZhenkun** [comment]
@xiaofan-luan  @LoveEachDay @czs007 can we merge it now?

**Comment by czs007** [comment]
pr :https://github.com/milvus-io/milvus/pull/33944

**Pull request merged**
