### PR TITLE
Fix load the same segments multiple times for manual LoadBalance

### PR DESCRIPTION
**Pull request by yah01**
Signed-off-by: yah01 <yang.cen@zilliz.com>
#16627

### CODE REVIEW

**Comment by yah01** [comment]
rerun ut

**Comment by yah01** [comment]
rerun ut

**Comment by yah01** [comment]
rerun ut

**Comment by yah01** [comment]
rerun ut

**Review by congqixia — APPROVED** [review]
Just on thing: the execute function is too long to read
/lgtm

**Pull request merged**
