### PR TITLE
Fix csv updateProgress

### PR DESCRIPTION
**Pull request by KumaJie**
issue: #27148 
In the past version, csv parser use `InputOffset()` to get file offset, but it only supported after go 1.19.
To fix that, I use string which parsed by csv, and convert it to `[]byte`.  Using `len([]byte)` to approximate file offset.

### CODE REVIEW

**Comment by yhmo** [comment]
rerun ut

**Comment by yhmo** [comment]
Since the inputOffset is calculated by the sum of string length, the commas and black spaces are ignored, the final value is less than the actual file size. So, the progress value is not accurate. But it is not a big problem.

**Comment by KumaJie** [comment]
> Since the inputOffset is calculated by the sum of string length, the commas and black spaces are ignored, the final value is less than the actual file size. So, the progress value is not accurate. But it is not a big problem.

Hi. I mention the problem. But I can't get accurate offset in go 1.18 `encoding/csv`. I think pr #28080 is good way to solve it.Thanks.

**Comment by xiaofan-luan** [comment]
We should also think of upgrade to go 1.20 in 2.4

**Pull request closed without merging**
