### PR TITLE
enhance: Organize the common modules of streamingNode and dataNode

### PR DESCRIPTION
**Pull request by bigsheeper**
1. Move the common modules of streamingNode and dataNode to flushcommon
2. Add new GetVChannels interface for rootcoord

issue: https://github.com/milvus-io/milvus/issues/33285

### CODE REVIEW

**Comment by bigsheeper** [comment]
rerun ut

**Comment by jaime0815** [comment]
There are cycle dependencies in the modules: `flushcommon -> datanode, flushcommon -> streamnode, datanode -> flushcommon`. The correct dependencies should be:` flushcommon -> datanode, flushcommon -> streamnode`.

**Comment by bigsheeper** [comment]
> There are cycle dependencies in the modules: `flushcommon -> datanode, flushcommon -> streamnode, datanode -> flushcommon`. The correct dependencies should be:` flushcommon -> datanode, flushcommon -> streamnode`.

Yep, we need to remove the datanode dependencies in flushcommon latter.

**Pull request merged**
