### PR TITLE
Fix folly run on sse42 machine

### PR DESCRIPTION
**Pull request by chasingegg**
/kind improvement

### CODE REVIEW

**Comment by xiaofan-luan** [comment]
so is this disable sse42?
what if the machine has sse42

**Comment by liliu-z** [comment]
> so is this disable sse42? what if the machine has sse42

This ac

> so is this disable sse42? what if the machine has sse42

@xiaofan-luan I think our conanfile has some problem, https://github.com/milvus-io/conanfiles/blob/main/folly/all/conanfile.py#L229
This `use_sse4_2` will add `-mfma` during the compile and it ask for FMA, which needs Haswell+ CPU arch (same as AVX2) https://en.wikipedia.org/wiki/List_of_Intel_CPU_microarchitectures

**Comment by xiaofan-luan** [comment]
> > so is this disable sse42? what if the machine has sse42
> 
> This ac
> 
> > so is this disable sse42? what if the machine has sse42
> 
> @xiaofan-luan I think our conanfile has some problem, https://github.com/milvus-io/conanfiles/blob/main/folly/all/conanfile.py#L229 This `use_sse4_2` will add `-mfma` during the compile and it ask for FMA, which needs Haswell+ CPU arch (same as AVX2) https://en.wikipedia.org/wiki/List_of_Intel_CPU_microarchitectures

so should we change the conan file of folly?

**Comment by liliu-z** [comment]
> > > so is this disable sse42? what if the machine has sse42
> > 
> > 
> > This ac
> > > so is this disable sse42? what if the machine has sse42
> > 
> > 
> > @xiaofan-luan I think our conanfile has some problem, https://github.com/milvus-io/conanfiles/blob/main/folly/all/conanfile.py#L229 This `use_sse4_2` will add `-mfma` during the compile and it ask for FMA, which needs Haswell+ CPU arch (same as AVX2) https://en.wikipedia.org/wiki/List_of_Intel_CPU_microarchitectures
> 
> so should we change the conan file of folly?

Yes, will do this.
I'd like to reevaluate all these config. @chasingegg Plz close this for now

**Pull request closed without merging**
