### PR TITLE
Fix incorrect e2e test

### PR DESCRIPTION
**Pull request by yah01**
Signed-off-by: yah01 <yang.cen@zilliz.com>
/kind bug
#19785

### CODE REVIEW

**Comment by congqixia** [comment]
I suggest e2e test cases shall assert specified `Error Code` instead of error message.
WDYGT @xiaofan-luan  @czs007 @jiaoew1991 @soothing-rain

**Comment by zhuwenxing** [comment]
> I suggest e2e test cases shall assert specified `Error Code` instead of error message. WDYGT @xiaofan-luan @czs007 @jiaoew1991 @soothing-rain

```
    @staticmethod
    def assert_exception(res, actual=True, error_dict=None):
        assert actual is False
        assert len(error_dict) > 0
        if isinstance(res, Error):
            error_code = error_dict[ct.err_code]
            assert res.code == error_code or error_dict[ct.err_msg] in res.message
        else:
            log.error("[CheckFunc] Response of API is not an error: %s" % str(res))
            assert False
        return True
```

**Pull request merged**
