### PR TITLE
fix: fix grant/revoke v2 meta and unclear error messages

### PR DESCRIPTION
**Pull request by shaoting-huang**
related issue: https://github.com/milvus-io/milvus/issues/37031

fixed issues:
#37974: better error messages for grant v2 interface
#37903: fix meta built-in privilege group object name
#37843: better error messages for custom privilege group interface 
#38002: fix built-in privilege group meta to pass proxy interceptor check
#38008: fix revoke v2 to support revoking v1 granted privileges

### CODE REVIEW

**Comment by shaoting-huang** [comment]
rerun go-sdk

**Comment by shaoting-huang** [comment]
rerun go-sdk

**Review by congqixia — APPROVED** [review]
/approve

**Pull request merged**
