### PR TITLE
use a large watchTimeoutInterval

### PR DESCRIPTION
**Pull request by aoiasd**
related:https://github.com/milvus-io/milvus/issues/23238
Signed-off-by: aoiasd [zhicheng.yue@zilliz.com](mailto:zhicheng.yue@zilliz.com)

### CODE REVIEW

**Comment by xiaofan-luan** [comment]
why would we still need it with ticke?

**Comment by aoiasd** [comment]
> why would we still need it with tickle?

This was the DataCoord tickler check interval, watch event will timeout if check failed, now was 30s and DataCoord tickler will update every 15s. We want DataCoord could try update twice and timeout if all failed or no progress, but we will check only once in fact. 
So DataCoord will only have 15s to get any progress, or will timeout, and now we find some status log use more than 20s, will cause timeout.
So I will set this param to 50s, make sure that if success load a status log in 45s, we will not timeout.

**Comment by xiaofan-luan** [comment]
> > why would we still need it with tickle?
> 
> This was the DataCoord tickler check interval, watch event will timeout if check failed, now was 30s and DataCoord tickler will update every 15s. We want DataCoord could try update twice and timeout if all failed or no progress, but now we will check only once in fact. So DataCoord will only have 15s to get any progress, or will timeout, and now we find some status log use more than 20s, will cause timeout. So I will set this param to 50s, make sure that if success load a status log in 45s, we will not timeout.

Make it to 1 or 2 mintues works for me

**Review by congqixia — APPROVED** [review]
/lgtm

**Pull request merged**
