### PR TITLE
enhance: Support database/collection level GC Control API

### PR DESCRIPTION
**Pull request by congqixia**
See also #31763

Add `scope` parameter for GcControl API and related `collection` & `database` paramter

### CODE REVIEW

**Comment by xiaofan-luan** [comment]
let's hold this modifications. The gc process is already too complicated and introduced many troubles.

If there is no scan, our life will be much easier. Or if we can leave orphan files to 7 days, then we don't need to worry about the gc.

**Comment by congqixia** [comment]
@xiaofan-luan this enhancement is needed in case of compaction caused segment file missing, which may lead to backup failure. any other solution to avoid that problem?
cc @yelusion2 @Thomas-HuWei

**Comment by xiaofan-luan** [comment]
> @xiaofan-luan this enhancement is needed in case of compaction caused segment file missing, which may lead to backup failure. any other solution to avoid that problem? cc @yelusion2 @Thomas-HuWei

we can just keep the gc period to 7 days?

**Comment by xiaofan-luan** [comment]
if collection is dropped, it doesn't need to follow the 7 days limitation

**Comment by congqixia** [comment]
> > @xiaofan-luan this enhancement is needed in case of compaction caused segment file missing, which may lead to backup failure. any other solution to avoid that problem? cc @yelusion2 @Thomas-HuWei
> 
> we can just keep the gc period to 7 days?

@xiaofan-luan 
Not sure what the "7 days" definition is. Does it mean the drop/missing tolerance duration? or gc execution interval?
I guess it's the drop/missing tolerance configuration value.
the problem here is that the "fast-gc" policy introduced in 2.3 will skip the drop tolerance value as long as the compact to segment has indexes

**Pull request closed without merging**
