### PR TITLE
Add disable traceback option for pytest

### PR DESCRIPTION
**Pull request by zhuwenxing**
Signed-off-by: zhuwenxing <wenxing.zhu@zilliz.com>

/kind improvement

see: #8764

### CODE REVIEW

**Comment by binbinlv** [comment]
@zhuwenxing  please associate an issue which includes the reason for this PR.

Thanks.

**Comment by zhuwenxing** [comment]
> @zhuwenxing please associate an issue which includes the reason for this PR.
> 
> Thanks.

done

**Pull request merged**
