### PR TITLE
enhance: Upgrade go version from 1.20 to 1.21

### PR DESCRIPTION
**Pull request by shaoting-huang**
issue #32982

related pr in master:
pr: #33047 #33150 #33176 #33351 #33202 #33192

### CODE REVIEW

**Comment by shaoting-huang** [comment]
rerun ut

**Comment by shaoting-huang** [comment]
related pr in master:
https://github.com/milvus-io/milvus/pull/33047
https://github.com/milvus-io/milvus/pull/33150
https://github.com/milvus-io/milvus/pull/33176
https://github.com/milvus-io/milvus/pull/33351
https://github.com/milvus-io/milvus/pull/33202
https://github.com/milvus-io/milvus/pull/33192

**Review by congqixia — APPROVED** [review]
/lgtm

**Pull request merged**
