### PR TITLE
fix: search-group-by failed to get data from multi-chunked-segment(##…

### PR DESCRIPTION
**Pull request by MrPresent-Han**
related: #38343

### CODE REVIEW

**Comment by MrPresent-Han** [comment]
rerun ut

**Comment by MrPresent-Han** [comment]
rerun go-sdk

**Comment by MrPresent-Han** [comment]
rerun ut

**Comment by sunby** [comment]
Code looks good to me but we need more unittests to cover this function

**Comment by MrPresent-Han** [comment]
I will give more unit test for this function next week

**Review by congqixia — APPROVED** [review]
/approve

**Pull request merged**
