### PR TITLE
Make proxy update cache with NotShardLeader status code

### PR DESCRIPTION
**Pull request by XuanYang-cn**
See also: #16926

Signed-off-by: yangxuan <xuan.yang@zilliz.com>

/kind improvement

### CODE REVIEW

**Review by congqixia — APPROVED** [review]
/lgtm

**Comment by XuanYang-cn** [comment]
rerun macos check

**Comment by XuanYang-cn** [comment]
rerun ut

**Comment by XuanYang-cn** [comment]
rerun ut

**Pull request merged**
