### PR TITLE
Enable ZSTD compression for pulsar

### PR DESCRIPTION
**Pull request by yah01**
Signed-off-by: yah01 <yang.cen@zilliz.com>
/kind improvement

### CODE REVIEW

**Comment by yah01** [comment]
NOTE: This requires pulsar client version >= 2.3

**Comment by yah01** [comment]
rerun ut

**Comment by jaime0815** [comment]
Suggest providing a configurable compression type to replace using a bool represents open or close compression, and we'd better abstract it to a higher-level interface.

**Comment by yah01** [comment]
> Suggest providing a configurable compression type to replace using a bool represents open or close compression, and we'd better abstract it to a higher-level interface.

Thanks for suggestion! Sure, I realized that, but Milvus will support Kafka, and the compression algorithm types (enum value) are different between Pulsar and Kafka, even there exists an algorithm that Kafka supports but Pulsar not (Snappy). In my view, keeping it simple is better, only provides ZSTD compression, because we can configure its compression level to balance between compression ratio and compression speed. We may provide an option to set the compression level later.

**Pull request merged**
