### PR TITLE
enhance: unable to compile C++ tests

### PR DESCRIPTION
**Pull request by yah01**
The tests need to call a private method, Milvus uses `#define` to replace private with public, the hack trick works but would be broken if the including order changed.

This uses friend to make all things work well

### CODE REVIEW

**Comment by yah01** [comment]
rerun ut

**Comment by yah01** [comment]
rerun ut

**Comment by yah01** [comment]
rerun ut

**Comment by wayblink** [comment]
rerun ut

**Comment by wayblink** [comment]
rerun ut

**Pull request merged**
