### PR TITLE
enhance: Support gc with bm25 stats logs

### PR DESCRIPTION
**Pull request by aoiasd**

### CODE REVIEW

**Comment by zhengbuqian** [comment]
rerun ut

**Comment by aoiasd** [comment]
rerun ut

**Comment by czs007** [comment]
ternal/metastore/kv/datacoord (524ms) (coverage: 9.2% of statements in ./...)

=== Failed
=== FAIL: internal/metastore/kv/datacoord Test_DropSegment/remove_successfully (0.00s)
    kv_catalog_test.go:536: 
        	Error Trace:	/go/src/github.com/milvus-io/milvus/internal/metastore/kv/datacoord/kv_catalog_test.go:536
        	Error:      	Not equal: 
        	            	expected: 4
        	            	actual  : 5
        	Test:       	Test_DropSegment/remove_successfully
    --- FAIL: Test_DropSegment/remove_successfully (0.00s)


rebase or check this failure.

**Pull request merged**
