### PR TITLE
Dedup output fields for task query

### LINKED ISSUE #18672: [Bug]: Query Output fields may contain duplicated pk column
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: be933a7
- Deployment mode(standalone or cluster): both
- SDK version(e.g. pymilvus v2.0.0rc2): go 2.1.1
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Returned Output fields for `QueryByPk(ctx, ... []{"embeding", "ID"}` may contains two returned column for primary key "ID"

### Expected Behavior

Returned column shall be exactly the same with the output field (or with added pk column if not provided)

### Steps To Reproduce

_No response_

### Milvus Log

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by congqixia**
Fix #18672

/kind bug

Signed-off-by: Congqi Xia <congqi.xia@zilliz.com>

### CODE REVIEW

**Review by jiaoew1991 — COMMENTED** [review]
add some UT?

**Comment by congqixia** [comment]
@jiaoew1991 unit tests added.

**Pull request merged**
