### PR TITLE
Fix WatchDmChannelsRequest can be too large to save in etcd

### PR DESCRIPTION
**Pull request by wayblink**
related #17726 
Signed-off-by: wayblink <anyang.wang@zilliz.com>

### CODE REVIEW

**Comment by xiaofan-luan** [comment]
We will need a issue for this~

**Comment by wayblink** [comment]
rerun ut

**Comment by wayblink** [comment]
rerun ut

**Comment by wayblink** [comment]
rerun ut

**Comment by wayblink** [comment]
rerun ut

**Comment by wayblink** [comment]
rerun ut

**Pull request merged**
