### PR TITLE
enhance: filter out the not needed collections while listing

### LINKED ISSUE #29631: [Bug]: ShowCollections doesn't respect the `CollectionNames` parameter
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

`CollectionNames` param doesn't work at all

### Expected Behavior

_No response_

### Steps To Reproduce

_No response_

### Milvus Log

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by yah01**
this improves performance while many collections exist
resolve #29631

### CODE REVIEW

**Comment by samhuang-z** [comment]
rerun ut

**Comment by yah01** [comment]
rerun ut

**Comment by samhuang-z** [comment]
rerun ut

**Pull request merged**
