### PR TITLE
enhance: pass partition key scalar info if enabled when build vector index

### PR DESCRIPTION
**Pull request by PwzXxm**
issue: #29892 

Pass optional scalar IVF offsets to Cardinal

### CODE REVIEW

**Comment by xiaocai2333** [comment]
LGTM for indexbuilder

**Comment by PwzXxm** [comment]
rerun ut

**Comment by PwzXxm** [comment]
rerun ut

**Comment by PwzXxm** [comment]
rerun ut

**Comment by PwzXxm** [comment]
rerun ut

**Comment by PwzXxm** [comment]
rerun ut

**Review by congqixia — APPROVED** [review]
/lgtm

**Pull request merged**
