### PR TITLE
Add docker images base on newer ubuntu LTS

### PR DESCRIPTION
**Pull request by soulteary**
Hi,  maintainers 👋

I refer to the existing dockerfile and upgrade Ubuntu LTS without upgrading application dependencies, and upgrade 18.04 to 20.04.

issue: https://github.com/milvus-io/milvus/issues/17243

Signed-off-by: soulteary <soulteary@gmail.com>

### CODE REVIEW

**Comment by jennyli-z** [comment]
Please also update Update the `OS_NAME` to `ubuntu20.04` in below two places.
1.  https://github.com/milvus-io/milvus/blob/master/.env#L3
2. https://github.com/milvus-io/milvus/blob/master/build/build_image.sh#L27

**Comment by LoveEachDay** [comment]
@soulteary You should split this pr into two: one for the openblas image, and the other for milvus image.

**Comment by jennyli-z** [comment]
rerun ut

**Comment by jennyli-z** [comment]
keep

**Pull request closed without merging**
