### PR TITLE
Require code-checker and ut action for go code change

### PR DESCRIPTION
**Pull request by LoveEachDay**
Signed-off-by: Edward Zeng <jie.zeng@zilliz.com>
/kind improvement
/cc @scsven @jennyli-z

### CODE REVIEW

**Review by jennyli-z — APPROVED** [review]
/lgtm

**Comment by czs007** [comment]
What about c++ file changes ?

**Comment by LoveEachDay** [comment]
> What about c++ file changes ?

So the cpp file extension is always `.cpp`?

**Pull request merged**
