### PR TITLE
[2.2.2] Fix missing to clear load count

### PR DESCRIPTION
**Pull request by yah01**
Signed-off-by: yah01 <yang.cen@zilliz.com>
/kind bug
related #20898 #21299

### CODE REVIEW

**Comment by yah01** [comment]
rerun ut

**Review by congqixia — APPROVED** [review]
/lgtm

**Comment by yanliang567** [comment]
manual lgtm for not trigger the robot

**Review by congqixia — APPROVED** [review]
/lgtm

**Pull request merged**
