### PR TITLE
fix: remove date in the end of ubuntu base image version

### PR DESCRIPTION
**Pull request by jenkoon**
CVE issues https://github.com/milvus-io/milvus/issues/31997
This PR will fix **32** LOW and **42** MEDIUM CVEs

**ubuntu:focal-20220426 (ubuntu 20.04)**
Total: 99 (UNKNOWN: 0, LOW: 55, MEDIUM: 44, HIGH: 0, CRITICAL: 0)
**ubuntu:focal (ubuntu 20.04)**
Total: 25 (UNKNOWN: 0, LOW: 23, MEDIUM: 2, HIGH: 0, CRITICAL: 0)
image
image

### CODE REVIEW

**Comment by weiZhenkun** [comment]
@LoveEachDay could you review this PR?

**Comment by weiZhenkun** [comment]
@xiaofan-luan could you review this PR?

**Comment by LoveEachDay** [comment]
@weiZhenkun It's recommended to use a specific tag instead only `focal`, like `focal-2024010`.

**Comment by weiZhenkun** [comment]
https://github.com/zilliztech/attu/blob/main/Dockerfile#L22
https://github.com/milvus-io/bitnami-docker-etcd/blob/3.5.0-new/3.5/debian-11/Dockerfile#L1
what about here?

**Comment by LoveEachDay** [comment]
> https://github.com/zilliztech/attu/blob/main/Dockerfile#L22 https://github.com/milvus-io/bitnami-docker-etcd/blob/3.5.0-new/3.5/debian-11/Dockerfile#L1 what about here?

We don't release attu and etcd image frequently, while milvus image are building after every pr has been merged. So keep the runtime base image stable is critical.

**Comment by weiZhenkun** [comment]
@LoveEachDay Change to latest version [focal-20240427](https://hub.docker.com/layers/library/ubuntu/focal-20240427/images/sha256-cc9cc8169c9517ae035cf293b15f06922cb8c6c864d625a72b7b18667f264b70?context=explore) now.

**Review by LoveEachDay — APPROVED** [review]
/lgtm

**Pull request merged**
