### PR TITLE
Check collection name before execute CreateCollectionTask

### LINKED ISSUE #19990: [Bug]: Collection with duplicated collection name could be created
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 7d2ba60
- Deployment mode(standalone or cluster): both
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Collection with duplicated collection name could be created

### Expected Behavior

Duplicated collection name should return error

### Steps To Reproduce

_No response_

### Milvus Log

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by congqixia**
Fix #19990 

/kind bug

Signed-off-by: Congqi Xia <congqi.xia@zilliz.com>

### CODE REVIEW

**Comment by haorenfsa** [comment]
I'm just reading the code of rootcoord these days. It seems duplicated collection with exactly same schema will not return err is intended for idempotency according to the comment.

The check is performed in here: https://github.com/milvus-io/milvus/blob/a277e0d967b9a43de239d53e7c19f2466fdcdbc5/internal/rootcoord/create_collection_task.go#L273

**Comment by haorenfsa** [comment]
Btw,  it seems that if the dmlChannel refCnt leaks if duplicated collection with exactly same schema in current master.

An extra `addChannelsAndGetStartPositions()` is called without `removeDmlChannels()`

**Comment by xiaofan-luan** [comment]
involved @longjiquan in the loop

**Pull request closed without merging**
