### PR TITLE
[skip e2e]Update go version to 1.17 for Code Checker MinGW

### PR DESCRIPTION
**Pull request by jennyli-z**
Signed-off-by: Jenny Li <jing.li@zilliz.com>

### CODE REVIEW

**Comment by jennyli-z** [comment]
image
@matrixji  Hi, for the master latest code, it failed code checker MinGW.
We guess it probably is because of the go version, so I added stick go version to 1.17, but it still failed. Could you help give some clues? Thanks.

**Comment by matrixji** [comment]
It failed while checking clang-format, seems msys2 upgrades the clang tools to 14, I'll try to lock it back to version 13 and see if it works to unblock this issue.

**Comment by jennyli-z** [comment]
> It failed while checking clang-format, seems msys2 upgrades the clang tools to 14, I'll try to lock it back to version 13 and see if it works to unblock this issue.

https://github.com/milvus-io/milvus/pull/16760 @yhmo has fixed the issue in his pr, I will wait for this pr, and try again.

**Comment by matrixji** [comment]
> > It failed while checking clang-format, seems msys2 upgrades the clang tools to 14, I'll try to lock it back to version 13 and see if it works to unblock this issue.
> 
> #16760 @yhmo has fixed the issue in his pr, I will wait for this pr, and try again.


Still falling, need to force with go 1.17, I raise PR for it  https://github.com/milvus-io/milvus/pull/16797

**Comment by jennyli-z** [comment]
close the pr,as  https://github.com/milvus-io/milvus/pull/16797  is going to fix the same issue.

**Pull request closed without merging**
