### PR TITLE
fix: check sparse float before calling get_dim

### PR DESCRIPTION
**Pull request by sunby**
https://github.com/milvus-io/milvus/issues/37146

### CODE REVIEW

**Comment by sunby** [comment]
rerun go-sdk

**Comment by xiaofan-luan** [comment]
@sunby 
we may need to add more unit test for chunked impl since it's still to be a little fragile

**Comment by sunby** [comment]
> @sunby we may need to add more unit test for chunked impl since it's still to be a little fragile

Agree, I will add some ut.

**Pull request merged**
