### PR TITLE
remove pull target from qc recover

### PR DESCRIPTION
**Pull request by weiliu1031**
Signed-off-by: Wei Liu <wei.liu@zilliz.com>

issue: #27056 

/kind improvement

### CODE REVIEW

**Comment by xiaofan-luan** [comment]
what is this issue about?
can we create a issue for such a large feature?

**Comment by weiliu1031** [comment]
> what is this issue about? can we create a issue for such a large feature?

in the previous version, after qc recover and target not ready,  to avoid segment and channel been released.  we add the pull target step in recover progress, and if pull target failed,  try panic. 

to avoid the unnecessary panic logic, which is easily triggered during rolling upgrade. we remove the pull target step from recover progress.

i will create issue for this.

**Pull request merged**
