### PR TITLE
[cherry-pick]enable balance channel

### PR DESCRIPTION
**Pull request by weiliu1031**
Signed-off-by: Wei Liu <wei.liu@zilliz.com>
issue #22554 #23313 
cherry-pick #23227

### CODE REVIEW

**Comment by weiliu1031** [comment]
rerun ut

**Review by congqixia — APPROVED** [review]
/lgtm

**Comment by congqixia** [comment]
manual add ci-passed due to mac coder checker blocked

**Comment by xiaofan-luan** [comment]
@weiliu1031 
pls add more test on the balancer for the integrated test.

**Comment by weiliu1031** [comment]
> @weiliu1031 pls add more test on the balancer for the integrated test.

got it

**Pull request merged**
