### PR TITLE
Enable pprof service

### LINKED ISSUE #13978: [Enhancement]: Enable PProf in milvus
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

I would like to enable pprof server in milvus.

Package pprof serves via its HTTP server runtime profiling data in the format expected by the pprof visualization tool.

The package is typically only imported for the side effect of registering its HTTP handlers. The handled paths all begin with /debug/pprof/.

image

### Why is this needed?

we can take a look at heap profile, cpu profile and trace data through pprof.

Use the pprof tool to look at the heap profile:
`go tool pprof http://localhost:9091/debug/pprof/heap`

Or to look at a 30-second CPU profile:
`go tool pprof http://localhost:9091/debug/pprof/profile?seconds=30`

To collect a 5-second execution trace:
`wget -O trace.out http://localhost:9091/debug/pprof/trace?seconds=5`
`go tool trace trace.out`

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by czs007**
fix: #13978 
Signed-off-by: zhenshan.cao <zhenshan.cao@zilliz.com>

### CODE REVIEW

**Comment by xiaofan-luan** [comment]
do we enable the http web service?

**Comment by czs007** [comment]
> do we enable the http web service?

@xiaofan-luan 

Yes.
Currently, we have started  web service (":9091") in metrics with the http.DefaultServeMux defined in http package to handle `/metrics`.

```
http.Handle("/metrics", promhttp.Handler())
	go func() {
		if err := http.ListenAndServe(":9091", nil); err != nil {
			log.Error("handle metrics failed", zap.Error(err))
		}
	}()
```

Via import "net/http/pprof"
we can make existing websevice to handler methods prefix with `/debug/pprof/`.

in  the method `init` of `net/http/pprof`, it just add other handle functions:
```
func init() {
	http.HandleFunc("/debug/pprof/", Index)
	http.HandleFunc("/debug/pprof/cmdline", Cmdline)
	http.HandleFunc("/debug/pprof/profile", Profile)
	http.HandleFunc("/debug/pprof/symbol", Symbol)
	http.HandleFunc("/debug/pprof/trace", Trace)
}

```

No need to listen to other ports.

**Comment by czs007** [comment]
we can take a look at heap profile, cpu profile and trace data through pprof.

Use the pprof tool to look at the heap profile:
go tool pprof http://localhost:9091/debug/pprof/heap

Or to look at a 30-second CPU profile:
go tool pprof http://localhost:9091/debug/pprof/profile?seconds=30

To collect a 5-second execution trace:
wget -O trace.out http://localhost:6060/debug/pprof/trace?seconds=5
go tool trace trace.out

**Pull request merged**
