### PR TITLE
Deep copy rocksdb data to byte slice

### LINKED ISSUE #7300: Milvus crashed with panic when running nightly CI tests
#### Steps/Code to reproduce:
Run nightly CI test cases:

https://ci.milvus.io:18080/jenkins/blue/organizations/jenkins/milvus-nightly-ci/detail/master/115/artifacts

#### Expected result:
No panic

#### Actual results:
panic occurs

This first panic log may be in 0.log.20210825-064810

#### Environment:
- Milvus version(): 8aa13f9
- Deployment mode(standalone or cluster): standalone
- SDK version(e.g. pymilvus v2.0.0rc2):
pymilvus: 2.0.0rc5.dev20
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:

### PR DESCRIPTION
**Pull request by czs007**
Resolves: #7300 
Signed-off-by: zhenshan.cao <zhenshan.cao@zilliz.com>

### CODE REVIEW

**Comment by czs007** [comment]
Looking at the log, RootCoord believes that the proxy has been deactivated according to the lease_key in etcd. In fact, the proxy is still alive, but the proxy does not panic itself.

**Review by xiaofan-luan — APPROVED** [review]

**Pull request merged**
