### PR TITLE
Support milvus build on mac

### PR DESCRIPTION
**Pull request by cydrain**
Signed-off-by: Cai Yudong <yudong.cai@zilliz.com>
Issue: #16382 

```
1. 2 testcase files cannot build on mac because of tbb error:
    test_scalar_index_creator.cpp
    test_string_index.cpp
2. 1 testcase fail because marisa not supported on mac
    test_index_c_api.cpp::CStringIndexTest
3. 5 testcases get different result comparing between mac and linux
    test_indexing.cpp::Indexing::BinaryBruteForce
    test_query.cpp::Query::ExecWithPredicateLoader
    test_query.cpp::Query::ExecWithPredicate
    test_query.cpp::Query::ExecWithoutPredicate
    test_sealed.cpp::Sealed::LoadFieldData
```

### CODE REVIEW

**Comment by cydrain** [comment]
rerun ut

**Review by congqixia — APPROVED** [review]
/approve

**Pull request merged**
