### PR TITLE
Fix rocksmq retention test is not stable (#21925)

### PR DESCRIPTION
**Pull request by aoiasd**
relate: https://github.com/milvus-io/milvus/issues/25103 https://github.com/milvus-io/milvus/issues/21923
cherry-pick to 2.2

### CODE REVIEW

**Comment by aoiasd** [comment]
rerun ut

**Comment by aoiasd** [comment]
rerun ut

**Comment by aoiasd** [comment]
rerun ut

**Comment by aoiasd** [comment]
rerun ut

**Review by congqixia — APPROVED** [review]
/lgtm

**Pull request merged**
