### PR TITLE
Set jemalloc LD_PRELOAD env to docker image

### PR DESCRIPTION
**Pull request by bigsheeper**
Signed-off-by: bigsheeper <yihao.dai@zilliz.com>

issues: #16943

### CODE REVIEW

**Comment by bigsheeper** [comment]
rerun ut

**Review by LoveEachDay — APPROVED** [review]
/lgtm

**Comment by bigsheeper** [comment]
set jemalloc succuessfully at ci https://ci.milvus.io:18080/jenkins/blue/organizations/jenkins/milvus-ha-ci/detail/PR-17494/1/pipeline 

image

**Pull request merged**
