### PR TITLE
Remove recollect segment stats during starting datacoord

### PR DESCRIPTION
**Pull request by jaime0815**
/kind improvement
cherry pick #27410
pr: #27410

### CODE REVIEW

**Comment by Bennu-Li** [comment]
pr: #27410

**Comment by xiaofan-luan** [comment]
/assign @wayblink 
could you help on check this too

**Comment by wayblink** [comment]
@jaime0815 
The previous Recollect logic aims to resend segmentstats after DC restart to avoid missing segmentStats updates during the crash peroid. Missing segmentStats may lead to DC never trigger these segment flush.

Now we replace segmentStats updates with RPC. Since RPC is synchronous and will cache and resend segmentStats if RPC call failed, so there is no need to Recollect?

Is my understanding correct?

**Pull request merged**
