### PR TITLE
fix: Dynamic update replica failed if load config changes during restart

### PR DESCRIPTION
**Pull request by weiliu1031**
issue: #37446
milvus support dynamic update collection's replica through updating cluster load config. but if user stop milvus, and update cluster load config, then start up milvus again, the dynamic update replica policy won't be trigger. and collection's replica num will diff from cluster load config.

This PR check the load config changes after restart.

### CODE REVIEW

**Review by XuanYang-cn — APPROVED** [review]
/lgtm

**Review by congqixia — COMMENTED** [review]
/hold

**Comment by congqixia** [comment]
user explicitly specified replica number shall NOT be update with default replica number. maybe we shall mark `Auto` replica mode in loaded collection meta info

**Pull request closed without merging**
